// Auto-generated by scripts/gen-ts-client.ts
// Do not edit manually. Run: npm run codegen

import type { ChainablePromise } from "@tkwf/tsclient";

// ===== Query Operations =====
export const Query = {
  requestChallenge                : { field: 'requestChallenge', type: 'query' } as const,
  registerSecure                  : { field: 'registerSecure', type: 'query' } as const,
  createBank_Execute              : { field: 'createBank_Execute', type: 'query' } as const,
  bankDetail_Execute              : { field: 'bankDetail_Execute', type: 'query' } as const,
  knowledgeCard_Execute           : { field: 'knowledgeCard_Execute', type: 'query' } as const,
  importQuestions_Execute         : { field: 'importQuestions_Execute', type: 'query' } as const,
  listBanks_Execute               : { field: 'listBanks_Execute', type: 'query' } as const,
  reviewBackingPoints_Execute     : { field: 'reviewBackingPoints_Execute', type: 'query' } as const,
  acceptBuddyInvite_Execute       : { field: 'acceptBuddyInvite_Execute', type: 'query' } as const,
  buddyRank_Execute               : { field: 'buddyRank_Execute', type: 'query' } as const,
  inviteBuddy_Execute             : { field: 'inviteBuddy_Execute', type: 'query' } as const,
  listBuddies_Execute             : { field: 'listBuddies_Execute', type: 'query' } as const,
  rejectBuddyInvite_Execute       : { field: 'rejectBuddyInvite_Execute', type: 'query' } as const,
  removeBuddy_Execute             : { field: 'removeBuddy_Execute', type: 'query' } as const,
  activateMember_Execute          : { field: 'activateMember_Execute', type: 'query' } as const,
  createGroup_Execute             : { field: 'createGroup_Execute', type: 'query' } as const,
  exportRosterCsv_Execute         : { field: 'exportRosterCsv_Execute', type: 'query' } as const,
  generateInviteCodes_Execute     : { field: 'generateInviteCodes_Execute', type: 'query' } as const,
  rosterPreview_Execute           : { field: 'rosterPreview_Execute', type: 'query' } as const,
  importRoster_Execute            : { field: 'importRoster_Execute', type: 'query' } as const,
  listGroups_Execute              : { field: 'listGroups_Execute', type: 'query' } as const,
  manageGroupMembers_Execute      : { field: 'manageGroupMembers_Execute', type: 'query' } as const,
  execute_ByRequest               : { field: 'execute_ByRequest', type: 'query' } as const,
  setRankEnabled_Execute          : { field: 'setRankEnabled_Execute', type: 'query' } as const,
  submitJudgmentFeedback_Execute  : { field: 'submitJudgmentFeedback_Execute', type: 'query' } as const,
  createStudySession_Execute      : { field: 'createStudySession_Execute', type: 'query' } as const,
  hint_Execute                    : { field: 'hint_Execute', type: 'query' } as const,
  memoryStates_Execute            : { field: 'memoryStates_Execute', type: 'query' } as const,
  reviewQueue_Execute             : { field: 'reviewQueue_Execute', type: 'query' } as const,
  sessionResult_Execute           : { field: 'sessionResult_Execute', type: 'query' } as const,
  wrongQuestions_Execute          : { field: 'wrongQuestions_Execute', type: 'query' } as const,
  submitAttempt_Execute           : { field: 'submitAttempt_Execute', type: 'query' } as const,
  cancelSubscription_Execute      : { field: 'cancelSubscription_Execute', type: 'query' } as const,
  createParentRelation_Execute    : { field: 'createParentRelation_Execute', type: 'query' } as const,
  dashboardReport_Execute         : { field: 'dashboardReport_Execute', type: 'query' } as const,
  progressReport_Execute          : { field: 'progressReport_Execute', type: 'query' } as const,
  weaknessReport_Execute          : { field: 'weaknessReport_Execute', type: 'query' } as const,
  listChildren_Execute            : { field: 'listChildren_Execute', type: 'query' } as const,
  listSubscriptions_Execute       : { field: 'listSubscriptions_Execute', type: 'query' } as const,
  startTrial_Execute              : { field: 'startTrial_Execute', type: 'query' } as const,
  createPkMatch_Execute           : { field: 'createPkMatch_Execute', type: 'query' } as const,
  pkResult_Execute                : { field: 'pkResult_Execute', type: 'query' } as const,
  pkStats_Execute                 : { field: 'pkStats_Execute', type: 'query' } as const,
  joinPkMatch_Execute             : { field: 'joinPkMatch_Execute', type: 'query' } as const,
  submitPkAnswer_Execute          : { field: 'submitPkAnswer_Execute', type: 'query' } as const,
  myRanking_Execute               : { field: 'myRanking_Execute', type: 'query' } as const,
  rankings_Execute                : { field: 'rankings_Execute', type: 'query' } as const,
  heatmap_Execute                 : { field: 'heatmap_Execute', type: 'query' } as const,
  periodReport_Execute            : { field: 'periodReport_Execute', type: 'query' } as const,
  streak_Execute                  : { field: 'streak_Execute', type: 'query' } as const,
  statsWrongQuestions_Execute     : { field: 'statsWrongQuestions_Execute', type: 'query' } as const,
  createTask_Execute              : { field: 'createTask_Execute', type: 'query' } as const,
  ownerDashboard_Execute          : { field: 'ownerDashboard_Execute', type: 'query' } as const,
  taskDetail_Execute              : { field: 'taskDetail_Execute', type: 'query' } as const,
  listMyTasks_Execute             : { field: 'listMyTasks_Execute', type: 'query' } as const,
  listTasks_Execute               : { field: 'listTasks_Execute', type: 'query' } as const,
} as const;

// ===== Mutation Operations =====
export const Mutation = {
  loginByPassword       : { field: 'loginByPassword', type: 'mutation' } as const,
  loginByContext        : { field: 'loginByContext', type: 'mutation' } as const,
  logout                : { field: 'logout', type: 'mutation' } as const,
  changePasswordSecure  : { field: 'changePasswordSecure', type: 'mutation' } as const,
} as const;

// ===== Operation Selection Map =====
// Auto-generated subfield selections for object-typed returns.
// Used by Use()/Call() proxy to satisfy GraphQL subfield requirement.
export const operationSelection: Record<string, string> = {
  'acceptBuddyInvite_Execute': 'success errorCode buddyId',
  'activateMember_Execute': 'success errorCode groupId groupName role memberId',
  'bankDetail_Execute': 'success errorCode bank { isFromPersistentSource id uId bankId name subject version purpose privacy ownerId jsonPath tags status createTime updateTime } topics { chapterId title subTopics questionIds } previewQuestions { isFromPersistentSource id uId questionId bankId chapterId qType content knowledgePoints difficulty status supersededBy createTime updateTime }',
  'buddyRank_Execute': 'success errorCode rank metricValue trend snapshotDate',
  'cancelSubscription_Execute': 'success errorCode',
  'changePasswordSecure': 'success message',
  'createBank_Execute': 'success errorCode bankUid bankId',
  'createGroup_Execute': 'success errorCode groupId',
  'createParentRelation_Execute': 'success errorCode relationUid',
  'createPkMatch_Execute': 'success errorCode matchUid inviteCode',
  'createStudySession_Execute': 'success errorCode sessionUid questionCount',
  'createTask_Execute': 'success errorCode taskUid assignedCount',
  'dashboardReport_Execute': 'success errorCode subscription { status trialEndAt } todayCompleted streakDays weekProgress { learnedCount accuracy } subjectsMastery { subject accuracy } locked',
  'execute_ByRequest': 'success errorCode removed',
  'exportRosterCsv_Execute': 'success errorCode csvFileUrl expiresAt columns',
  'generateInviteCodes_Execute': 'success errorCode generatedCount',
  'heatmap_Execute': 'success errorCode days { isFromPersistentSource id uId userId statDate learnedCount starredCount reviewCount accuracy studySeconds createTime updateTime }',
  'hint_Execute': 'success errorCode hint difficultySlot hintSource',
  'importQuestions_Execute': 'success errorCode imported failed failures',
  'importRoster_Execute': 'success errorCode importId status sourceCount',
  'inviteBuddy_Execute': 'success errorCode inviteId expiresAt',
  'joinPkMatch_Execute': 'success errorCode matchUid mode questionCount perQuestionTimeS',
  'knowledgeCard_Execute': 'success errorCode cardType content',
  'listBanks_Execute': 'success errorCode items { bank { isFromPersistentSource id uId bankId name subject version purpose privacy ownerId jsonPath tags status createTime updateTime } topicCount questionCount } total',
  'listBuddies_Execute': 'success errorCode items { buddyId userId nickname avatarUrl streakDays status rank { isFromPersistentSource id uId userId scopeType scopeId subject metricType metricValue rank snapshotDate createTime updateTime } }',
  'listChildren_Execute': 'success errorCode items { studentUid nickname className hasSubscription }',
  'listGroups_Execute': 'success errorCode items { groupId name subject grade memberCount executionRate rankEnabled } pageIndex pageSize totalCount',
  'listMyTasks_Execute': 'success errorCode items { taskUid title progress deadlineAt status ownerName }',
  'listSubscriptions_Execute': 'success errorCode items { subscriptionUid studentUid studentNickname plan status trialEndAt periodEndAt }',
  'listTasks_Execute': 'success errorCode items { taskUid title deadlineAt status questionCount completionRate } total',
  'loginByContext': 'success userName displayName sessionKey accessToken refreshToken expiresAt deviceId extensions { key value }',
  'loginByPassword': 'success userName displayName sessionKey accessToken refreshToken expiresAt deviceId extensions { key value }',
  'logout': 'success userName displayName sessionKey accessToken refreshToken expiresAt deviceId extensions { key value }',
  'manageGroupMembers_Execute': 'success errorCode groupId members { userId nickname role joinedAt progress }',
  'memoryStates_Execute': 'success errorCode items { isFromPersistentSource id uId userId questionId bankId state consecutiveCorrect historyAccuracy easeFactor nextReviewAt lastAttemptId lastHintLevel createTime updateTime } totalCount pageIndex pageSize',
  'myRanking_Execute': 'success errorCode rank value trend rankChange rankEnabled',
  'ownerDashboard_Execute': 'success errorCode todayExecutionRate avgProgress overdueCount weakPointsTop5 { knowledgePoint accuracy } taskList { task { isFromPersistentSource id uId ownerId groupId bankId title description questionIds questionCount scenario sessionType allowRedo startedAt deadlineAt status createTime updateTime } completionRate status }',
  'periodReport_Execute': 'success errorCode learnedCount accuracy starredCount weakPoints { knowledgePoint accuracy }',
  'pkResult_Execute': 'success errorCode status winnerId finishReason winReason players { userId nickname score totalTimeMs aiComment }',
  'pkStats_Execute': 'success errorCode totalMatches wins draws winRate totalScore',
  'progressReport_Execute': 'success errorCode trend { isFromPersistentSource id uId userId statDate learnedCount starredCount reviewCount accuracy studySeconds createTime updateTime } vsLastWeek { learnedDelta weaknessShift }',
  'rankings_Execute': 'success errorCode snapshotDate rankEnabled items { rank userId nickname avatarUrl value trend isMe }',
  'registerSecure': 'success message',
  'rejectBuddyInvite_Execute': 'success errorCode',
  'removeBuddy_Execute': 'success errorCode',
  'requestChallenge': 'challengeToken salt iterations',
  'reviewBackingPoints_Execute': 'success errorCode imported skipped',
  'reviewQueue_Execute': 'success errorCode items { isFromPersistentSource id uId userId questionId bankId state consecutiveCorrect historyAccuracy easeFactor nextReviewAt lastAttemptId lastHintLevel createTime updateTime } overdueCount',
  'rosterPreview_Execute': 'success errorCode importId status sourceCount cleanedCount duplicateCount invalidCount preview',
  'sessionResult_Execute': 'success errorCode correctCount totalCount newStarCount blockedPoints { questionId knowledgePoint state }',
  'setRankEnabled_Execute': 'success errorCode groupId rankEnabled',
  'startTrial_Execute': 'success errorCode subscriptionUid status trialEndAt',
  'statsWrongQuestions_Execute': 'success errorCode items { knowledgePoint summary isFromPersistentSource id uId userId questionId bankId subject wrongCount lastWrongAt mastered createTime updateTime } total',
  'streak_Execute': 'success errorCode currentStreak longestStreak',
  'submitAttempt_Execute': 'success errorCode result confidence matchedKeywords missingKeywords hint preState postState nextReviewAt',
  'submitJudgmentFeedback_Execute': 'success errorCode feedbackUid status',
  'submitPkAnswer_Execute': 'success errorCode isCorrect result confidence score',
  'taskDetail_Execute': 'success errorCode task { isFromPersistentSource id uId ownerId groupId bankId title description questionIds questionCount scenario sessionType allowRedo startedAt deadlineAt status createTime updateTime } members { isFromPersistentSource id uId taskId userId status progress sessionId assignedAt startedAt completedAt createTime updateTime }',
  'weaknessReport_Execute': 'success errorCode weakPoints { subject knowledgePoint accuracy stateText }',
  'wrongQuestions_Execute': 'success errorCode items { knowledgePoint summary isFromPersistentSource id uId userId questionId bankId subject wrongCount lastWrongAt mastered createTime updateTime } totalCount pageIndex pageSize',
} as const;

// ===== Schema Types (Auto-generated from schema.graphql) =====

export interface ChallengeResponse {
  challengeToken: string;
  salt: string;
  iterations: number;
}

export interface RegisterResult {
  success: boolean;
  message: string | null;
}

export interface RegisterSecureInput {
  userName: string;
  clientHash: string;
  salt: string;
}

export interface CreateBankResDto {
  success: boolean;
  errorCode: string | null;
  bankUid: string;
  bankId: string;
}

export interface CreateBankReqDtoInput {
  name: string;
  subject: string;
  purpose: string | null;
  privacy: string | null;
  groupIds: string | null;
}

export interface GetBankDetailResDto {
  success: boolean;
  errorCode: string | null;
  bank: BanksDto | null;
  topics: Array<TopicNodeDto>;
  previewQuestions: Array<QuestionsDto>;
}

export interface GetBankDetailReqDtoInput {
  bankId: string;
}

export interface GetKnowledgeCardResDto {
  success: boolean;
  errorCode: string | null;
  cardType: string;
  content: string;
}

export interface GetKnowledgeCardReqDtoInput {
  questionId: string;
}

export interface ImportQuestionsResDto {
  success: boolean;
  errorCode: string | null;
  imported: number;
  failed: number;
  failures: Array<string>;
}

export interface ImportQuestionsReqDtoInput {
  bankId: string;
  file: number | null;
  rawText: string | null;
  topic: string | null;
}

export interface ListBanksResDto {
  success: boolean;
  errorCode: string | null;
  items: Array<BankListItemDto>;
  total: number;
}

export interface ListBanksReqDtoInput {
  subject: string | null;
  purpose: string | null;
  pageIndex: number;
  pageSize: number;
}

export interface ReviewBackingPointsResDto {
  success: boolean;
  errorCode: string | null;
  imported: number;
  skipped: number;
}

export interface ReviewBackingPointsReqDtoInput {
  bankId: string;
  batchId: string;
  items: ReviewItemInputDtoInput;
  skipUnreviewed: boolean;
}

export interface AcceptBuddyInviteResDto {
  success: boolean;
  errorCode: string | null;
  buddyId: string;
}

export interface AcceptBuddyInviteReqDtoInput {
  inviteId: string;
}

export interface GetBuddyRankResDto {
  success: boolean;
  errorCode: string | null;
  rank: number;
  metricValue: number;
  trend: string;
  snapshotDate: string;
}

export interface GetBuddyRankReqDtoInput {
  buddyId: string;
  scopeType: string;
  scopeId: string;
  subject: string | null;
}

export interface InviteBuddyResDto {
  success: boolean;
  errorCode: string | null;
  inviteId: string;
  expiresAt: string;
}

export interface InviteBuddyReqDtoInput {
  inviteeUserId: number;
}

export interface ListBuddiesResDto {
  success: boolean;
  errorCode: string | null;
  items: Array<BuddyListItemDto>;
}

export interface RejectBuddyInviteResDto {
  success: boolean;
  errorCode: string | null;
}

export interface RejectBuddyInviteReqDtoInput {
  inviteId: string;
}

export interface RemoveBuddyResDto {
  success: boolean;
  errorCode: string | null;
}

export interface RemoveBuddyReqDtoInput {
  buddyId: string;
}

export interface ActivateMemberResDto {
  success: boolean;
  errorCode: string | null;
  groupId: number;
  groupName: string;
  role: string;
  memberId: number;
}

export interface ActivateMemberReqDtoInput {
  oneTimeCode: string;
  phoneLast4: string;
}

export interface CreateGroupResDto {
  success: boolean;
  errorCode: string | null;
  groupId: number;
}

export interface CreateGroupReqDtoInput {
  betaCode: string;
  name: string;
  subject: string;
  grade: string | null;
}

export interface ExportRosterCsvResDto {
  success: boolean;
  errorCode: string | null;
  csvFileUrl: string | null;
  expiresAt: string | null;
  columns: Array<string>;
}

export interface ExportRosterCsvReqDtoInput {
  groupId: number;
  importId: number;
}

export interface GenerateInviteCodesResDto {
  success: boolean;
  errorCode: string | null;
  generatedCount: number;
}

export interface GenerateInviteCodesReqDtoInput {
  groupId: number;
  importId: number;
  confirm: boolean;
}

export interface RosterPreviewResDto {
  success: boolean;
  errorCode: string | null;
  importId: number;
  status: string | null;
  sourceCount: number;
  cleanedCount: number;
  duplicateCount: number;
  invalidCount: number;
  preview: Array<string>;
}

export interface GetRosterPreviewReqDtoInput {
  groupId: number;
  importId: number;
}

export interface ImportRosterResDto {
  success: boolean;
  errorCode: string | null;
  importId: number;
  status: string | null;
  sourceCount: number;
}

export interface ImportRosterReqDtoInput {
  groupId: number;
  method: string;
  rawText: string | null;
}

export interface ListGroupsResDto {
  success: boolean;
  errorCode: string | null;
  items: Array<GroupListItemDto>;
  pageIndex: number;
  pageSize: number;
  totalCount: number;
}

export interface ListGroupsReqDtoInput {
  pageIndex: number;
  pageSize: number;
}

export interface GroupDetailResDto {
  success: boolean;
  errorCode: string | null;
  groupId: number;
  members: Array<MemberItemDto>;
}

export interface GetMembersReqDtoInput {
  groupId: number;
}

export interface RemoveMemberResDto {
  success: boolean;
  errorCode: string | null;
  removed: boolean;
}

export interface RemoveMemberReqDtoInput {
  groupId: number;
  userId: number;
}

export interface SetRankEnabledResDto {
  success: boolean;
  errorCode: string | null;
  groupId: number;
  rankEnabled: boolean;
}

export interface SetRankEnabledReqDtoInput {
  groupId: number;
  rankEnabled: boolean;
}

export interface SubmitJudgmentFeedbackResDto {
  success: boolean;
  errorCode: string | null;
  feedbackUid: string;
  status: string;
}

export interface SubmitJudgmentFeedbackReqDtoInput {
  attemptUid: string;
  feedbackType: string | null;
}

export interface CreateStudySessionResDto {
  success: boolean;
  errorCode: string | null;
  sessionUid: string;
  questionCount: number;
}

export interface CreateStudySessionReqDtoInput {
  scenario: string;
  bankId: string;
  sessionType: string;
  taskId: number | null;
  questionCount: number;
}

export interface GetHintResDto {
  success: boolean;
  errorCode: string | null;
  hint: string;
  difficultySlot: string;
  hintSource: string;
}

export interface GetHintReqDtoInput {
  questionId: string;
  difficultySlot: string | null;
}

export interface GetMemoryStatesResDto {
  success: boolean;
  errorCode: string | null;
  items: Array<MemoryStatesDto>;
  totalCount: number;
  pageIndex: number;
  pageSize: number;
}

export interface GetMemoryStatesReqDtoInput {
  bankId: string | null;
  state: string | null;
  pageIndex: number;
  pageSize: number;
}

export interface GetReviewQueueResDto {
  success: boolean;
  errorCode: string | null;
  items: Array<MemoryStatesDto>;
  overdueCount: number;
}

export interface GetReviewQueueReqDtoInput {
  date: string;
  pageIndex: number;
  pageSize: number;
}

export interface GetSessionResultResDto {
  success: boolean;
  errorCode: string | null;
  correctCount: number;
  totalCount: number;
  newStarCount: number;
  blockedPoints: Array<BlockedPointDto>;
}

export interface GetSessionResultReqDtoInput {
  sessionUid: string;
}

export interface GetWrongQuestionsResDto {
  success: boolean;
  errorCode: string | null;
  items: Array<WrongQuestionsDto>;
  totalCount: number;
  pageIndex: number;
  pageSize: number;
}

export interface GetWrongQuestionsReqDtoInput {
  mastered: boolean;
  subject: string | null;
  pageIndex: number;
  pageSize: number;
}

export interface SubmitAttemptResDto {
  success: boolean;
  errorCode: string | null;
  result: string;
  confidence: number | null;
  matchedKeywords: Array<string>;
  missingKeywords: Array<string>;
  hint: string;
  preState: string;
  postState: string;
  nextReviewAt: string;
}

export interface SubmitAttemptReqDtoInput {
  sessionUid: string;
  questionId: string;
  userAnswer: string;
  hintLevel: string;
  timeCostMs: number | null;
}

export interface CancelSubscriptionResDto {
  success: boolean;
  errorCode: string | null;
}

export interface CancelSubscriptionReqDtoInput {
  subscriptionUid: string;
}

export interface CreateParentRelationResDto {
  success: boolean;
  errorCode: string | null;
  relationUid: string;
}

export interface CreateParentRelationReqDtoInput {
  studentId: number;
  relation: string | null;
}

export interface GetDashboardReportResDto {
  success: boolean;
  errorCode: string | null;
  subscription: SubscriptionBriefDto | null;
  todayCompleted: boolean | null;
  streakDays: number | null;
  weekProgress: WeekProgressDto | null;
  subjectsMastery: Array<SubjectMasteryDto>;
  locked: boolean;
}

export interface GetDashboardReportReqDtoInput {
  studentId: number;
}

export interface GetProgressReportResDto {
  success: boolean;
  errorCode: string | null;
  trend: Array<DailyStatsDto>;
  vsLastWeek: VsLastWeekDto | null;
}

export interface GetProgressReportReqDtoInput {
  studentId: number;
  period: string;
}

export interface GetWeaknessReportResDto {
  success: boolean;
  errorCode: string | null;
  weakPoints: Array<ParentWeakPointDto>;
}

export interface GetWeaknessReportReqDtoInput {
  studentId: number;
}

export interface ListChildrenResDto {
  success: boolean;
  errorCode: string | null;
  items: Array<ChildItemDto>;
}

export interface ListSubscriptionsResDto {
  success: boolean;
  errorCode: string | null;
  items: Array<SubscriptionItemDto>;
}

export interface StartTrialResDto {
  success: boolean;
  errorCode: string | null;
  subscriptionUid: string;
  status: string;
  trialEndAt: string | null;
}

export interface StartTrialReqDtoInput {
  studentId: number;
}

export interface CreatePkMatchResDto {
  success: boolean;
  errorCode: string | null;
  matchUid: string;
  inviteCode: string;
}

export interface CreatePkMatchReqDtoInput {
  opponentUserId: number;
  bankId: string;
  topic: string | null;
  questionCount: number;
  mode: string | null;
}

export interface GetPkResultResDto {
  success: boolean;
  errorCode: string | null;
  status: string;
  winnerId: number | null;
  finishReason: string;
  winReason: string | null;
  players: Array<PkPlayerResultDto>;
}

export interface GetPkResultReqDtoInput {
  matchUid: string;
}

export interface GetPkStatsResDto {
  success: boolean;
  errorCode: string | null;
  totalMatches: number;
  wins: number;
  draws: number;
  winRate: number;
  totalScore: number;
}

export interface GetPkStatsReqDtoInput {
  userUid: string | null;
}

export interface JoinPkMatchResDto {
  success: boolean;
  errorCode: string | null;
  matchUid: string;
  mode: string;
  questionCount: number;
  perQuestionTimeS: number;
}

export interface JoinPkMatchReqDtoInput {
  matchUid: string;
  inviteCode: string;
}

export interface SubmitPkAnswerResDto {
  success: boolean;
  errorCode: string | null;
  isCorrect: boolean;
  result: string;
  confidence: number | null;
  score: number;
}

export interface SubmitPkAnswerReqDtoInput {
  matchUid: string;
  questionId: string;
  userAnswer: string;
  timeCostMs: number;
}

export interface GetMyRankingResDto {
  success: boolean;
  errorCode: string | null;
  rank: number;
  value: number;
  trend: string;
  rankChange: number;
  rankEnabled: boolean;
}

export interface GetMyRankingReqDtoInput {
  scopeType: string;
  scopeId: string;
  subject: string | null;
  metric: string;
}

export interface GetRankingsResDto {
  success: boolean;
  errorCode: string | null;
  snapshotDate: string;
  rankEnabled: boolean;
  items: Array<RankingItemDto>;
}

export interface GetRankingsReqDtoInput {
  scopeType: string;
  scopeId: string;
  subject: string | null;
  metric: string;
  date: string | null;
  limit: number;
}

export interface GetHeatmapResDto {
  success: boolean;
  errorCode: string | null;
  days: Array<DailyStatsDto>;
}

export interface GetHeatmapReqDtoInput {
  start: string;
  end: string;
}

export interface GetPeriodReportResDto {
  success: boolean;
  errorCode: string | null;
  learnedCount: number;
  accuracy: number | null;
  starredCount: number;
  weakPoints: Array<WeakPointDto>;
}

export interface GetPeriodReportReqDtoInput {
  period: string;
}

export interface GetStreakResDto {
  success: boolean;
  errorCode: string | null;
  currentStreak: number;
  longestStreak: number;
}

export interface StatsGetWrongQuestionsResDto {
  success: boolean;
  errorCode: string | null;
  items: Array<WrongQuestionsDto>;
  total: number;
}

export interface CreateTaskResDto {
  success: boolean;
  errorCode: string | null;
  taskUid: string;
  assignedCount: number;
}

export interface CreateTaskReqDtoInput {
  groupUid: string;
  bankId: string | null;
  title: string;
  description: string | null;
  questionIds: string;
  scenario: string | null;
  sessionType: string | null;
  allowRedo: boolean;
  deadlineAt: string | null;
}

export interface GetOwnerDashboardResDto {
  success: boolean;
  errorCode: string | null;
  todayExecutionRate: number;
  avgProgress: number;
  overdueCount: number;
  weakPointsTop5: Array<WeakPointDto>;
  taskList: Array<DashboardTaskDto>;
}

export interface GetOwnerDashboardReqDtoInput {
  groupUid: string;
}

export interface GetTaskDetailResDto {
  success: boolean;
  errorCode: string | null;
  task: TasksDto | null;
  members: Array<TaskAssignmentsDto>;
}

export interface GetTaskDetailReqDtoInput {
  taskUid: string;
}

export interface ListMyTasksResDto {
  success: boolean;
  errorCode: string | null;
  items: Array<MyTaskItemDto>;
}

export interface ListMyTasksReqDtoInput {
  status: string | null;
}

export interface ListTasksResDto {
  success: boolean;
  errorCode: string | null;
  items: Array<TaskListItemDto>;
  total: number;
}

export interface ListTasksReqDtoInput {
  groupUid: string | null;
  status: string | null;
  pageIndex: number;
  pageSize: number;
}

export interface LoginPayload {
  success: boolean;
  userName: string | null;
  displayName: string | null;
  sessionKey: string | null;
  accessToken: string | null;
  refreshToken: string | null;
  expiresAt: string | null;
  deviceId: string | null;
  extensions: Array<ExtensionEntry>;
}

export interface LoginContextInput {
  userName: string;
  credential: string;
  loginFrom: string;
  authType: string;
  authInfo: string | null;
  deviceId: string | null;
}

export interface ChangePasswordSecureInput {
  oldChallengeResponse: string;
  challengeToken: string;
  newClientHash: string;
  newSalt: string;
}

export interface BanksDto {
  isFromPersistentSource: boolean;
  id: number;
  uId: string;
  bankId: string;
  name: string;
  subject: string;
  version: string;
  purpose: string;
  privacy: string;
  ownerId: number | null;
  jsonPath: string;
  tags: Array<string>;
  status: string;
  createTime: string;
  updateTime: string;
}

export interface TopicNodeDto {
  chapterId: string;
  title: string;
  subTopics: Array<string>;
  questionIds: Array<string>;
}

export interface QuestionsDto {
  isFromPersistentSource: boolean;
  id: number;
  uId: string;
  questionId: string;
  bankId: string;
  chapterId: string | null;
  qType: string;
  content: string;
  knowledgePoints: Array<string>;
  difficulty: number;
  status: string;
  supersededBy: string | null;
  createTime: string;
  updateTime: string;
}

export interface BankListItemDto {
  bank: BanksDto | null;
  topicCount: number;
  questionCount: number;
}

export interface ReviewItemInputDtoInput {
  questionId: string;
  editedStem: string | null;
  editedAnswer: string | null;
}

export interface BuddyListItemDto {
  buddyId: string;
  userId: number;
  nickname: string;
  avatarUrl: string;
  streakDays: number;
  status: string;
  rank: RankSnapshotsDto | null;
}

export interface GroupListItemDto {
  groupId: number;
  name: string;
  subject: string;
  grade: string | null;
  memberCount: number;
  executionRate: number;
  rankEnabled: boolean;
}

export interface MemberItemDto {
  userId: number;
  nickname: string | null;
  role: string;
  joinedAt: string;
  progress: number;
}

export interface MemoryStatesDto {
  isFromPersistentSource: boolean;
  id: number;
  uId: string;
  userId: number;
  questionId: string;
  bankId: string;
  state: string;
  consecutiveCorrect: number;
  historyAccuracy: number;
  easeFactor: number;
  nextReviewAt: string;
  lastAttemptId: number | null;
  lastHintLevel: string;
  createTime: string;
  updateTime: string;
}

export interface BlockedPointDto {
  questionId: string;
  knowledgePoint: string;
  state: string;
}

export interface WrongQuestionsDto {
  knowledgePoint: string;
  summary: string;
  isFromPersistentSource: boolean;
  id: number;
  uId: string;
  userId: number;
  questionId: string;
  bankId: string;
  subject: string;
  wrongCount: number;
  lastWrongAt: string;
  mastered: boolean;
  createTime: string;
  updateTime: string;
}

export interface SubscriptionBriefDto {
  status: string;
  trialEndAt: string | null;
}

export interface WeekProgressDto {
  learnedCount: number;
  accuracy: number | null;
}

export interface SubjectMasteryDto {
  subject: string;
  accuracy: number;
}

export interface DailyStatsDto {
  isFromPersistentSource: boolean;
  id: number;
  uId: string;
  userId: number;
  statDate: string;
  learnedCount: number;
  starredCount: number;
  reviewCount: number;
  accuracy: number | null;
  studySeconds: number;
  createTime: string;
  updateTime: string;
}

export interface VsLastWeekDto {
  learnedDelta: number;
  weaknessShift: number;
}

export interface ParentWeakPointDto {
  subject: string;
  knowledgePoint: string;
  accuracy: number;
  stateText: string;
}

export interface ChildItemDto {
  studentUid: string;
  nickname: string;
  className: string;
  hasSubscription: boolean;
}

export interface SubscriptionItemDto {
  subscriptionUid: string;
  studentUid: string;
  studentNickname: string;
  plan: string;
  status: string;
  trialEndAt: string | null;
  periodEndAt: string | null;
}

export interface PkPlayerResultDto {
  userId: number;
  nickname: string;
  score: number;
  totalTimeMs: number;
  aiComment: string;
}

export interface RankingItemDto {
  rank: number;
  userId: number;
  nickname: string;
  avatarUrl: string;
  value: number;
  trend: string;
  isMe: boolean;
}

export interface WeakPointDto {
  knowledgePoint: string;
  accuracy: number;
}

export interface DashboardTaskDto {
  task: TasksDto | null;
  completionRate: number;
  status: string;
}

export interface TasksDto {
  isFromPersistentSource: boolean;
  id: number;
  uId: string;
  ownerId: number;
  groupId: number;
  bankId: string | null;
  title: string;
  description: string | null;
  questionIds: Array<string>;
  questionCount: number;
  scenario: string;
  sessionType: string;
  allowRedo: boolean;
  startedAt: string;
  deadlineAt: string | null;
  status: string;
  createTime: string;
  updateTime: string;
}

export interface TaskAssignmentsDto {
  isFromPersistentSource: boolean;
  id: number;
  uId: string;
  taskId: number;
  userId: number;
  status: string;
  progress: number;
  sessionId: number | null;
  assignedAt: string;
  startedAt: string | null;
  completedAt: string | null;
  createTime: string;
  updateTime: string;
}

export interface MyTaskItemDto {
  taskUid: string;
  title: string;
  progress: number;
  deadlineAt: string | null;
  status: string;
  ownerName: string;
}

export interface TaskListItemDto {
  taskUid: string;
  title: string;
  deadlineAt: string | null;
  status: string;
  questionCount: number;
  completionRate: number;
}

export interface ExtensionEntry {
  key: string;
  value: string | null;
}

export interface RankSnapshotsDto {
  isFromPersistentSource: boolean;
  id: number;
  uId: string;
  userId: number;
  scopeType: string;
  scopeId: string | null;
  subject: string;
  metricType: string;
  metricValue: number;
  rank: number;
  snapshotDate: string;
  createTime: string;
  updateTime: string;
}

// ===== Operation Argument Types =====

export interface RegisterSecureArgs {
  input?: RegisterSecureInput;
}

export interface CreateBank_ExecuteArgs {
  request?: CreateBankReqDtoInput;
}

export interface BankDetail_ExecuteArgs {
  request?: GetBankDetailReqDtoInput;
}

export interface KnowledgeCard_ExecuteArgs {
  request?: GetKnowledgeCardReqDtoInput;
}

export interface ImportQuestions_ExecuteArgs {
  request?: ImportQuestionsReqDtoInput;
}

export interface ListBanks_ExecuteArgs {
  request?: ListBanksReqDtoInput;
}

export interface ReviewBackingPoints_ExecuteArgs {
  request?: ReviewBackingPointsReqDtoInput;
}

export interface AcceptBuddyInvite_ExecuteArgs {
  request?: AcceptBuddyInviteReqDtoInput;
}

export interface BuddyRank_ExecuteArgs {
  request?: GetBuddyRankReqDtoInput;
}

export interface InviteBuddy_ExecuteArgs {
  request?: InviteBuddyReqDtoInput;
}

export interface RejectBuddyInvite_ExecuteArgs {
  request?: RejectBuddyInviteReqDtoInput;
}

export interface RemoveBuddy_ExecuteArgs {
  request?: RemoveBuddyReqDtoInput;
}

export interface ActivateMember_ExecuteArgs {
  request?: ActivateMemberReqDtoInput;
}

export interface CreateGroup_ExecuteArgs {
  request?: CreateGroupReqDtoInput;
}

export interface ExportRosterCsv_ExecuteArgs {
  request?: ExportRosterCsvReqDtoInput;
}

export interface GenerateInviteCodes_ExecuteArgs {
  request?: GenerateInviteCodesReqDtoInput;
}

export interface RosterPreview_ExecuteArgs {
  request?: GetRosterPreviewReqDtoInput;
}

export interface ImportRoster_ExecuteArgs {
  request?: ImportRosterReqDtoInput;
}

export interface ListGroups_ExecuteArgs {
  request?: ListGroupsReqDtoInput;
}

export interface ManageGroupMembers_ExecuteArgs {
  request?: GetMembersReqDtoInput;
}

export interface Execute_ByRequestArgs {
  request?: RemoveMemberReqDtoInput;
}

export interface SetRankEnabled_ExecuteArgs {
  request?: SetRankEnabledReqDtoInput;
}

export interface SubmitJudgmentFeedback_ExecuteArgs {
  request?: SubmitJudgmentFeedbackReqDtoInput;
}

export interface CreateStudySession_ExecuteArgs {
  request?: CreateStudySessionReqDtoInput;
}

export interface Hint_ExecuteArgs {
  request?: GetHintReqDtoInput;
}

export interface MemoryStates_ExecuteArgs {
  request?: GetMemoryStatesReqDtoInput;
}

export interface ReviewQueue_ExecuteArgs {
  request?: GetReviewQueueReqDtoInput;
}

export interface SessionResult_ExecuteArgs {
  request?: GetSessionResultReqDtoInput;
}

export interface WrongQuestions_ExecuteArgs {
  request?: GetWrongQuestionsReqDtoInput;
}

export interface SubmitAttempt_ExecuteArgs {
  request?: SubmitAttemptReqDtoInput;
}

export interface CancelSubscription_ExecuteArgs {
  request?: CancelSubscriptionReqDtoInput;
}

export interface CreateParentRelation_ExecuteArgs {
  request?: CreateParentRelationReqDtoInput;
}

export interface DashboardReport_ExecuteArgs {
  request?: GetDashboardReportReqDtoInput;
}

export interface ProgressReport_ExecuteArgs {
  request?: GetProgressReportReqDtoInput;
}

export interface WeaknessReport_ExecuteArgs {
  request?: GetWeaknessReportReqDtoInput;
}

export interface StartTrial_ExecuteArgs {
  request?: StartTrialReqDtoInput;
}

export interface CreatePkMatch_ExecuteArgs {
  request?: CreatePkMatchReqDtoInput;
}

export interface PkResult_ExecuteArgs {
  request?: GetPkResultReqDtoInput;
}

export interface PkStats_ExecuteArgs {
  request?: GetPkStatsReqDtoInput;
}

export interface JoinPkMatch_ExecuteArgs {
  request?: JoinPkMatchReqDtoInput;
}

export interface SubmitPkAnswer_ExecuteArgs {
  request?: SubmitPkAnswerReqDtoInput;
}

export interface MyRanking_ExecuteArgs {
  request?: GetMyRankingReqDtoInput;
}

export interface Rankings_ExecuteArgs {
  request?: GetRankingsReqDtoInput;
}

export interface Heatmap_ExecuteArgs {
  request?: GetHeatmapReqDtoInput;
}

export interface PeriodReport_ExecuteArgs {
  request?: GetPeriodReportReqDtoInput;
}

export interface StatsWrongQuestions_ExecuteArgs {
  request?: GetWrongQuestionsReqDtoInput;
}

export interface CreateTask_ExecuteArgs {
  request?: CreateTaskReqDtoInput;
}

export interface OwnerDashboard_ExecuteArgs {
  request?: GetOwnerDashboardReqDtoInput;
}

export interface TaskDetail_ExecuteArgs {
  request?: GetTaskDetailReqDtoInput;
}

export interface ListMyTasks_ExecuteArgs {
  request?: ListMyTasksReqDtoInput;
}

export interface ListTasks_ExecuteArgs {
  request?: ListTasksReqDtoInput;
}

export interface LoginByContextArgs {
  input?: LoginContextInput;
}

export interface ChangePasswordSecureArgs {
  input?: ChangePasswordSecureInput;
}

// ===== Service Typed Interfaces =====
export interface AcceptBuddyInvite_ExecuteService {
  acceptBuddyInvite_Execute(args?: AcceptBuddyInvite_ExecuteArgs): ChainablePromise<AcceptBuddyInviteResDto>;
}

export interface ActivateMember_ExecuteService {
  activateMember_Execute(args?: ActivateMember_ExecuteArgs): ChainablePromise<ActivateMemberResDto>;
}

export interface AuthService {
  loginByPassword(args?: Record<string, unknown>): ChainablePromise<LoginPayload>;
  loginByContext(args?: LoginByContextArgs): ChainablePromise<LoginPayload>;
  logout(args?: Record<string, unknown>): ChainablePromise<LoginPayload>;
}

export interface Bank_ExecuteService {
  createBank_Execute(args?: CreateBank_ExecuteArgs): ChainablePromise<CreateBankResDto>;
}

export interface BankDetail_ExecuteService {
  bankDetail_Execute(args?: BankDetail_ExecuteArgs): ChainablePromise<GetBankDetailResDto>;
}

export interface Banks_ExecuteService {
  listBanks_Execute(args?: ListBanks_ExecuteArgs): ChainablePromise<ListBanksResDto>;
}

export interface Buddies_ExecuteService {
  listBuddies_Execute(args?: Record<string, unknown>): ChainablePromise<ListBuddiesResDto>;
}

export interface Buddy_ExecuteService {
  removeBuddy_Execute(args?: RemoveBuddy_ExecuteArgs): ChainablePromise<RemoveBuddyResDto>;
}

export interface BuddyRank_ExecuteService {
  buddyRank_Execute(args?: BuddyRank_ExecuteArgs): ChainablePromise<GetBuddyRankResDto>;
}

export interface CancelSubscription_ExecuteService {
  cancelSubscription_Execute(args?: CancelSubscription_ExecuteArgs): ChainablePromise<CancelSubscriptionResDto>;
}

export interface ChangePasswordSecureService {
  changePasswordSecure(args?: ChangePasswordSecureArgs): ChainablePromise<RegisterResult>;
}

export interface Children_ExecuteService {
  listChildren_Execute(args?: Record<string, unknown>): ChainablePromise<ListChildrenResDto>;
}

export interface DashboardReport_ExecuteService {
  dashboardReport_Execute(args?: DashboardReport_ExecuteArgs): ChainablePromise<GetDashboardReportResDto>;
}

export interface Execute_ByRequestService {
  execute_ByRequest(args?: Execute_ByRequestArgs): ChainablePromise<RemoveMemberResDto>;
}

export interface ExportRosterCsv_ExecuteService {
  exportRosterCsv_Execute(args?: ExportRosterCsv_ExecuteArgs): ChainablePromise<ExportRosterCsvResDto>;
}

export interface GenerateInviteCodes_ExecuteService {
  generateInviteCodes_Execute(args?: GenerateInviteCodes_ExecuteArgs): ChainablePromise<GenerateInviteCodesResDto>;
}

export interface Group_ExecuteService {
  createGroup_Execute(args?: CreateGroup_ExecuteArgs): ChainablePromise<CreateGroupResDto>;
}

export interface Groups_ExecuteService {
  listGroups_Execute(args?: ListGroups_ExecuteArgs): ChainablePromise<ListGroupsResDto>;
}

export interface Heatmap_ExecuteService {
  heatmap_Execute(args?: Heatmap_ExecuteArgs): ChainablePromise<GetHeatmapResDto>;
}

export interface Hint_ExecuteService {
  hint_Execute(args?: Hint_ExecuteArgs): ChainablePromise<GetHintResDto>;
}

export interface ImportQuestions_ExecuteService {
  importQuestions_Execute(args?: ImportQuestions_ExecuteArgs): ChainablePromise<ImportQuestionsResDto>;
}

export interface ImportRoster_ExecuteService {
  importRoster_Execute(args?: ImportRoster_ExecuteArgs): ChainablePromise<ImportRosterResDto>;
}

export interface InviteBuddy_ExecuteService {
  inviteBuddy_Execute(args?: InviteBuddy_ExecuteArgs): ChainablePromise<InviteBuddyResDto>;
}

export interface JoinPkMatch_ExecuteService {
  joinPkMatch_Execute(args?: JoinPkMatch_ExecuteArgs): ChainablePromise<JoinPkMatchResDto>;
}

export interface KnowledgeCard_ExecuteService {
  knowledgeCard_Execute(args?: KnowledgeCard_ExecuteArgs): ChainablePromise<GetKnowledgeCardResDto>;
}

export interface ManageGroupMembers_ExecuteService {
  manageGroupMembers_Execute(args?: ManageGroupMembers_ExecuteArgs): ChainablePromise<GroupDetailResDto>;
}

export interface MemoryStates_ExecuteService {
  memoryStates_Execute(args?: MemoryStates_ExecuteArgs): ChainablePromise<GetMemoryStatesResDto>;
}

export interface MyRanking_ExecuteService {
  myRanking_Execute(args?: MyRanking_ExecuteArgs): ChainablePromise<GetMyRankingResDto>;
}

export interface MyTasks_ExecuteService {
  listMyTasks_Execute(args?: ListMyTasks_ExecuteArgs): ChainablePromise<ListMyTasksResDto>;
}

export interface OwnerDashboard_ExecuteService {
  ownerDashboard_Execute(args?: OwnerDashboard_ExecuteArgs): ChainablePromise<GetOwnerDashboardResDto>;
}

export interface ParentRelation_ExecuteService {
  createParentRelation_Execute(args?: CreateParentRelation_ExecuteArgs): ChainablePromise<CreateParentRelationResDto>;
}

export interface PeriodReport_ExecuteService {
  periodReport_Execute(args?: PeriodReport_ExecuteArgs): ChainablePromise<GetPeriodReportResDto>;
}

export interface PkMatch_ExecuteService {
  createPkMatch_Execute(args?: CreatePkMatch_ExecuteArgs): ChainablePromise<CreatePkMatchResDto>;
}

export interface PkResult_ExecuteService {
  pkResult_Execute(args?: PkResult_ExecuteArgs): ChainablePromise<GetPkResultResDto>;
}

export interface PkStats_ExecuteService {
  pkStats_Execute(args?: PkStats_ExecuteArgs): ChainablePromise<GetPkStatsResDto>;
}

export interface ProgressReport_ExecuteService {
  progressReport_Execute(args?: ProgressReport_ExecuteArgs): ChainablePromise<GetProgressReportResDto>;
}

export interface Rankings_ExecuteService {
  rankings_Execute(args?: Rankings_ExecuteArgs): ChainablePromise<GetRankingsResDto>;
}

export interface RegisterSecureService {
  registerSecure(args?: RegisterSecureArgs): ChainablePromise<RegisterResult>;
}

export interface RejectBuddyInvite_ExecuteService {
  rejectBuddyInvite_Execute(args?: RejectBuddyInvite_ExecuteArgs): ChainablePromise<RejectBuddyInviteResDto>;
}

export interface RequestChallengeService {
  requestChallenge(args?: Record<string, unknown>): ChainablePromise<ChallengeResponse>;
}

export interface ReviewBackingPoints_ExecuteService {
  reviewBackingPoints_Execute(args?: ReviewBackingPoints_ExecuteArgs): ChainablePromise<ReviewBackingPointsResDto>;
}

export interface ReviewQueue_ExecuteService {
  reviewQueue_Execute(args?: ReviewQueue_ExecuteArgs): ChainablePromise<GetReviewQueueResDto>;
}

export interface RosterPreview_ExecuteService {
  rosterPreview_Execute(args?: RosterPreview_ExecuteArgs): ChainablePromise<RosterPreviewResDto>;
}

export interface SessionResult_ExecuteService {
  sessionResult_Execute(args?: SessionResult_ExecuteArgs): ChainablePromise<GetSessionResultResDto>;
}

export interface SetRankEnabled_ExecuteService {
  setRankEnabled_Execute(args?: SetRankEnabled_ExecuteArgs): ChainablePromise<SetRankEnabledResDto>;
}

export interface StartTrial_ExecuteService {
  startTrial_Execute(args?: StartTrial_ExecuteArgs): ChainablePromise<StartTrialResDto>;
}

export interface StatsWrongQuestions_ExecuteService {
  statsWrongQuestions_Execute(args?: StatsWrongQuestions_ExecuteArgs): ChainablePromise<StatsGetWrongQuestionsResDto>;
}

export interface Streak_ExecuteService {
  streak_Execute(args?: Record<string, unknown>): ChainablePromise<GetStreakResDto>;
}

export interface StudySession_ExecuteService {
  createStudySession_Execute(args?: CreateStudySession_ExecuteArgs): ChainablePromise<CreateStudySessionResDto>;
}

export interface SubmitAttempt_ExecuteService {
  submitAttempt_Execute(args?: SubmitAttempt_ExecuteArgs): ChainablePromise<SubmitAttemptResDto>;
}

export interface SubmitJudgmentFeedback_ExecuteService {
  submitJudgmentFeedback_Execute(args?: SubmitJudgmentFeedback_ExecuteArgs): ChainablePromise<SubmitJudgmentFeedbackResDto>;
}

export interface SubmitPkAnswer_ExecuteService {
  submitPkAnswer_Execute(args?: SubmitPkAnswer_ExecuteArgs): ChainablePromise<SubmitPkAnswerResDto>;
}

export interface Subscriptions_ExecuteService {
  listSubscriptions_Execute(args?: Record<string, unknown>): ChainablePromise<ListSubscriptionsResDto>;
}

export interface Task_ExecuteService {
  createTask_Execute(args?: CreateTask_ExecuteArgs): ChainablePromise<CreateTaskResDto>;
}

export interface TaskDetail_ExecuteService {
  taskDetail_Execute(args?: TaskDetail_ExecuteArgs): ChainablePromise<GetTaskDetailResDto>;
}

export interface Tasks_ExecuteService {
  listTasks_Execute(args?: ListTasks_ExecuteArgs): ChainablePromise<ListTasksResDto>;
}

export interface WeaknessReport_ExecuteService {
  weaknessReport_Execute(args?: WeaknessReport_ExecuteArgs): ChainablePromise<GetWeaknessReportResDto>;
}

export interface WrongQuestions_ExecuteService {
  wrongQuestions_Execute(args?: WrongQuestions_ExecuteArgs): ChainablePromise<GetWrongQuestionsResDto>;
}
