// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 3b437250d719c96ec3b0f65e13b6ae1a5a6a6d8fce827d340d854cd50be5b7d6]
// 模型: JudgmentFeedback (XiaoShuTong.Entities.Judging.JudgmentFeedback)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Entity;
using TKW.Framework.Domain.xCodeGen;
using XiaoShuTong.Entities.Judging;
using XiaoShuTong.Entities.Judging.DTOs;
using TKW.Framework.Domain.Interfaces;
using System.ComponentModel;

namespace XiaoShuTong.DataServices.Judging;

/// <summary>
/// </summary>
 sealed partial class JudgmentFeedbackDataService : IGeneratedByxCodeGenCli
{
    #region [ 内部原子逻辑转发 (Internal Accessors) ]

    /// <summary> 转发基类受保护的 QueryForUser，供同程序集 Controller 组合查询 Entity </summary>
    /// <remarks>优先使用 EntityGetAsync / EntitySelectAsync 等异步安全方法，仅在需要组合复杂查询时使用此属性。</remarks>
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    internal IQueryable<JudgmentFeedback> Query => QueryForUser();

    /// <summary> 转发基类受保护的 InternalGetAsync </summary>
    internal Task<JudgmentFeedback?> EntityGetAsync(Expression<Func<JudgmentFeedback, bool>> predicate, CancellationToken ct = default) 
        => InternalGetAsync(predicate, ct);

    /// <summary> 转发基类受保护的 InternalSelectAsync </summary>
    internal Task<List<JudgmentFeedback>> EntitySelectAsync(
        Expression<Func<JudgmentFeedback, bool>>? predicate, 
        int skip = 0, int limit = 100, 
        Func<IQueryable<JudgmentFeedback>, IQueryable<JudgmentFeedback>>? orderBy = null, 
        CancellationToken ct = default)
        => InternalSelectAsync(predicate, skip, limit, orderBy, ct);


    // --- 仅非视图(可写)实体拥有的转发方法 ---

    /// <summary> 转发基类受保护的 InternalCreateAsync </summary>
    internal Task<JudgmentFeedback> EntityCreateAsync(JudgmentFeedback entity, CancellationToken ct = default)
        => InternalCreateAsync(entity, ct);

    /// <summary> 转发基类受保护的 InternalCreateBatchAsync (批量插入) </summary>
    internal Task<List<JudgmentFeedback>> EntityCreateBatchAsync(IEnumerable<JudgmentFeedback> entities, CancellationToken ct = default)
        => InternalCreateBatchAsync(entities, ct);

    /// <summary> 转发基类受保护的 InternalUpdateAsync（返回更新后的实体） </summary>
    internal Task<JudgmentFeedback> EntityUpdateAsync(JudgmentFeedback entity, CancellationToken ct = default)
        => InternalUpdateAsync(entity, ct);

    /// <summary> 转发基类受保护的 InternalUpdateBatchAsync (全字段批量更新) </summary>
    internal Task EntityUpdateBatchAsync(IEnumerable<JudgmentFeedback> entities, CancellationToken ct = default)
        => InternalUpdateBatchAsync(entities, ct);

    /// <summary> 转发基类受保护的 InternalUpdateColumnsBatchAsync (指定列批量更新) </summary>
    internal Task<int> EntityUpdateColumnsBatchAsync<TColumns>(
        IEnumerable<JudgmentFeedback> entities, 
        Expression<Func<JudgmentFeedback, TColumns>> columns, 
        CancellationToken ct = default)
        => InternalUpdateColumnsBatchAsync(entities, columns, ct);

    /// <summary> 转发基类受保护的 InternalSoftDeleteAsync (软删除) </summary>
    internal Task<bool> EntitySoftDeleteAsync(long id, CancellationToken ct = default)
        => InternalSoftDeleteAsync(id, ct);

    /// <summary> 转发基类受保护的 InternalDeleteBatchAsync (批量删除) </summary>
    internal Task<int> EntityDeleteBatchAsync(IEnumerable<long> ids, CancellationToken ct = default)
        => InternalDeleteBatchAsync(ids, ct);
        
    #endregion
} // end service class