// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 31550ce606ee64557e745e6eee736371a932a72afb2d87d40a57566e9dd558c1]
// 模型: StudyBuddies (XiaoShuTong.Entities.Buddy.StudyBuddies)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Entity;
using TKW.Framework.Domain.xCodeGen;
using XiaoShuTong.Entities.Buddy;
using XiaoShuTong.Entities.Buddy.DTOs;
using TKW.Framework.Domain.Interfaces;
using System.ComponentModel;

namespace XiaoShuTong.DataServices.Buddy;

/// <summary>
/// </summary>
 sealed partial class StudyBuddiesDataService : IGeneratedByxCodeGenCli
{
    #region [ 内部原子逻辑转发 (Internal Accessors) ]

    /// <summary> 转发基类受保护的 QueryForUser，供同程序集 Controller 组合查询 Entity </summary>
    /// <remarks>优先使用 EntityGetAsync / EntitySelectAsync 等异步安全方法，仅在需要组合复杂查询时使用此属性。</remarks>
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    internal IQueryable<StudyBuddies> Query => QueryForUser();

    /// <summary> 转发基类受保护的 InternalGetAsync </summary>
    internal Task<StudyBuddies?> EntityGetAsync(Expression<Func<StudyBuddies, bool>> predicate, CancellationToken ct = default) 
        => InternalGetAsync(predicate, ct);

    /// <summary> 转发基类受保护的 InternalSelectAsync </summary>
    internal Task<List<StudyBuddies>> EntitySelectAsync(
        Expression<Func<StudyBuddies, bool>>? predicate, 
        int skip = 0, int limit = 100, 
        Func<IQueryable<StudyBuddies>, IQueryable<StudyBuddies>>? orderBy = null, 
        CancellationToken ct = default)
        => InternalSelectAsync(predicate, skip, limit, orderBy, ct);


    // --- 仅非视图(可写)实体拥有的转发方法 ---

    /// <summary> 转发基类受保护的 InternalCreateAsync </summary>
    internal Task<StudyBuddies> EntityCreateAsync(StudyBuddies entity, CancellationToken ct = default)
        => InternalCreateAsync(entity, ct);

    /// <summary> 转发基类受保护的 InternalCreateBatchAsync (批量插入) </summary>
    internal Task<List<StudyBuddies>> EntityCreateBatchAsync(IEnumerable<StudyBuddies> entities, CancellationToken ct = default)
        => InternalCreateBatchAsync(entities, ct);

    /// <summary> 转发基类受保护的 InternalUpdateAsync（返回更新后的实体） </summary>
    internal Task<StudyBuddies> EntityUpdateAsync(StudyBuddies entity, CancellationToken ct = default)
        => InternalUpdateAsync(entity, ct);

    /// <summary> 转发基类受保护的 InternalUpdateBatchAsync (全字段批量更新) </summary>
    internal Task EntityUpdateBatchAsync(IEnumerable<StudyBuddies> entities, CancellationToken ct = default)
        => InternalUpdateBatchAsync(entities, ct);

    /// <summary> 转发基类受保护的 InternalUpdateColumnsBatchAsync (指定列批量更新) </summary>
    internal Task<int> EntityUpdateColumnsBatchAsync<TColumns>(
        IEnumerable<StudyBuddies> entities, 
        Expression<Func<StudyBuddies, TColumns>> columns, 
        CancellationToken ct = default)
        => InternalUpdateColumnsBatchAsync(entities, columns, ct);

    /// <summary> 转发基类受保护的 InternalSoftDeleteAsync (软删除) </summary>
    internal Task<bool> EntitySoftDeleteAsync(long id, CancellationToken ct = default)
        => InternalSoftDeleteAsync(id, ct);

    /// <summary> 转发基类受保护的 InternalDeleteBatchAsync (批量删除) </summary>
    internal Task<int> EntityDeleteBatchAsync(IEnumerable<long> ids, CancellationToken ct = default)
        => InternalDeleteBatchAsync(ids, ct);
        
    #endregion
} // end service class