// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: ce109a42847ae42e9ca1ace1792e9fa22f63e5b4a78e2f578a2b6ef38b2d9434]
// 模型: PkMatches (XiaoShuTong.Entities.Pk.PkMatches)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using XiaoShuTong.Entities.Pk.DTOs;
using XiaoShuTong.Generated;

namespace XiaoShuTong.Entities.Pk;

public partial class PkMatches : IDomainEntity // SG 也声明此接口，冗余声明安全
{
    [NotMapped] // V4.9.54 BCL 标准属性（等价 FreeSql [Column(IsIgnore = true)]）
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; } = false;

    public void Validate(EnumSceneFlags scene = EnumSceneFlags.ForceValidate)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnBusinessValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene = EnumSceneFlags.None)
    {
        var results = new List<ValidationResult>();
        this.CreateModelValidator(scene, results)
                .MaxLength(nameof(UId), 32, d => d.UId)
                .MaxLength(nameof(BankId), 64, d => d.BankId)
                .MaxLength(nameof(Topic), 128, d => d.Topic)
                .MaxLength(nameof(InviteCode), 4, d => d.InviteCode)
        ;
        return results;
    }

    TDto IDomainEntity.ToDto<TDto>()
    {
        // 尝试将结果转换为请求的类型
        // 这通常意味着你需要一个转换器，或者简单地抛出异常如果不支持
        var dto = DTOs.PkMatchesDto.FromEntity(this);

        if (dto is TDto result)
            return result;

        throw new InvalidCastException($"无法将 {nameof(DTOs.PkMatchesDto)} 转换为请求的 {typeof(TDto)}");
    }

    public PkMatchesDto ToDto()
    {
        return PkMatchesDto.FromEntity(this);
    }

    /// <summary>
    /// V4.9: 控制是否允许通过 DomainUser.Query&lt;T&gt;() 直接查询此实体。
    /// 默认 true（允许）。设置为 false 后调用 DomainUser.Query&lt;T&gt;() 将抛出 InvalidOperationException。
    /// ⚠️ 此方法绕过 AOP 控制器，调用方必须自行验证身份和控制数据范围。
    /// </summary>
    public static bool AllowDirectQuery { get; set; } = true;

    /// <summary>条件工厂由 SourceGenerator 自动生成（EntityDomainInterfaceGenerator）</summary>

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Entity.cshtml";
    public const string GeneratorVersion = "4.9";

    partial void OnBusinessValidate(EnumSceneFlags scene, List<ValidationResult> results);
}
