// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 2e686dad89198088edce7a504d3f65f019e84296ef5ee3fd89616b6c9cf040ec]
// 模型: Questions (XiaoShuTong.Entities.Bank.Questions)
// 生成时间: 2026-09-08 05:56:56
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using XiaoShuTong.Entities.Bank.DTOs;
using XiaoShuTong.Generated;

namespace XiaoShuTong.Entities.Bank;

public partial class Questions : IDomainEntity // SG 也声明此接口，冗余声明安全
{
    [NotMapped] // V4.9.54 BCL 标准属性（等价 FreeSql [Column(IsIgnore = true)]）
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; } = false;

    public void Validate(EnumSceneFlags scene = EnumSceneFlags.ForceValidate)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnBusinessValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene = EnumSceneFlags.None)
    {
        var results = new List<ValidationResult>();
        this.CreateModelValidator(scene, results)
                .MaxLength(nameof(UId), 32, d => d.UId)
                .MaxLength(nameof(QuestionId), 64, d => d.QuestionId)
                .MaxLength(nameof(BankId), 64, d => d.BankId)
                .MaxLength(nameof(ChapterId), 32, d => d.ChapterId)
                .MaxLength(nameof(SupersededBy), 64, d => d.SupersededBy)
        ;
        return results;
    }

    TDto IDomainEntity.ToDto<TDto>()
    {
        // 尝试将结果转换为请求的类型
        // 这通常意味着你需要一个转换器，或者简单地抛出异常如果不支持
        var dto = DTOs.QuestionsDto.FromEntity(this);

        if (dto is TDto result)
            return result;

        throw new InvalidCastException($"无法将 {nameof(DTOs.QuestionsDto)} 转换为请求的 {typeof(TDto)}");
    }

    public QuestionsDto ToDto()
    {
        return QuestionsDto.FromEntity(this);
    }

    /// <summary>
    /// V4.9: 控制是否允许通过 DomainUser.Query&lt;T&gt;() 直接查询此实体。
    /// 默认 true（允许）。设置为 false 后调用 DomainUser.Query&lt;T&gt;() 将抛出 InvalidOperationException。
    /// ⚠️ 此方法绕过 AOP 控制器，调用方必须自行验证身份和控制数据范围。
    /// </summary>
    public static bool AllowDirectQuery { get; set; } = true;

    /// <summary>条件工厂由 SourceGenerator 自动生成（EntityDomainInterfaceGenerator）</summary>

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Entity.cshtml";
    public const string GeneratorVersion = "4.9";

    partial void OnBusinessValidate(EnumSceneFlags scene, List<ValidationResult> results);
}
