// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 9007afb7d6b99b92f0ecda3eeb4f10aed04935cb888e01d2bd5c30c2211d9058]
// 模型: AiModelConfig (XiaoShuTong.Entities.Platform.AiModelConfig)
// 生成时间: 2026-09-11 05:03:24
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using XiaoShuTong;
using XiaoShuTong.Entities.Platform;

namespace XiaoShuTong.Entities.Platform.DTOs;
/// <summary>AI 模型配置（统一 AI 网关路由表）</summary>
public partial record AiModelConfigDto : IDomainDto<AiModelConfig>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 自增主键 </summary>
    public long Id { get; init; }
    /// <summary> 外部业务键（uuid，API/DTO 暴露） </summary>
    public required string UId { get; init; }
    /// <summary> 配置名（≤64） </summary>
    public required string Name { get; init; }
    /// <summary> 供应商（OpenAiCompatible） </summary>
    public required AiProvider Provider { get; init; }
    /// <summary> 在线 API BaseUrl（如 https://api.openai.com/v1） </summary>
    public required string BaseUrl { get; init; }
    /// <summary> 模型名（如 gpt-4o-mini） </summary>
    public required string ModelName { get; init; }
    /// <summary> 是否启用（默认 true） </summary>
    public bool Enabled { get; init; }
    /// <summary> 轮询顺序（升序优先，默认 0） </summary>
    public int SortOrder { get; init; }
    /// <summary> 请求超时秒数（默认 30） </summary>
    public int TimeoutSeconds { get; init; }
    /// <summary> 备注（可空） </summary>
    public string? Remark { get; init; }
    /// <summary> 创建时间 </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 更新时间 </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static AiModelConfigDto FromEntity(AiModelConfig entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new AiModelConfigDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UId = entity.UId,
            Name = entity.Name,
            Provider = entity.Provider,
            BaseUrl = entity.BaseUrl,
            ModelName = entity.ModelName,
            Enabled = entity.Enabled,
            SortOrder = entity.SortOrder,
            TimeoutSeconds = entity.TimeoutSeconds,
            Remark = entity.Remark,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<AiModelConfig, AiModelConfigDto>> SelectExpression => e => new AiModelConfigDto
    {
        Id = e.Id,
        UId = e.UId,
        Name = e.Name,
        Provider = e.Provider,
        BaseUrl = e.BaseUrl,
        ModelName = e.ModelName,
        Enabled = e.Enabled,
        SortOrder = e.SortOrder,
        TimeoutSeconds = e.TimeoutSeconds,
        Remark = e.Remark,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    AiModelConfig IDomainDto<AiModelConfig>.ApplyToEntity(AiModelConfig entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UId), d => d.UId, (e, v) => e.UId = v )
            .Map(nameof(Name), d => d.Name, (e, v) => e.Name = v )
            .Map(nameof(Provider), d => d.Provider, (e, v) => e.Provider = v )
            .Map(nameof(BaseUrl), d => d.BaseUrl, (e, v) => e.BaseUrl = v )
            .Map(nameof(ModelName), d => d.ModelName, (e, v) => e.ModelName = v )
            .Map(nameof(Enabled), d => d.Enabled, (e, v) => e.Enabled = v )
            .Map(nameof(SortOrder), d => d.SortOrder, (e, v) => e.SortOrder = v )
            .Map(nameof(TimeoutSeconds), d => d.TimeoutSeconds, (e, v) => e.TimeoutSeconds = v )
            .Map(nameof(Remark), d => d.Remark, (e, v) => e.Remark = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    AiModelConfig IDomainDto<AiModelConfig>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(AiModelConfigDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<AiModelConfig>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<AiModelConfig, AiModelConfigDto>(scene, results)
                .MaxLength(nameof(UId), 32, d => d.UId)
                .MaxLength(nameof(Name), 64, d => d.Name)
                .MaxLength(nameof(BaseUrl), 256, d => d.BaseUrl)
                .MaxLength(nameof(ModelName), 64, d => d.ModelName)
                .MaxLength(nameof(Remark), 256, d => d.Remark)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class AiModelConfigDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static AiModelConfigDto ToDto(this AiModelConfig entity) => AiModelConfigDto.FromEntity(entity);
}

