// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: d09d14915fac2c5968537c62359e7f6ed12a7c444359daebeccd9afddd4844d0]
// 模型: Attempts (XiaoShuTong.Entities.Learning.Attempts)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using XiaoShuTong;
using XiaoShuTong.Entities.Learning;

namespace XiaoShuTong.Entities.Learning.DTOs;
/// <summary>作答记录（唯一事实源）</summary>
public partial record AttemptsDto : IDomainDto<Attempts>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 自增主键 </summary>
    public long Id { get; init; }
    /// <summary> 外部业务键 </summary>
    public required string UId { get; init; }
    /// <summary> 学生用户 </summary>
    public long UserId { get; init; }
    /// <summary> 学习会话归属 </summary>
    public long? SessionId { get; init; }
    /// <summary> 题目业务键（Q-ch-7a-0001） </summary>
    public required string QuestionId { get; init; }
    /// <summary> 题库业务键 </summary>
    public required string BankId { get; init; }
    /// <summary> 场景（LearningScenario，由会话派生） </summary>
    public required LearningScenario Scenario { get; init; }
    /// <summary> 题型键（R1/R2/R3a/R3b/O1...） </summary>
    public required string QType { get; init; }
    /// <summary> 作答前记忆状态（MemoryState） </summary>
    public required MemoryState PreState { get; init; }
    /// <summary> 作答后记忆状态（MemoryState） </summary>
    public required MemoryState PostState { get; init; }
    /// <summary> 判题结果（Correct/Partial/Wrong） </summary>
    public required JudgmentResult Result { get; init; }
    /// <summary> 判题置信度（0-1） </summary>
    public double? Confidence { get; init; }
    /// <summary> 求助档位（None/Partial/Full） </summary>
    public required HintLevel HintLevel { get; init; }
    /// <summary> 作答耗时（服务端计时，毫秒） </summary>
    public int? TimeCostMs { get; init; }
    /// <summary> 作答时间 </summary>
    public DateTime AnsweredAt { get; init; }
    /// <summary> 创建时间（框架审计字段） </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 更新时间（框架审计字段） </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static AttemptsDto FromEntity(Attempts entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new AttemptsDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UId = entity.UId,
            UserId = entity.UserId,
            SessionId = entity.SessionId,
            QuestionId = entity.QuestionId,
            BankId = entity.BankId,
            Scenario = entity.Scenario,
            QType = entity.QType,
            PreState = entity.PreState,
            PostState = entity.PostState,
            Result = entity.Result,
            Confidence = entity.Confidence,
            HintLevel = entity.HintLevel,
            TimeCostMs = entity.TimeCostMs,
            AnsweredAt = entity.AnsweredAt,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<Attempts, AttemptsDto>> SelectExpression => e => new AttemptsDto
    {
        Id = e.Id,
        UId = e.UId,
        UserId = e.UserId,
        SessionId = e.SessionId,
        QuestionId = e.QuestionId,
        BankId = e.BankId,
        Scenario = e.Scenario,
        QType = e.QType,
        PreState = e.PreState,
        PostState = e.PostState,
        Result = e.Result,
        Confidence = e.Confidence,
        HintLevel = e.HintLevel,
        TimeCostMs = e.TimeCostMs,
        AnsweredAt = e.AnsweredAt,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    Attempts IDomainDto<Attempts>.ApplyToEntity(Attempts entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UId), d => d.UId, (e, v) => e.UId = v )
            .Map(nameof(UserId), d => d.UserId, (e, v) => e.UserId = v )
            .Map(nameof(SessionId), d => d.SessionId, (e, v) => e.SessionId = v )
            .Map(nameof(QuestionId), d => d.QuestionId, (e, v) => e.QuestionId = v )
            .Map(nameof(BankId), d => d.BankId, (e, v) => e.BankId = v )
            .Map(nameof(Scenario), d => d.Scenario, (e, v) => e.Scenario = v )
            .Map(nameof(QType), d => d.QType, (e, v) => e.QType = v )
            .Map(nameof(PreState), d => d.PreState, (e, v) => e.PreState = v )
            .Map(nameof(PostState), d => d.PostState, (e, v) => e.PostState = v )
            .Map(nameof(Result), d => d.Result, (e, v) => e.Result = v )
            .Map(nameof(Confidence), d => d.Confidence, (e, v) => e.Confidence = v )
            .Map(nameof(HintLevel), d => d.HintLevel, (e, v) => e.HintLevel = v )
            .Map(nameof(TimeCostMs), d => d.TimeCostMs, (e, v) => e.TimeCostMs = v )
            .Map(nameof(AnsweredAt), d => d.AnsweredAt, (e, v) => e.AnsweredAt = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    Attempts IDomainDto<Attempts>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(AttemptsDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<Attempts>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<Attempts, AttemptsDto>(scene, results)
                .MaxLength(nameof(UId), 32, d => d.UId)
                .MaxLength(nameof(QuestionId), 64, d => d.QuestionId)
                .MaxLength(nameof(BankId), 64, d => d.BankId)
                .MaxLength(nameof(QType), 20, d => d.QType)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class AttemptsDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static AttemptsDto ToDto(this Attempts entity) => AttemptsDto.FromEntity(entity);
}

