// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 3772b2943de91caf166f6ed380fa60ae9cb714be29511de431a4cac9475ff166]
// 模型: Banks (XiaoShuTong.Entities.Bank.Banks)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using XiaoShuTong;
using XiaoShuTong.Entities.Bank;

namespace XiaoShuTong.Entities.Bank.DTOs;
/// <summary>题库元数据（API 查询索引）</summary>
public partial record BanksDto : IDomainDto<Banks>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 自增主键 </summary>
    public long Id { get; init; }
    /// <summary> 外部业务键（uuid，API/DTO 暴露） </summary>
    public required string UId { get; init; }
    /// <summary> 业务键（chinese-7to9-pep） </summary>
    public required string BankId { get; init; }
    /// <summary> 题库名（≤128） </summary>
    public required string Name { get; init; }
    /// <summary> 学科 </summary>
    public required Subject Subject { get; init; }
    /// <summary> 内容版本（MinVer） </summary>
    public required string Version { get; init; }
    /// <summary> 用途（Memorize/Assess/Play） </summary>
    public required BankPurpose Purpose { get; init; }
    /// <summary> 隐私（Private/Public/Group） </summary>
    public required BankPrivacy Privacy { get; init; }
    /// <summary> 私域题库 owner（官方题库 NULL） </summary>
    public long? OwnerId { get; init; }
    /// <summary> bank.v1.json 文件路径（内容权威） </summary>
    public required string JsonPath { get; init; }
    /// <summary> 标签（JSONB，如 ["高频考点"]） </summary>
    public required string[] Tags { get; init; }
    /// <summary> 状态（Active/Hidden/Archived） </summary>
    public required BankStatus Status { get; init; }
    /// <summary> 创建时间 </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 更新时间 </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static BanksDto FromEntity(Banks entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new BanksDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UId = entity.UId,
            BankId = entity.BankId,
            Name = entity.Name,
            Subject = entity.Subject,
            Version = entity.Version,
            Purpose = entity.Purpose,
            Privacy = entity.Privacy,
            OwnerId = entity.OwnerId,
            JsonPath = entity.JsonPath,
            Tags = entity.Tags,
            Status = entity.Status,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<Banks, BanksDto>> SelectExpression => e => new BanksDto
    {
        Id = e.Id,
        UId = e.UId,
        BankId = e.BankId,
        Name = e.Name,
        Subject = e.Subject,
        Version = e.Version,
        Purpose = e.Purpose,
        Privacy = e.Privacy,
        OwnerId = e.OwnerId,
        JsonPath = e.JsonPath,
        Tags = e.Tags,
        Status = e.Status,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    Banks IDomainDto<Banks>.ApplyToEntity(Banks entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UId), d => d.UId, (e, v) => e.UId = v )
            .Map(nameof(BankId), d => d.BankId, (e, v) => e.BankId = v )
            .Map(nameof(Name), d => d.Name, (e, v) => e.Name = v )
            .Map(nameof(Subject), d => d.Subject, (e, v) => e.Subject = v )
            .Map(nameof(Version), d => d.Version, (e, v) => e.Version = v )
            .Map(nameof(Purpose), d => d.Purpose, (e, v) => e.Purpose = v )
            .Map(nameof(Privacy), d => d.Privacy, (e, v) => e.Privacy = v )
            .Map(nameof(OwnerId), d => d.OwnerId, (e, v) => e.OwnerId = v )
            .Map(nameof(JsonPath), d => d.JsonPath, (e, v) => e.JsonPath = v )
            .Map(nameof(Tags), d => d.Tags, (e, v) => e.Tags = v )
            .Map(nameof(Status), d => d.Status, (e, v) => e.Status = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    Banks IDomainDto<Banks>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(BanksDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<Banks>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<Banks, BanksDto>(scene, results)
                .MaxLength(nameof(UId), 32, d => d.UId)
                .MaxLength(nameof(BankId), 64, d => d.BankId)
                .MaxLength(nameof(Name), 128, d => d.Name)
                .MaxLength(nameof(Version), 20, d => d.Version)
                .MaxLength(nameof(JsonPath), 256, d => d.JsonPath)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class BanksDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static BanksDto ToDto(this Banks entity) => BanksDto.FromEntity(entity);
}

