// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 1f7c3cb262286a08c13f7d6d1de20532e3a18986ca6f12311e5c24f19278041f]
// 模型: BetaInviteCodes (XiaoShuTong.Entities.GroupManagement.BetaInviteCodes)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using XiaoShuTong;
using XiaoShuTong.Entities.GroupManagement;

namespace XiaoShuTong.Entities.GroupManagement.DTOs;
/// <summary>内测邀请码（平台发放给群主）</summary>
public partial record BetaInviteCodesDto : IDomainDto<BetaInviteCodes>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键 </summary>
    public long Id { get; init; }
    /// <summary> 外部业务键（uuid，API/DTO 暴露） </summary>
    public required string UId { get; init; }
    /// <summary> 内测邀请码（平台生成，16 位） </summary>
    public required string Code { get; init; }
    /// <summary> 状态（Pending/Used/Expired） </summary>
    public required BetaCodeStatus Status { get; init; }
    /// <summary> 发放对象（群主，可 NULL=未指定） </summary>
    public long? IssuedToUserId { get; init; }
    /// <summary> 发放时间 </summary>
    public DateTime? IssuedAt { get; init; }
    /// <summary> 内测期码有效期 </summary>
    public DateTime ExpiresAt { get; init; }
    /// <summary> 群主激活建群时间 </summary>
    public DateTime? UsedAt { get; init; }
    /// <summary> 激活的群组 </summary>
    public long? UsedByGroupId { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static BetaInviteCodesDto FromEntity(BetaInviteCodes entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new BetaInviteCodesDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UId = entity.UId,
            Code = entity.Code,
            Status = entity.Status,
            IssuedToUserId = entity.IssuedToUserId,
            IssuedAt = entity.IssuedAt,
            ExpiresAt = entity.ExpiresAt,
            UsedAt = entity.UsedAt,
            UsedByGroupId = entity.UsedByGroupId,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<BetaInviteCodes, BetaInviteCodesDto>> SelectExpression => e => new BetaInviteCodesDto
    {
        Id = e.Id,
        UId = e.UId,
        Code = e.Code,
        Status = e.Status,
        IssuedToUserId = e.IssuedToUserId,
        IssuedAt = e.IssuedAt,
        ExpiresAt = e.ExpiresAt,
        UsedAt = e.UsedAt,
        UsedByGroupId = e.UsedByGroupId,
    };
    #endregion

    BetaInviteCodes IDomainDto<BetaInviteCodes>.ApplyToEntity(BetaInviteCodes entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UId), d => d.UId, (e, v) => e.UId = v )
            .Map(nameof(Code), d => d.Code, (e, v) => e.Code = v )
            .Map(nameof(Status), d => d.Status, (e, v) => e.Status = v )
            .Map(nameof(IssuedToUserId), d => d.IssuedToUserId, (e, v) => e.IssuedToUserId = v )
            .Map(nameof(IssuedAt), d => d.IssuedAt, (e, v) => e.IssuedAt = v )
            .Map(nameof(ExpiresAt), d => d.ExpiresAt, (e, v) => e.ExpiresAt = v )
            .Map(nameof(UsedAt), d => d.UsedAt, (e, v) => e.UsedAt = v )
            .Map(nameof(UsedByGroupId), d => d.UsedByGroupId, (e, v) => e.UsedByGroupId = v )
        ;
        return entity;
    }

    BetaInviteCodes IDomainDto<BetaInviteCodes>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(BetaInviteCodesDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<BetaInviteCodes>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<BetaInviteCodes, BetaInviteCodesDto>(scene, results)
                .MaxLength(nameof(UId), 32, d => d.UId)
                .MaxLength(nameof(Code), 16, d => d.Code)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class BetaInviteCodesDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static BetaInviteCodesDto ToDto(this BetaInviteCodes entity) => BetaInviteCodesDto.FromEntity(entity);
}

