// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 8b093e13707735ea9b732575f49f91fef77ae45f7bba6432012e71283e41d95b]
// 模型: DailyStats (XiaoShuTong.Entities.Learning.DailyStats)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using XiaoShuTong.Entities.Learning;

namespace XiaoShuTong.Entities.Learning.DTOs;
/// <summary>条件工厂（V4.9）。支持两种使用方式：     <list type="bullet">     <item><c>DailyStats.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>     <item><c>DailyStats.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>     </list></summary>
public partial record DailyStatsDto : IDomainDto<DailyStats>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 自增主键 </summary>
    public long Id { get; init; }
    /// <summary> 外部业务键 </summary>
    public required string UId { get; init; }
    /// <summary> 学生用户 </summary>
    public long UserId { get; init; }
    /// <summary> UTC+8 业务日期 </summary>
    public DateOnly StatDate { get; init; }
    /// <summary> 学习题数 </summary>
    public int LearnedCount { get; init; }
    /// <summary> 点亮★数（热力图） </summary>
    public int StarredCount { get; init; }
    /// <summary> 复习题数 </summary>
    public int ReviewCount { get; init; }
    /// <summary> 当日正确率 </summary>
    public double? Accuracy { get; init; }
    /// <summary> 学习时长（秒） </summary>
    public int StudySeconds { get; init; }
    /// <summary> 创建时间（框架审计字段） </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 更新时间（框架审计字段） </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static DailyStatsDto FromEntity(DailyStats entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new DailyStatsDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UId = entity.UId,
            UserId = entity.UserId,
            StatDate = entity.StatDate,
            LearnedCount = entity.LearnedCount,
            StarredCount = entity.StarredCount,
            ReviewCount = entity.ReviewCount,
            Accuracy = entity.Accuracy,
            StudySeconds = entity.StudySeconds,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<DailyStats, DailyStatsDto>> SelectExpression => e => new DailyStatsDto
    {
        Id = e.Id,
        UId = e.UId,
        UserId = e.UserId,
        StatDate = e.StatDate,
        LearnedCount = e.LearnedCount,
        StarredCount = e.StarredCount,
        ReviewCount = e.ReviewCount,
        Accuracy = e.Accuracy,
        StudySeconds = e.StudySeconds,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    DailyStats IDomainDto<DailyStats>.ApplyToEntity(DailyStats entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UId), d => d.UId, (e, v) => e.UId = v )
            .Map(nameof(UserId), d => d.UserId, (e, v) => e.UserId = v )
            .Map(nameof(StatDate), d => d.StatDate, (e, v) => e.StatDate = v )
            .Map(nameof(LearnedCount), d => d.LearnedCount, (e, v) => e.LearnedCount = v )
            .Map(nameof(StarredCount), d => d.StarredCount, (e, v) => e.StarredCount = v )
            .Map(nameof(ReviewCount), d => d.ReviewCount, (e, v) => e.ReviewCount = v )
            .Map(nameof(Accuracy), d => d.Accuracy, (e, v) => e.Accuracy = v )
            .Map(nameof(StudySeconds), d => d.StudySeconds, (e, v) => e.StudySeconds = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    DailyStats IDomainDto<DailyStats>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(DailyStatsDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<DailyStats>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<DailyStats, DailyStatsDto>(scene, results)
                .MaxLength(nameof(UId), 32, d => d.UId)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class DailyStatsDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static DailyStatsDto ToDto(this DailyStats entity) => DailyStatsDto.FromEntity(entity);
}

