// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 1dc1dc901d889778e085e0dd9e048d1f110dee415b7b6812c60ad87acf48cab2]
// 模型: GroupMembers (XiaoShuTong.Entities.GroupManagement.GroupMembers)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using XiaoShuTong;
using XiaoShuTong.Entities.GroupManagement;

namespace XiaoShuTong.Entities.GroupManagement.DTOs;
/// <summary>条件工厂（V4.9）。支持两种使用方式：     <list type="bullet">     <item><c>GroupMembers.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>     <item><c>GroupMembers.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>     </list></summary>
public partial record GroupMembersDto : IDomainDto<GroupMembers>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键 </summary>
    public long Id { get; init; }
    /// <summary> 外部业务键（uuid，API/DTO 暴露） </summary>
    public required string UId { get; init; }
    /// <summary> 所属群组 </summary>
    public long GroupId { get; init; }
    /// <summary> 成员用户 </summary>
    public long UserId { get; init; }
    /// <summary> 成员角色（Student/Parent） </summary>
    public required MemberRole Role { get; init; }
    /// <summary> 群内昵称（学生号/姓名） </summary>
    public string? Nickname { get; init; }
    /// <summary> 加入所用一次性邀请码（溯源） </summary>
    public long? InviteCodeId { get; init; }
    /// <summary> 加入时间 </summary>
    public DateTime JoinedAt { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static GroupMembersDto FromEntity(GroupMembers entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new GroupMembersDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UId = entity.UId,
            GroupId = entity.GroupId,
            UserId = entity.UserId,
            Role = entity.Role,
            Nickname = entity.Nickname,
            InviteCodeId = entity.InviteCodeId,
            JoinedAt = entity.JoinedAt,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<GroupMembers, GroupMembersDto>> SelectExpression => e => new GroupMembersDto
    {
        Id = e.Id,
        UId = e.UId,
        GroupId = e.GroupId,
        UserId = e.UserId,
        Role = e.Role,
        Nickname = e.Nickname,
        InviteCodeId = e.InviteCodeId,
        JoinedAt = e.JoinedAt,
    };
    #endregion

    GroupMembers IDomainDto<GroupMembers>.ApplyToEntity(GroupMembers entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UId), d => d.UId, (e, v) => e.UId = v )
            .Map(nameof(GroupId), d => d.GroupId, (e, v) => e.GroupId = v )
            .Map(nameof(UserId), d => d.UserId, (e, v) => e.UserId = v )
            .Map(nameof(Role), d => d.Role, (e, v) => e.Role = v )
            .Map(nameof(Nickname), d => d.Nickname, (e, v) => e.Nickname = v )
            .Map(nameof(InviteCodeId), d => d.InviteCodeId, (e, v) => e.InviteCodeId = v )
        ;
        return entity;
    }

    GroupMembers IDomainDto<GroupMembers>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(GroupMembersDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<GroupMembers>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<GroupMembers, GroupMembersDto>(scene, results)
                .MaxLength(nameof(UId), 32, d => d.UId)
                .MaxLength(nameof(Nickname), 64, d => d.Nickname)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class GroupMembersDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static GroupMembersDto ToDto(this GroupMembers entity) => GroupMembersDto.FromEntity(entity);
}

