// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 1609a4fa5d1641802d4a92882f6f08cdbd7fcf6e14be674a1c9895f9425e449d]
// 模型: Groups (XiaoShuTong.Entities.GroupManagement.Groups)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using XiaoShuTong;
using XiaoShuTong.Entities.GroupManagement;

namespace XiaoShuTong.Entities.GroupManagement.DTOs;
/// <summary>条件工厂（V4.9）。支持两种使用方式：     <list type="bullet">     <item><c>Groups.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>     <item><c>Groups.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>     </list></summary>
public partial record GroupsDto : IDomainDto<Groups>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键 </summary>
    public long Id { get; init; }
    /// <summary> 外部业务键（uuid，API/DTO 暴露） </summary>
    public required string UId { get; init; }
    /// <summary> 群主（原老师/班主任） </summary>
    public long OwnerId { get; init; }
    /// <summary> 群组名称（≤64，如"七(3)班"） </summary>
    public required string Name { get; init; }
    /// <summary> 学科（history/geography/biology/daodeyufazhi） </summary>
    public required string Subject { get; init; }
    /// <summary> 年级（七年级/八年级/九年级） </summary>
    public string? Grade { get; init; }
    /// <summary> 状态（Active/Archived） </summary>
    public required GroupStatus Status { get; init; }
    /// <summary> 群组战绩榜开关（false → 战绩榜入口隐藏） </summary>
    public bool RankEnabled { get; init; }
    /// <summary> 激活本群所用的内测邀请码 </summary>
    public long? BetaCodeId { get; init; }
    /// <summary> 创建时间 </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 更新时间 </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static GroupsDto FromEntity(Groups entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new GroupsDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UId = entity.UId,
            OwnerId = entity.OwnerId,
            Name = entity.Name,
            Subject = entity.Subject,
            Grade = entity.Grade,
            Status = entity.Status,
            RankEnabled = entity.RankEnabled,
            BetaCodeId = entity.BetaCodeId,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<Groups, GroupsDto>> SelectExpression => e => new GroupsDto
    {
        Id = e.Id,
        UId = e.UId,
        OwnerId = e.OwnerId,
        Name = e.Name,
        Subject = e.Subject,
        Grade = e.Grade,
        Status = e.Status,
        RankEnabled = e.RankEnabled,
        BetaCodeId = e.BetaCodeId,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    Groups IDomainDto<Groups>.ApplyToEntity(Groups entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UId), d => d.UId, (e, v) => e.UId = v )
            .Map(nameof(OwnerId), d => d.OwnerId, (e, v) => e.OwnerId = v )
            .Map(nameof(Name), d => d.Name, (e, v) => e.Name = v )
            .Map(nameof(Subject), d => d.Subject, (e, v) => e.Subject = v )
            .Map(nameof(Grade), d => d.Grade, (e, v) => e.Grade = v )
            .Map(nameof(Status), d => d.Status, (e, v) => e.Status = v )
            .Map(nameof(RankEnabled), d => d.RankEnabled, (e, v) => e.RankEnabled = v )
            .Map(nameof(BetaCodeId), d => d.BetaCodeId, (e, v) => e.BetaCodeId = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    Groups IDomainDto<Groups>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(GroupsDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<Groups>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<Groups, GroupsDto>(scene, results)
                .MaxLength(nameof(UId), 32, d => d.UId)
                .MaxLength(nameof(Name), 64, d => d.Name)
                .MaxLength(nameof(Subject), 32, d => d.Subject)
                .MaxLength(nameof(Grade), 16, d => d.Grade)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class GroupsDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static GroupsDto ToDto(this Groups entity) => GroupsDto.FromEntity(entity);
}

