// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: cf196b4afa397fbe3b3e5d542a6d10211ca8015f4580ea0206f6b5d34fb4872d]
// 模型: JudgmentFeedback (XiaoShuTong.Entities.Judging.JudgmentFeedback)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using XiaoShuTong;
using XiaoShuTong.Entities.Judging;

namespace XiaoShuTong.Entities.Judging.DTOs;
/// <summary>条件工厂（V4.9）。支持两种使用方式：     <list type="bullet">     <item><c>JudgmentFeedback.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>     <item><c>JudgmentFeedback.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>     </list></summary>
public partial record JudgmentFeedbackDto : IDomainDto<JudgmentFeedback>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 自增主键 </summary>
    public long Id { get; init; }
    /// <summary> 外部业务键 </summary>
    public required string UId { get; init; }
    /// <summary> 关联作答记录（跨模块，学习域） </summary>
    public long AttemptId { get; init; }
    /// <summary> 反馈用户 </summary>
    public long UserId { get; init; }
    /// <summary> 反馈类型（WrongJudgment/Other） </summary>
    public required FeedbackType FeedbackType { get; init; }
    /// <summary> 复核状态（Pending/Reviewed/Resolved） </summary>
    public required FeedbackStatus Status { get; init; }
    /// <summary> 复核人（人工队列） </summary>
    public string? ReviewedBy { get; init; }
    /// <summary> 复核时间 </summary>
    public DateTime? ReviewedAt { get; init; }
    /// <summary> 创建时间 </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 更新时间 </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static JudgmentFeedbackDto FromEntity(JudgmentFeedback entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new JudgmentFeedbackDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UId = entity.UId,
            AttemptId = entity.AttemptId,
            UserId = entity.UserId,
            FeedbackType = entity.FeedbackType,
            Status = entity.Status,
            ReviewedBy = entity.ReviewedBy,
            ReviewedAt = entity.ReviewedAt,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<JudgmentFeedback, JudgmentFeedbackDto>> SelectExpression => e => new JudgmentFeedbackDto
    {
        Id = e.Id,
        UId = e.UId,
        AttemptId = e.AttemptId,
        UserId = e.UserId,
        FeedbackType = e.FeedbackType,
        Status = e.Status,
        ReviewedBy = e.ReviewedBy,
        ReviewedAt = e.ReviewedAt,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    JudgmentFeedback IDomainDto<JudgmentFeedback>.ApplyToEntity(JudgmentFeedback entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UId), d => d.UId, (e, v) => e.UId = v )
            .Map(nameof(AttemptId), d => d.AttemptId, (e, v) => e.AttemptId = v )
            .Map(nameof(UserId), d => d.UserId, (e, v) => e.UserId = v )
            .Map(nameof(FeedbackType), d => d.FeedbackType, (e, v) => e.FeedbackType = v )
            .Map(nameof(Status), d => d.Status, (e, v) => e.Status = v )
            .Map(nameof(ReviewedBy), d => d.ReviewedBy, (e, v) => e.ReviewedBy = v )
            .Map(nameof(ReviewedAt), d => d.ReviewedAt, (e, v) => e.ReviewedAt = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    JudgmentFeedback IDomainDto<JudgmentFeedback>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(JudgmentFeedbackDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<JudgmentFeedback>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<JudgmentFeedback, JudgmentFeedbackDto>(scene, results)
                .MaxLength(nameof(UId), 32, d => d.UId)
                .MaxLength(nameof(ReviewedBy), 64, d => d.ReviewedBy)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class JudgmentFeedbackDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static JudgmentFeedbackDto ToDto(this JudgmentFeedback entity) => JudgmentFeedbackDto.FromEntity(entity);
}

