// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 28a89cc3e5660f891f71295cd2960da1f579863f8b5e20c85423138d5afa1cbd]
// 模型: KnowledgeMastery (XiaoShuTong.Entities.Learning.KnowledgeMastery)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using XiaoShuTong;
using XiaoShuTong.Entities.Learning;

namespace XiaoShuTong.Entities.Learning.DTOs;
/// <summary>条件工厂（V4.9）。支持两种使用方式：     <list type="bullet">     <item><c>KnowledgeMastery.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>     <item><c>KnowledgeMastery.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>     </list></summary>
public partial record KnowledgeMasteryDto : IDomainDto<KnowledgeMastery>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 自增主键 </summary>
    public long Id { get; init; }
    /// <summary> 外部业务键 </summary>
    public required string UId { get; init; }
    /// <summary> 学生用户 </summary>
    public long UserId { get; init; }
    /// <summary> 学科 </summary>
    public required string Subject { get; init; }
    /// <summary> 知识点 </summary>
    public required string KnowledgePoint { get; init; }
    /// <summary> 聚合状态（取题目中位/最差，MemoryState） </summary>
    public required MemoryState State { get; init; }
    /// <summary> 聚合正确率 </summary>
    public double Accuracy { get; init; }
    /// <summary> 作答次数 </summary>
    public int AttemptCount { get; init; }
    /// <summary> 最近复习时间 </summary>
    public DateTime? LastReviewedAt { get; init; }
    /// <summary> 创建时间（框架审计字段） </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 更新时间（框架审计字段） </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static KnowledgeMasteryDto FromEntity(KnowledgeMastery entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new KnowledgeMasteryDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UId = entity.UId,
            UserId = entity.UserId,
            Subject = entity.Subject,
            KnowledgePoint = entity.KnowledgePoint,
            State = entity.State,
            Accuracy = entity.Accuracy,
            AttemptCount = entity.AttemptCount,
            LastReviewedAt = entity.LastReviewedAt,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<KnowledgeMastery, KnowledgeMasteryDto>> SelectExpression => e => new KnowledgeMasteryDto
    {
        Id = e.Id,
        UId = e.UId,
        UserId = e.UserId,
        Subject = e.Subject,
        KnowledgePoint = e.KnowledgePoint,
        State = e.State,
        Accuracy = e.Accuracy,
        AttemptCount = e.AttemptCount,
        LastReviewedAt = e.LastReviewedAt,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    KnowledgeMastery IDomainDto<KnowledgeMastery>.ApplyToEntity(KnowledgeMastery entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UId), d => d.UId, (e, v) => e.UId = v )
            .Map(nameof(UserId), d => d.UserId, (e, v) => e.UserId = v )
            .Map(nameof(Subject), d => d.Subject, (e, v) => e.Subject = v )
            .Map(nameof(KnowledgePoint), d => d.KnowledgePoint, (e, v) => e.KnowledgePoint = v )
            .Map(nameof(State), d => d.State, (e, v) => e.State = v )
            .Map(nameof(Accuracy), d => d.Accuracy, (e, v) => e.Accuracy = v )
            .Map(nameof(AttemptCount), d => d.AttemptCount, (e, v) => e.AttemptCount = v )
            .Map(nameof(LastReviewedAt), d => d.LastReviewedAt, (e, v) => e.LastReviewedAt = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    KnowledgeMastery IDomainDto<KnowledgeMastery>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(KnowledgeMasteryDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<KnowledgeMastery>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<KnowledgeMastery, KnowledgeMasteryDto>(scene, results)
                .MaxLength(nameof(UId), 32, d => d.UId)
                .MaxLength(nameof(Subject), 32, d => d.Subject)
                .MaxLength(nameof(KnowledgePoint), 128, d => d.KnowledgePoint)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class KnowledgeMasteryDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static KnowledgeMasteryDto ToDto(this KnowledgeMastery entity) => KnowledgeMasteryDto.FromEntity(entity);
}

