// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 3b80ad56cf63367e656dd867a0a80e89bbf0ff511f59b05f3f9acae00885246c]
// 模型: MemoryStates (XiaoShuTong.Entities.Learning.MemoryStates)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using XiaoShuTong;
using XiaoShuTong.Entities.Learning;

namespace XiaoShuTong.Entities.Learning.DTOs;
/// <summary>条件工厂（V4.9）。支持两种使用方式：     <list type="bullet">     <item><c>MemoryStates.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>     <item><c>MemoryStates.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>     </list></summary>
public partial record MemoryStatesDto : IDomainDto<MemoryStates>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 自增主键 </summary>
    public long Id { get; init; }
    /// <summary> 外部业务键 </summary>
    public required string UId { get; init; }
    /// <summary> 学生用户 </summary>
    public long UserId { get; init; }
    /// <summary> 题目业务键 </summary>
    public required string QuestionId { get; init; }
    /// <summary> 题库业务键 </summary>
    public required string BankId { get; init; }
    /// <summary> 记忆状态（NotMastered/Fuzzy/Mastered/Proficient） </summary>
    public required MemoryState State { get; init; }
    /// <summary> 连续独立答对（2 次→★） </summary>
    public int ConsecutiveCorrect { get; init; }
    /// <summary> 近 20 次正确率（间隔系数 0.5~1.5） </summary>
    public double HistoryAccuracy { get; init; }
    /// <summary> 预留（Phase2 SM-2） </summary>
    public double EaseFactor { get; init; }
    /// <summary> 下次复习（驱动队列） </summary>
    public DateTime NextReviewAt { get; init; }
    /// <summary> 最近一次作答 </summary>
    public long? LastAttemptId { get; init; }
    /// <summary> 最近求助档位（None/Partial/Full） </summary>
    public required HintLevel LastHintLevel { get; init; }
    /// <summary> 创建时间（框架审计字段） </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 更新时间（框架审计字段） </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static MemoryStatesDto FromEntity(MemoryStates entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new MemoryStatesDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UId = entity.UId,
            UserId = entity.UserId,
            QuestionId = entity.QuestionId,
            BankId = entity.BankId,
            State = entity.State,
            ConsecutiveCorrect = entity.ConsecutiveCorrect,
            HistoryAccuracy = entity.HistoryAccuracy,
            EaseFactor = entity.EaseFactor,
            NextReviewAt = entity.NextReviewAt,
            LastAttemptId = entity.LastAttemptId,
            LastHintLevel = entity.LastHintLevel,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<MemoryStates, MemoryStatesDto>> SelectExpression => e => new MemoryStatesDto
    {
        Id = e.Id,
        UId = e.UId,
        UserId = e.UserId,
        QuestionId = e.QuestionId,
        BankId = e.BankId,
        State = e.State,
        ConsecutiveCorrect = e.ConsecutiveCorrect,
        HistoryAccuracy = e.HistoryAccuracy,
        EaseFactor = e.EaseFactor,
        NextReviewAt = e.NextReviewAt,
        LastAttemptId = e.LastAttemptId,
        LastHintLevel = e.LastHintLevel,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    MemoryStates IDomainDto<MemoryStates>.ApplyToEntity(MemoryStates entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UId), d => d.UId, (e, v) => e.UId = v )
            .Map(nameof(UserId), d => d.UserId, (e, v) => e.UserId = v )
            .Map(nameof(QuestionId), d => d.QuestionId, (e, v) => e.QuestionId = v )
            .Map(nameof(BankId), d => d.BankId, (e, v) => e.BankId = v )
            .Map(nameof(State), d => d.State, (e, v) => e.State = v )
            .Map(nameof(ConsecutiveCorrect), d => d.ConsecutiveCorrect, (e, v) => e.ConsecutiveCorrect = v )
            .Map(nameof(HistoryAccuracy), d => d.HistoryAccuracy, (e, v) => e.HistoryAccuracy = v )
            .Map(nameof(EaseFactor), d => d.EaseFactor, (e, v) => e.EaseFactor = v )
            .Map(nameof(NextReviewAt), d => d.NextReviewAt, (e, v) => e.NextReviewAt = v )
            .Map(nameof(LastAttemptId), d => d.LastAttemptId, (e, v) => e.LastAttemptId = v )
            .Map(nameof(LastHintLevel), d => d.LastHintLevel, (e, v) => e.LastHintLevel = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    MemoryStates IDomainDto<MemoryStates>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(MemoryStatesDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<MemoryStates>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<MemoryStates, MemoryStatesDto>(scene, results)
                .MaxLength(nameof(UId), 32, d => d.UId)
                .MaxLength(nameof(QuestionId), 64, d => d.QuestionId)
                .MaxLength(nameof(BankId), 64, d => d.BankId)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class MemoryStatesDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static MemoryStatesDto ToDto(this MemoryStates entity) => MemoryStatesDto.FromEntity(entity);
}

