// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: d2ea6e02d28998647c170622a035e8f64a33b1269124b47b42fdd848bad42fa3]
// 模型: OneTimeInviteCodes (XiaoShuTong.Entities.GroupManagement.OneTimeInviteCodes)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using XiaoShuTong;
using XiaoShuTong.Entities.GroupManagement;

namespace XiaoShuTong.Entities.GroupManagement.DTOs;
/// <summary>条件工厂（V4.9）。支持两种使用方式：     <list type="bullet">     <item><c>OneTimeInviteCodes.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>     <item><c>OneTimeInviteCodes.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>     </list></summary>
public partial record OneTimeInviteCodesDto : IDomainDto<OneTimeInviteCodes>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键 </summary>
    public long Id { get; init; }
    /// <summary> 外部业务键（uuid，API/DTO 暴露） </summary>
    public required string UId { get; init; }
    /// <summary> 所属群组 </summary>
    public long GroupId { get; init; }
    /// <summary> 一次性邀请码（8 位） </summary>
    public required string Code { get; init; }
    /// <summary> 名单手机号后四位（脱敏定向标识） </summary>
    public required string PhoneLast4 { get; init; }
    /// <summary> 状态（Unused/Used/Expired） </summary>
    public required OneTimeCodeStatus Status { get; init; }
    /// <summary> 群主（生成者） </summary>
    public long GeneratedBy { get; init; }
    /// <summary> 来源名单批次 </summary>
    public long? RosterImportId { get; init; }
    /// <summary> 生成时间 </summary>
    public DateTime GeneratedAt { get; init; }
    /// <summary> 有效期（可空：内测期默认 30 天） </summary>
    public DateTime? ExpiresAt { get; init; }
    /// <summary> 激活时间 </summary>
    public DateTime? UsedAt { get; init; }
    /// <summary> 激活绑定（成员微信 OpenId → UserId） </summary>
    public long? BoundUserId { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static OneTimeInviteCodesDto FromEntity(OneTimeInviteCodes entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new OneTimeInviteCodesDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UId = entity.UId,
            GroupId = entity.GroupId,
            Code = entity.Code,
            PhoneLast4 = entity.PhoneLast4,
            Status = entity.Status,
            GeneratedBy = entity.GeneratedBy,
            RosterImportId = entity.RosterImportId,
            GeneratedAt = entity.GeneratedAt,
            ExpiresAt = entity.ExpiresAt,
            UsedAt = entity.UsedAt,
            BoundUserId = entity.BoundUserId,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<OneTimeInviteCodes, OneTimeInviteCodesDto>> SelectExpression => e => new OneTimeInviteCodesDto
    {
        Id = e.Id,
        UId = e.UId,
        GroupId = e.GroupId,
        Code = e.Code,
        PhoneLast4 = e.PhoneLast4,
        Status = e.Status,
        GeneratedBy = e.GeneratedBy,
        RosterImportId = e.RosterImportId,
        GeneratedAt = e.GeneratedAt,
        ExpiresAt = e.ExpiresAt,
        UsedAt = e.UsedAt,
        BoundUserId = e.BoundUserId,
    };
    #endregion

    OneTimeInviteCodes IDomainDto<OneTimeInviteCodes>.ApplyToEntity(OneTimeInviteCodes entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UId), d => d.UId, (e, v) => e.UId = v )
            .Map(nameof(GroupId), d => d.GroupId, (e, v) => e.GroupId = v )
            .Map(nameof(Code), d => d.Code, (e, v) => e.Code = v )
            .Map(nameof(PhoneLast4), d => d.PhoneLast4, (e, v) => e.PhoneLast4 = v )
            .Map(nameof(Status), d => d.Status, (e, v) => e.Status = v )
            .Map(nameof(GeneratedBy), d => d.GeneratedBy, (e, v) => e.GeneratedBy = v )
            .Map(nameof(RosterImportId), d => d.RosterImportId, (e, v) => e.RosterImportId = v )
            .Map(nameof(ExpiresAt), d => d.ExpiresAt, (e, v) => e.ExpiresAt = v )
            .Map(nameof(UsedAt), d => d.UsedAt, (e, v) => e.UsedAt = v )
            .Map(nameof(BoundUserId), d => d.BoundUserId, (e, v) => e.BoundUserId = v )
        ;
        return entity;
    }

    OneTimeInviteCodes IDomainDto<OneTimeInviteCodes>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(OneTimeInviteCodesDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<OneTimeInviteCodes>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<OneTimeInviteCodes, OneTimeInviteCodesDto>(scene, results)
                .MaxLength(nameof(UId), 32, d => d.UId)
                .MaxLength(nameof(Code), 8, d => d.Code)
                .MaxLength(nameof(PhoneLast4), 4, d => d.PhoneLast4)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class OneTimeInviteCodesDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static OneTimeInviteCodesDto ToDto(this OneTimeInviteCodes entity) => OneTimeInviteCodesDto.FromEntity(entity);
}

