// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: dee5bed9cced9363a1b2c3750cdc97a7e9333765a45bb93ff886c7a4e9274781]
// 模型: PkAttempts (XiaoShuTong.Entities.Pk.PkAttempts)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using XiaoShuTong;
using XiaoShuTong.Entities.Pk;

namespace XiaoShuTong.Entities.Pk.DTOs;
/// <summary>条件工厂（V4.9）。支持两种使用方式：     <list type="bullet">     <item><c>PkAttempts.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>     <item><c>PkAttempts.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>     </list></summary>
public partial record PkAttemptsDto : IDomainDto<PkAttempts>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 自增主键 </summary>
    public long Id { get; init; }
    /// <summary> 外部业务键 </summary>
    public required string UId { get; init; }
    /// <summary> 对局归属 </summary>
    public long MatchId { get; init; }
    /// <summary> 参赛者成绩记录 </summary>
    public long PlayerId { get; init; }
    /// <summary> 答题用户 </summary>
    public long UserId { get; init; }
    /// <summary> 题目业务键 </summary>
    public required string QuestionId { get; init; }
    /// <summary> 用户答案 </summary>
    public string? Answer { get; init; }
    /// <summary> 判题结果（Correct/Partial/Wrong） </summary>
    public required PkAttemptResult Result { get; init; }
    /// <summary> 答对标记（Correct=true；Partial/Wrong=false） </summary>
    public bool IsCorrect { get; init; }
    /// <summary> 答题用时（毫秒，客户端上送） </summary>
    public int TimeCostMs { get; init; }
    /// <summary> 创建时间（框架审计字段） </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 更新时间（框架审计字段） </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static PkAttemptsDto FromEntity(PkAttempts entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new PkAttemptsDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UId = entity.UId,
            MatchId = entity.MatchId,
            PlayerId = entity.PlayerId,
            UserId = entity.UserId,
            QuestionId = entity.QuestionId,
            Answer = entity.Answer,
            Result = entity.Result,
            IsCorrect = entity.IsCorrect,
            TimeCostMs = entity.TimeCostMs,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<PkAttempts, PkAttemptsDto>> SelectExpression => e => new PkAttemptsDto
    {
        Id = e.Id,
        UId = e.UId,
        MatchId = e.MatchId,
        PlayerId = e.PlayerId,
        UserId = e.UserId,
        QuestionId = e.QuestionId,
        Answer = e.Answer,
        Result = e.Result,
        IsCorrect = e.IsCorrect,
        TimeCostMs = e.TimeCostMs,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    PkAttempts IDomainDto<PkAttempts>.ApplyToEntity(PkAttempts entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UId), d => d.UId, (e, v) => e.UId = v )
            .Map(nameof(MatchId), d => d.MatchId, (e, v) => e.MatchId = v )
            .Map(nameof(PlayerId), d => d.PlayerId, (e, v) => e.PlayerId = v )
            .Map(nameof(UserId), d => d.UserId, (e, v) => e.UserId = v )
            .Map(nameof(QuestionId), d => d.QuestionId, (e, v) => e.QuestionId = v )
            .Map(nameof(Answer), d => d.Answer, (e, v) => e.Answer = v )
            .Map(nameof(Result), d => d.Result, (e, v) => e.Result = v )
            .Map(nameof(IsCorrect), d => d.IsCorrect, (e, v) => e.IsCorrect = v )
            .Map(nameof(TimeCostMs), d => d.TimeCostMs, (e, v) => e.TimeCostMs = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    PkAttempts IDomainDto<PkAttempts>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(PkAttemptsDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<PkAttempts>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<PkAttempts, PkAttemptsDto>(scene, results)
                .MaxLength(nameof(UId), 32, d => d.UId)
                .MaxLength(nameof(QuestionId), 64, d => d.QuestionId)
                .MaxLength(nameof(Answer), 512, d => d.Answer)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class PkAttemptsDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static PkAttemptsDto ToDto(this PkAttempts entity) => PkAttemptsDto.FromEntity(entity);
}

