// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 97060515850fce4001d44a0b94d2b25f38f6b60c39456b68cf3744097e074c90]
// 模型: PkMatches (XiaoShuTong.Entities.Pk.PkMatches)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using XiaoShuTong;
using XiaoShuTong.Entities.Pk;

namespace XiaoShuTong.Entities.Pk.DTOs;
/// <summary>条件工厂（V4.9）。支持两种使用方式：     <list type="bullet">     <item><c>PkMatches.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>     <item><c>PkMatches.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>     </list></summary>
public partial record PkMatchesDto : IDomainDto<PkMatches>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 自增主键 </summary>
    public long Id { get; init; }
    /// <summary> 外部业务键（uuid，API/DTO 暴露） </summary>
    public required string UId { get; init; }
    /// <summary> 学科 </summary>
    public required Subject Subject { get; init; }
    /// <summary> 题库业务键 </summary>
    public required string BankId { get; init; }
    /// <summary> 知识点/主题（按知识点自动出题） </summary>
    public string? Topic { get; init; }
    /// <summary> 题量（5/10/20） </summary>
    public int QuestionCount { get; init; }
    /// <summary> 每题限时（秒） </summary>
    public int PerQuestionTimeS { get; init; }
    /// <summary> 总时长上限（秒） </summary>
    public int TotalTimeLimitS { get; init; }
    /// <summary> 模式（Sync/Async） </summary>
    public required PkMode Mode { get; init; }
    /// <summary> 状态（Pending/Ongoing/Finished/Cancelled） </summary>
    public required PkMatchStatus Status { get; init; }
    /// <summary> 胜方（NULL=平局） </summary>
    public long? WinnerId { get; init; }
    /// <summary> 4 位对战码（方式 B 加入） </summary>
    public string? InviteCode { get; init; }
    /// <summary> 结束原因（Score/Forfeit/Timeout） </summary>
    public PkFinishReason? FinishReason { get; init; }
    /// <summary> 创建时间（D02 原 CreatedAt） </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 结束时间 </summary>
    public DateTime? FinishedAt { get; init; }
    /// <summary> 更新时间（框架审计字段） </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static PkMatchesDto FromEntity(PkMatches entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new PkMatchesDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UId = entity.UId,
            Subject = entity.Subject,
            BankId = entity.BankId,
            Topic = entity.Topic,
            QuestionCount = entity.QuestionCount,
            PerQuestionTimeS = entity.PerQuestionTimeS,
            TotalTimeLimitS = entity.TotalTimeLimitS,
            Mode = entity.Mode,
            Status = entity.Status,
            WinnerId = entity.WinnerId,
            InviteCode = entity.InviteCode,
            FinishReason = entity.FinishReason,
            CreateTime = entity.CreateTime,
            FinishedAt = entity.FinishedAt,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<PkMatches, PkMatchesDto>> SelectExpression => e => new PkMatchesDto
    {
        Id = e.Id,
        UId = e.UId,
        Subject = e.Subject,
        BankId = e.BankId,
        Topic = e.Topic,
        QuestionCount = e.QuestionCount,
        PerQuestionTimeS = e.PerQuestionTimeS,
        TotalTimeLimitS = e.TotalTimeLimitS,
        Mode = e.Mode,
        Status = e.Status,
        WinnerId = e.WinnerId,
        InviteCode = e.InviteCode,
        FinishReason = e.FinishReason,
        CreateTime = e.CreateTime,
        FinishedAt = e.FinishedAt,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    PkMatches IDomainDto<PkMatches>.ApplyToEntity(PkMatches entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UId), d => d.UId, (e, v) => e.UId = v )
            .Map(nameof(Subject), d => d.Subject, (e, v) => e.Subject = v )
            .Map(nameof(BankId), d => d.BankId, (e, v) => e.BankId = v )
            .Map(nameof(Topic), d => d.Topic, (e, v) => e.Topic = v )
            .Map(nameof(QuestionCount), d => d.QuestionCount, (e, v) => e.QuestionCount = v )
            .Map(nameof(PerQuestionTimeS), d => d.PerQuestionTimeS, (e, v) => e.PerQuestionTimeS = v )
            .Map(nameof(TotalTimeLimitS), d => d.TotalTimeLimitS, (e, v) => e.TotalTimeLimitS = v )
            .Map(nameof(Mode), d => d.Mode, (e, v) => e.Mode = v )
            .Map(nameof(Status), d => d.Status, (e, v) => e.Status = v )
            .Map(nameof(WinnerId), d => d.WinnerId, (e, v) => e.WinnerId = v )
            .Map(nameof(InviteCode), d => d.InviteCode, (e, v) => e.InviteCode = v )
            .Map(nameof(FinishReason), d => d.FinishReason, (e, v) => e.FinishReason = v )
            .Map(nameof(FinishedAt), d => d.FinishedAt, (e, v) => e.FinishedAt = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    PkMatches IDomainDto<PkMatches>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(PkMatchesDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<PkMatches>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<PkMatches, PkMatchesDto>(scene, results)
                .MaxLength(nameof(UId), 32, d => d.UId)
                .MaxLength(nameof(BankId), 64, d => d.BankId)
                .MaxLength(nameof(Topic), 128, d => d.Topic)
                .MaxLength(nameof(InviteCode), 4, d => d.InviteCode)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class PkMatchesDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static PkMatchesDto ToDto(this PkMatches entity) => PkMatchesDto.FromEntity(entity);
}

