// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: a2efe1608945c78ac24b6a1eb09c485ff4f127290e44f1ea5188ad11290d5234]
// 模型: PkPlayerStatsView (XiaoShuTong.Entities.Pk.PkPlayerStatsView)
// 生成时间: 2026-09-12 04:26:46
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using XiaoShuTong.Entities.Pk;

namespace XiaoShuTong.Entities.Pk.DTOs;
/// <summary>PK 战绩视图（每用户一行：Finished 对局聚合）</summary>
public partial record PkPlayerStatsViewDto : IDomainDto<PkPlayerStatsView>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 业务唯一键（UserId 透传，稳定） </summary>
    public long Id { get; init; }
    /// <summary> 用户 Id（分组键 + RLS 过滤） </summary>
    public long UserId { get; init; }
    /// <summary> 总场次（仅 Finished 计入） </summary>
    public long TotalMatches { get; init; }
    /// <summary> 胜场 </summary>
    public long Wins { get; init; }
    /// <summary> 平局场次 </summary>
    public long Draws { get; init; }
    /// <summary> 累计分（Finished 对局 Score 之和） </summary>
    public long TotalScore { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static PkPlayerStatsViewDto FromEntity(PkPlayerStatsView entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new PkPlayerStatsViewDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UserId = entity.UserId,
            TotalMatches = entity.TotalMatches,
            Wins = entity.Wins,
            Draws = entity.Draws,
            TotalScore = entity.TotalScore,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<PkPlayerStatsView, PkPlayerStatsViewDto>> SelectExpression => e => new PkPlayerStatsViewDto
    {
        Id = e.Id,
        UserId = e.UserId,
        TotalMatches = e.TotalMatches,
        Wins = e.Wins,
        Draws = e.Draws,
        TotalScore = e.TotalScore,
    };
    #endregion

    PkPlayerStatsView IDomainDto<PkPlayerStatsView>.ApplyToEntity(PkPlayerStatsView entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UserId), d => d.UserId, (e, v) => e.UserId = v )
            .Map(nameof(TotalMatches), d => d.TotalMatches, (e, v) => e.TotalMatches = v )
            .Map(nameof(Wins), d => d.Wins, (e, v) => e.Wins = v )
            .Map(nameof(Draws), d => d.Draws, (e, v) => e.Draws = v )
            .Map(nameof(TotalScore), d => d.TotalScore, (e, v) => e.TotalScore = v )
        ;
        return entity;
    }

    PkPlayerStatsView IDomainDto<PkPlayerStatsView>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(PkPlayerStatsViewDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<PkPlayerStatsView>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<PkPlayerStatsView, PkPlayerStatsViewDto>(scene, results)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class PkPlayerStatsViewDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static PkPlayerStatsViewDto ToDto(this PkPlayerStatsView entity) => PkPlayerStatsViewDto.FromEntity(entity);
}

