// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 7aacf5a5146a3f98bbec79d8bd7595cfd2d4958f100679b90f925df6199ea4a2]
// 模型: PkPlayers (XiaoShuTong.Entities.Pk.PkPlayers)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using XiaoShuTong.Entities.Pk;

namespace XiaoShuTong.Entities.Pk.DTOs;
/// <summary>条件工厂（V4.9）。支持两种使用方式：     <list type="bullet">     <item><c>PkPlayers.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>     <item><c>PkPlayers.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>     </list></summary>
public partial record PkPlayersDto : IDomainDto<PkPlayers>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 自增主键 </summary>
    public long Id { get; init; }
    /// <summary> 外部业务键 </summary>
    public required string UId { get; init; }
    /// <summary> 对局归属 </summary>
    public long MatchId { get; init; }
    /// <summary> 参赛者 </summary>
    public long UserId { get; init; }
    /// <summary> 总分（每题 +10） </summary>
    public int Score { get; init; }
    /// <summary> 答对数 </summary>
    public int CorrectCount { get; init; }
    /// <summary> 总用时（毫秒，同分比用时） </summary>
    public int TotalTimeMs { get; init; }
    /// <summary> AI 趣味点评（失败留空 + 兜底文案） </summary>
    public string? AiComment { get; init; }
    /// <summary> 创建时间（框架审计字段） </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 更新时间（框架审计字段） </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static PkPlayersDto FromEntity(PkPlayers entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new PkPlayersDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UId = entity.UId,
            MatchId = entity.MatchId,
            UserId = entity.UserId,
            Score = entity.Score,
            CorrectCount = entity.CorrectCount,
            TotalTimeMs = entity.TotalTimeMs,
            AiComment = entity.AiComment,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<PkPlayers, PkPlayersDto>> SelectExpression => e => new PkPlayersDto
    {
        Id = e.Id,
        UId = e.UId,
        MatchId = e.MatchId,
        UserId = e.UserId,
        Score = e.Score,
        CorrectCount = e.CorrectCount,
        TotalTimeMs = e.TotalTimeMs,
        AiComment = e.AiComment,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    PkPlayers IDomainDto<PkPlayers>.ApplyToEntity(PkPlayers entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UId), d => d.UId, (e, v) => e.UId = v )
            .Map(nameof(MatchId), d => d.MatchId, (e, v) => e.MatchId = v )
            .Map(nameof(UserId), d => d.UserId, (e, v) => e.UserId = v )
            .Map(nameof(Score), d => d.Score, (e, v) => e.Score = v )
            .Map(nameof(CorrectCount), d => d.CorrectCount, (e, v) => e.CorrectCount = v )
            .Map(nameof(TotalTimeMs), d => d.TotalTimeMs, (e, v) => e.TotalTimeMs = v )
            .Map(nameof(AiComment), d => d.AiComment, (e, v) => e.AiComment = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    PkPlayers IDomainDto<PkPlayers>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(PkPlayersDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<PkPlayers>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<PkPlayers, PkPlayersDto>(scene, results)
                .MaxLength(nameof(UId), 32, d => d.UId)
                .MaxLength(nameof(AiComment), 512, d => d.AiComment)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class PkPlayersDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static PkPlayersDto ToDto(this PkPlayers entity) => PkPlayersDto.FromEntity(entity);
}

