// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: c0b2f60c8dda45a4b5c695634cbc5d63a55e0b46c44ccb6b83d4ea46e6de142e]
// 模型: Questions (XiaoShuTong.Entities.Bank.Questions)
// 生成时间: 2026-09-08 05:56:56
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using XiaoShuTong;
using XiaoShuTong.Entities.Bank;

namespace XiaoShuTong.Entities.Bank.DTOs;
/// <summary>题目索引表（API 查询索引）</summary>
public partial record QuestionsDto : IDomainDto<Questions>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 自增主键 </summary>
    public long Id { get; init; }
    /// <summary> 外部业务键 </summary>
    public required string UId { get; init; }
    /// <summary> 业务键（Q-ch-7a-0001） </summary>
    public required string QuestionId { get; init; }
    /// <summary> 题库业务键（外键引用 Banks.BankId） </summary>
    public required string BankId { get; init; }
    /// <summary> 章节/单元（如 7a） </summary>
    public string? ChapterId { get; init; }
    /// <summary> 题型键（R1/R2/O1...） </summary>
    public required QuestionType QType { get; init; }
    /// <summary> 题目展示内容镜像（JSON，不含答案，防爬） </summary>
    public required string Content { get; init; }
    /// <summary> 知识点列表（JSONB GIN 索引） </summary>
    public required string[] KnowledgePoints { get; init; }
    /// <summary> 难度 0-5 </summary>
    public int Difficulty { get; init; }
    /// <summary> 状态（Active/Superseded/Hidden） </summary>
    public required QuestionStatus Status { get; init; }
    /// <summary> 题目改版替换（软删除） </summary>
    public string? SupersededBy { get; init; }
    /// <summary> 创建时间 </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 更新时间 </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static QuestionsDto FromEntity(Questions entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new QuestionsDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UId = entity.UId,
            QuestionId = entity.QuestionId,
            BankId = entity.BankId,
            ChapterId = entity.ChapterId,
            QType = entity.QType,
            Content = entity.Content,
            KnowledgePoints = entity.KnowledgePoints,
            Difficulty = entity.Difficulty,
            Status = entity.Status,
            SupersededBy = entity.SupersededBy,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<Questions, QuestionsDto>> SelectExpression => e => new QuestionsDto
    {
        Id = e.Id,
        UId = e.UId,
        QuestionId = e.QuestionId,
        BankId = e.BankId,
        ChapterId = e.ChapterId,
        QType = e.QType,
        Content = e.Content,
        KnowledgePoints = e.KnowledgePoints,
        Difficulty = e.Difficulty,
        Status = e.Status,
        SupersededBy = e.SupersededBy,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    Questions IDomainDto<Questions>.ApplyToEntity(Questions entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UId), d => d.UId, (e, v) => e.UId = v )
            .Map(nameof(QuestionId), d => d.QuestionId, (e, v) => e.QuestionId = v )
            .Map(nameof(BankId), d => d.BankId, (e, v) => e.BankId = v )
            .Map(nameof(ChapterId), d => d.ChapterId, (e, v) => e.ChapterId = v )
            .Map(nameof(QType), d => d.QType, (e, v) => e.QType = v )
            .Map(nameof(Content), d => d.Content, (e, v) => e.Content = v )
            .Map(nameof(KnowledgePoints), d => d.KnowledgePoints, (e, v) => e.KnowledgePoints = v )
            .Map(nameof(Difficulty), d => d.Difficulty, (e, v) => e.Difficulty = v )
            .Map(nameof(Status), d => d.Status, (e, v) => e.Status = v )
            .Map(nameof(SupersededBy), d => d.SupersededBy, (e, v) => e.SupersededBy = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    Questions IDomainDto<Questions>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(QuestionsDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<Questions>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<Questions, QuestionsDto>(scene, results)
                .MaxLength(nameof(UId), 32, d => d.UId)
                .MaxLength(nameof(QuestionId), 64, d => d.QuestionId)
                .MaxLength(nameof(BankId), 64, d => d.BankId)
                .MaxLength(nameof(ChapterId), 32, d => d.ChapterId)
                .MaxLength(nameof(SupersededBy), 64, d => d.SupersededBy)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class QuestionsDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static QuestionsDto ToDto(this Questions entity) => QuestionsDto.FromEntity(entity);
}

