// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: e8cb6e3f6bd063ba61e052308cc78e3ef230acbedf99c1f468b28a1cb178db10]
// 模型: RankSnapshots (XiaoShuTong.Entities.Rank.RankSnapshots)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using XiaoShuTong;
using XiaoShuTong.Entities.Rank;

namespace XiaoShuTong.Entities.Rank.DTOs;
/// <summary>条件工厂（V4.9）。支持两种使用方式：     <list type="bullet">     <item><c>RankSnapshots.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>     <item><c>RankSnapshots.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>     </list></summary>
public partial record RankSnapshotsDto : IDomainDto<RankSnapshots>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 自增主键 </summary>
    public long Id { get; init; }
    /// <summary> 外部业务键（uuid，API/DTO 暴露） </summary>
    public required string UId { get; init; }
    /// <summary> 用户 </summary>
    public long UserId { get; init; }
    /// <summary> 范围类型（Group/Grade） </summary>
    public required RankScopeType ScopeType { get; init; }
    /// <summary> group_id（群组）或 grade_key（年级） </summary>
    public string? ScopeId { get; init; }
    /// <summary> 学科筛选维度（All/语文/…/政治） </summary>
    public required string Subject { get; init; }
    /// <summary> 指标类型（Streak/Volume/PkWins/Accuracy/Mastery/Stars） </summary>
    public required RankMetricType MetricType { get; init; }
    /// <summary> 冻结的指标原始值 </summary>
    public decimal MetricValue { get; init; }
    /// <summary> 冻结的排名（不回溯） </summary>
    public int Rank { get; init; }
    /// <summary> 快照日期 </summary>
    public DateOnly SnapshotDate { get; init; }
    /// <summary> 创建时间（框架审计字段） </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 更新时间（框架审计字段） </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static RankSnapshotsDto FromEntity(RankSnapshots entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new RankSnapshotsDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UId = entity.UId,
            UserId = entity.UserId,
            ScopeType = entity.ScopeType,
            ScopeId = entity.ScopeId,
            Subject = entity.Subject,
            MetricType = entity.MetricType,
            MetricValue = entity.MetricValue,
            Rank = entity.Rank,
            SnapshotDate = entity.SnapshotDate,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<RankSnapshots, RankSnapshotsDto>> SelectExpression => e => new RankSnapshotsDto
    {
        Id = e.Id,
        UId = e.UId,
        UserId = e.UserId,
        ScopeType = e.ScopeType,
        ScopeId = e.ScopeId,
        Subject = e.Subject,
        MetricType = e.MetricType,
        MetricValue = e.MetricValue,
        Rank = e.Rank,
        SnapshotDate = e.SnapshotDate,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    RankSnapshots IDomainDto<RankSnapshots>.ApplyToEntity(RankSnapshots entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UId), d => d.UId, (e, v) => e.UId = v )
            .Map(nameof(UserId), d => d.UserId, (e, v) => e.UserId = v )
            .Map(nameof(ScopeType), d => d.ScopeType, (e, v) => e.ScopeType = v )
            .Map(nameof(ScopeId), d => d.ScopeId, (e, v) => e.ScopeId = v )
            .Map(nameof(Subject), d => d.Subject, (e, v) => e.Subject = v )
            .Map(nameof(MetricType), d => d.MetricType, (e, v) => e.MetricType = v )
            .Map(nameof(MetricValue), d => d.MetricValue, (e, v) => e.MetricValue = v )
            .Map(nameof(Rank), d => d.Rank, (e, v) => e.Rank = v )
            .Map(nameof(SnapshotDate), d => d.SnapshotDate, (e, v) => e.SnapshotDate = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    RankSnapshots IDomainDto<RankSnapshots>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(RankSnapshotsDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<RankSnapshots>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<RankSnapshots, RankSnapshotsDto>(scene, results)
                .MaxLength(nameof(UId), 32, d => d.UId)
                .MaxLength(nameof(ScopeId), 64, d => d.ScopeId)
                .MaxLength(nameof(Subject), 20, d => d.Subject)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class RankSnapshotsDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static RankSnapshotsDto ToDto(this RankSnapshots entity) => RankSnapshotsDto.FromEntity(entity);
}

