// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 7163f0f38206b2b47ebc77da5fefa722fe75bff346d31b7a7a0672b12ad5f247]
// 模型: RosterImports (XiaoShuTong.Entities.GroupManagement.RosterImports)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using XiaoShuTong;
using XiaoShuTong.Entities.GroupManagement;

namespace XiaoShuTong.Entities.GroupManagement.DTOs;
/// <summary>条件工厂（V4.9）。支持两种使用方式：     <list type="bullet">     <item><c>RosterImports.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>     <item><c>RosterImports.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>     </list></summary>
public partial record RosterImportsDto : IDomainDto<RosterImports>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键 </summary>
    public long Id { get; init; }
    /// <summary> 外部业务键（uuid，API/DTO 暴露） </summary>
    public required string UId { get; init; }
    /// <summary> 所属群组 </summary>
    public long GroupId { get; init; }
    /// <summary> 群主 </summary>
    public long OwnerId { get; init; }
    /// <summary> 导入方式（Paste(批量粘贴) / File(文件导入)） </summary>
    public required string ImportMethod { get; init; }
    /// <summary> 原始行数 </summary>
    public int SourceCount { get; init; }
    /// <summary> Agent 整理后有效数（去重/格式校验） </summary>
    public int CleanedCount { get; init; }
    /// <summary> 去重剔除数 </summary>
    public int DuplicateCount { get; init; }
    /// <summary> 非法手机号剔除数 </summary>
    public int InvalidCount { get; init; }
    /// <summary> 状态（Processing/Ready/Exported/Failed） </summary>
    public required RosterImportStatus Status { get; init; }
    /// <summary> 导出的 CSV（OSS） </summary>
    public string? CsvFileUrl { get; init; }
    /// <summary> CSV 有效期（建议 7 天） </summary>
    public DateTime? CsvExpiresAt { get; init; }
    /// <summary> 创建时间 </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 整理完成时间 </summary>
    public DateTime? CompletedAt { get; init; }
    /// <summary> 名单手机号原始列表（JSON 数组，jsonb）。     导入时存原始列表；Agent 整理后覆盖为清洗后列表（去重 + 合法），供预览/生成一次性码使用。     说明：DS01 未定义原始名单存储字段，为支撑 UC-6.6/6.7/6.8 数据流补充（切片验证）。 </summary>
    public string? RawPhonesJson { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static RosterImportsDto FromEntity(RosterImports entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new RosterImportsDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UId = entity.UId,
            GroupId = entity.GroupId,
            OwnerId = entity.OwnerId,
            ImportMethod = entity.ImportMethod,
            SourceCount = entity.SourceCount,
            CleanedCount = entity.CleanedCount,
            DuplicateCount = entity.DuplicateCount,
            InvalidCount = entity.InvalidCount,
            Status = entity.Status,
            CsvFileUrl = entity.CsvFileUrl,
            CsvExpiresAt = entity.CsvExpiresAt,
            CreateTime = entity.CreateTime,
            CompletedAt = entity.CompletedAt,
            RawPhonesJson = entity.RawPhonesJson,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<RosterImports, RosterImportsDto>> SelectExpression => e => new RosterImportsDto
    {
        Id = e.Id,
        UId = e.UId,
        GroupId = e.GroupId,
        OwnerId = e.OwnerId,
        ImportMethod = e.ImportMethod,
        SourceCount = e.SourceCount,
        CleanedCount = e.CleanedCount,
        DuplicateCount = e.DuplicateCount,
        InvalidCount = e.InvalidCount,
        Status = e.Status,
        CsvFileUrl = e.CsvFileUrl,
        CsvExpiresAt = e.CsvExpiresAt,
        CreateTime = e.CreateTime,
        CompletedAt = e.CompletedAt,
        RawPhonesJson = e.RawPhonesJson,
    };
    #endregion

    RosterImports IDomainDto<RosterImports>.ApplyToEntity(RosterImports entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UId), d => d.UId, (e, v) => e.UId = v )
            .Map(nameof(GroupId), d => d.GroupId, (e, v) => e.GroupId = v )
            .Map(nameof(OwnerId), d => d.OwnerId, (e, v) => e.OwnerId = v )
            .Map(nameof(ImportMethod), d => d.ImportMethod, (e, v) => e.ImportMethod = v )
            .Map(nameof(SourceCount), d => d.SourceCount, (e, v) => e.SourceCount = v )
            .Map(nameof(CleanedCount), d => d.CleanedCount, (e, v) => e.CleanedCount = v )
            .Map(nameof(DuplicateCount), d => d.DuplicateCount, (e, v) => e.DuplicateCount = v )
            .Map(nameof(InvalidCount), d => d.InvalidCount, (e, v) => e.InvalidCount = v )
            .Map(nameof(Status), d => d.Status, (e, v) => e.Status = v )
            .Map(nameof(CsvFileUrl), d => d.CsvFileUrl, (e, v) => e.CsvFileUrl = v )
            .Map(nameof(CsvExpiresAt), d => d.CsvExpiresAt, (e, v) => e.CsvExpiresAt = v )
            .Map(nameof(CompletedAt), d => d.CompletedAt, (e, v) => e.CompletedAt = v )
            .Map(nameof(RawPhonesJson), d => d.RawPhonesJson, (e, v) => e.RawPhonesJson = v )
        ;
        return entity;
    }

    RosterImports IDomainDto<RosterImports>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(RosterImportsDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<RosterImports>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<RosterImports, RosterImportsDto>(scene, results)
                .MaxLength(nameof(UId), 32, d => d.UId)
                .MaxLength(nameof(ImportMethod), 16, d => d.ImportMethod)
                .MaxLength(nameof(CsvFileUrl), 256, d => d.CsvFileUrl)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class RosterImportsDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static RosterImportsDto ToDto(this RosterImports entity) => RosterImportsDto.FromEntity(entity);
}

