// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: dcf740795c6fcfae287ad88780fbdbabe94ef4d514e3247d469a144a5f62ab0a]
// 模型: StudyBuddies (XiaoShuTong.Entities.Buddy.StudyBuddies)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using XiaoShuTong;
using XiaoShuTong.Entities.Buddy;

namespace XiaoShuTong.Entities.Buddy.DTOs;
/// <summary>学习搭子（双向同意制，同一对用户仅一条关系记录）</summary>
public partial record StudyBuddiesDto : IDomainDto<StudyBuddies>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 自增主键 </summary>
    public long Id { get; init; }
    /// <summary> 外部业务键 </summary>
    public required string UId { get; init; }
    /// <summary> 邀请方 </summary>
    public long InviterId { get; init; }
    /// <summary> 被邀请方 </summary>
    public long InviteeId { get; init; }
    /// <summary> 状态（Pending/Accepted/Rejected/Removed/Expired） </summary>
    public required BuddyStatus Status { get; init; }
    /// <summary> 邀请时间 </summary>
    public DateTime InvitedAt { get; init; }
    /// <summary> 同意时间 </summary>
    public DateTime? AcceptedAt { get; init; }
    /// <summary> 邀请过期（InvitedAt + 7 天） </summary>
    public DateTime ExpiresAt { get; init; }
    /// <summary> 创建时间（框架审计字段） </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 更新时间（框架审计字段） </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static StudyBuddiesDto FromEntity(StudyBuddies entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new StudyBuddiesDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UId = entity.UId,
            InviterId = entity.InviterId,
            InviteeId = entity.InviteeId,
            Status = entity.Status,
            InvitedAt = entity.InvitedAt,
            AcceptedAt = entity.AcceptedAt,
            ExpiresAt = entity.ExpiresAt,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<StudyBuddies, StudyBuddiesDto>> SelectExpression => e => new StudyBuddiesDto
    {
        Id = e.Id,
        UId = e.UId,
        InviterId = e.InviterId,
        InviteeId = e.InviteeId,
        Status = e.Status,
        InvitedAt = e.InvitedAt,
        AcceptedAt = e.AcceptedAt,
        ExpiresAt = e.ExpiresAt,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    StudyBuddies IDomainDto<StudyBuddies>.ApplyToEntity(StudyBuddies entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UId), d => d.UId, (e, v) => e.UId = v )
            .Map(nameof(InviterId), d => d.InviterId, (e, v) => e.InviterId = v )
            .Map(nameof(InviteeId), d => d.InviteeId, (e, v) => e.InviteeId = v )
            .Map(nameof(Status), d => d.Status, (e, v) => e.Status = v )
            .Map(nameof(InvitedAt), d => d.InvitedAt, (e, v) => e.InvitedAt = v )
            .Map(nameof(AcceptedAt), d => d.AcceptedAt, (e, v) => e.AcceptedAt = v )
            .Map(nameof(ExpiresAt), d => d.ExpiresAt, (e, v) => e.ExpiresAt = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    StudyBuddies IDomainDto<StudyBuddies>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(StudyBuddiesDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<StudyBuddies>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<StudyBuddies, StudyBuddiesDto>(scene, results)
                .MaxLength(nameof(UId), 32, d => d.UId)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class StudyBuddiesDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static StudyBuddiesDto ToDto(this StudyBuddies entity) => StudyBuddiesDto.FromEntity(entity);
}

