// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 852a82b262aa0f2839cfd60fc3f4762d39efe3d5e3abf89db5f3f66c301277a1]
// 模型: StudySessions (XiaoShuTong.Entities.Learning.StudySessions)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using XiaoShuTong;
using XiaoShuTong.Entities.Learning;

namespace XiaoShuTong.Entities.Learning.DTOs;
/// <summary>条件工厂（V4.9）。支持两种使用方式：     <list type="bullet">     <item><c>StudySessions.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>     <item><c>StudySessions.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>     </list></summary>
public partial record StudySessionsDto : IDomainDto<StudySessions>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 自增主键 </summary>
    public long Id { get; init; }
    /// <summary> 外部业务键（uuid，API/DTO 暴露） </summary>
    public required string UId { get; init; }
    /// <summary> 学生用户 </summary>
    public long UserId { get; init; }
    /// <summary> 场景（Memorize/Assess/PlayPk/PlayDaily） </summary>
    public required LearningScenario Scenario { get; init; }
    /// <summary> 题库业务键（跨模块引用 Banks） </summary>
    public required string BankId { get; init; }
    /// <summary> 会话类型（Progressive/Free/Assembled/Level/Pk） </summary>
    public required SessionType SessionType { get; init; }
    /// <summary> 计划题数 </summary>
    public int QuestionCount { get; init; }
    /// <summary> 本次答对题数 </summary>
    public int CorrectCount { get; init; }
    /// <summary> 累计用时（毫秒） </summary>
    public int TotalTimeMs { get; init; }
    /// <summary> 群组任务归属（个人背诵 NULL） </summary>
    public long? TaskId { get; init; }
    /// <summary> 会话开始时间 </summary>
    public DateTime StartedAt { get; init; }
    /// <summary> 会话结束时间 </summary>
    public DateTime? EndedAt { get; init; }
    /// <summary> 创建时间（框架审计字段） </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 更新时间（框架审计字段） </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static StudySessionsDto FromEntity(StudySessions entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new StudySessionsDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UId = entity.UId,
            UserId = entity.UserId,
            Scenario = entity.Scenario,
            BankId = entity.BankId,
            SessionType = entity.SessionType,
            QuestionCount = entity.QuestionCount,
            CorrectCount = entity.CorrectCount,
            TotalTimeMs = entity.TotalTimeMs,
            TaskId = entity.TaskId,
            StartedAt = entity.StartedAt,
            EndedAt = entity.EndedAt,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<StudySessions, StudySessionsDto>> SelectExpression => e => new StudySessionsDto
    {
        Id = e.Id,
        UId = e.UId,
        UserId = e.UserId,
        Scenario = e.Scenario,
        BankId = e.BankId,
        SessionType = e.SessionType,
        QuestionCount = e.QuestionCount,
        CorrectCount = e.CorrectCount,
        TotalTimeMs = e.TotalTimeMs,
        TaskId = e.TaskId,
        StartedAt = e.StartedAt,
        EndedAt = e.EndedAt,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    StudySessions IDomainDto<StudySessions>.ApplyToEntity(StudySessions entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UId), d => d.UId, (e, v) => e.UId = v )
            .Map(nameof(UserId), d => d.UserId, (e, v) => e.UserId = v )
            .Map(nameof(Scenario), d => d.Scenario, (e, v) => e.Scenario = v )
            .Map(nameof(BankId), d => d.BankId, (e, v) => e.BankId = v )
            .Map(nameof(SessionType), d => d.SessionType, (e, v) => e.SessionType = v )
            .Map(nameof(QuestionCount), d => d.QuestionCount, (e, v) => e.QuestionCount = v )
            .Map(nameof(CorrectCount), d => d.CorrectCount, (e, v) => e.CorrectCount = v )
            .Map(nameof(TotalTimeMs), d => d.TotalTimeMs, (e, v) => e.TotalTimeMs = v )
            .Map(nameof(TaskId), d => d.TaskId, (e, v) => e.TaskId = v )
            .Map(nameof(StartedAt), d => d.StartedAt, (e, v) => e.StartedAt = v )
            .Map(nameof(EndedAt), d => d.EndedAt, (e, v) => e.EndedAt = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    StudySessions IDomainDto<StudySessions>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(StudySessionsDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<StudySessions>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<StudySessions, StudySessionsDto>(scene, results)
                .MaxLength(nameof(UId), 32, d => d.UId)
                .MaxLength(nameof(BankId), 64, d => d.BankId)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class StudySessionsDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static StudySessionsDto ToDto(this StudySessions entity) => StudySessionsDto.FromEntity(entity);
}

