// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: c8a6a3858c0683dec2e0754349b0fdc53a104b6b65c1e29add7250c679d2dad0]
// 模型: Subscriptions (XiaoShuTong.Entities.Parent.Subscriptions)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using XiaoShuTong;
using XiaoShuTong.Entities.Parent;

namespace XiaoShuTong.Entities.Parent.DTOs;
/// <summary>条件工厂（V4.9）。支持两种使用方式：     <list type="bullet">     <item><c>Subscriptions.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>     <item><c>Subscriptions.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>     </list></summary>
public partial record SubscriptionsDto : IDomainDto<Subscriptions>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 自增主键 </summary>
    public long Id { get; init; }
    /// <summary> 外部业务键 </summary>
    public required string UId { get; init; }
    /// <summary> 家长 </summary>
    public long ParentId { get; init; }
    /// <summary> 孩子（报告对象） </summary>
    public long StudentId { get; init; }
    /// <summary> 方案（Month/Year） </summary>
    public required SubscriptionPlan Plan { get; init; }
    /// <summary> 状态（Trialing/Active/Expired/Cancelled） </summary>
    public required SubscriptionStatus Status { get; init; }
    /// <summary> 试用结束（试用期 7 天） </summary>
    public DateTime? TrialEndAt { get; init; }
    /// <summary> 当前计费周期结束 </summary>
    public DateTime? PeriodEndAt { get; init; }
    /// <summary> 创建时间（框架审计字段） </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 更新时间（框架审计字段） </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static SubscriptionsDto FromEntity(Subscriptions entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new SubscriptionsDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UId = entity.UId,
            ParentId = entity.ParentId,
            StudentId = entity.StudentId,
            Plan = entity.Plan,
            Status = entity.Status,
            TrialEndAt = entity.TrialEndAt,
            PeriodEndAt = entity.PeriodEndAt,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<Subscriptions, SubscriptionsDto>> SelectExpression => e => new SubscriptionsDto
    {
        Id = e.Id,
        UId = e.UId,
        ParentId = e.ParentId,
        StudentId = e.StudentId,
        Plan = e.Plan,
        Status = e.Status,
        TrialEndAt = e.TrialEndAt,
        PeriodEndAt = e.PeriodEndAt,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    Subscriptions IDomainDto<Subscriptions>.ApplyToEntity(Subscriptions entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UId), d => d.UId, (e, v) => e.UId = v )
            .Map(nameof(ParentId), d => d.ParentId, (e, v) => e.ParentId = v )
            .Map(nameof(StudentId), d => d.StudentId, (e, v) => e.StudentId = v )
            .Map(nameof(Plan), d => d.Plan, (e, v) => e.Plan = v )
            .Map(nameof(Status), d => d.Status, (e, v) => e.Status = v )
            .Map(nameof(TrialEndAt), d => d.TrialEndAt, (e, v) => e.TrialEndAt = v )
            .Map(nameof(PeriodEndAt), d => d.PeriodEndAt, (e, v) => e.PeriodEndAt = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    Subscriptions IDomainDto<Subscriptions>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(SubscriptionsDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<Subscriptions>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<Subscriptions, SubscriptionsDto>(scene, results)
                .MaxLength(nameof(UId), 32, d => d.UId)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class SubscriptionsDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static SubscriptionsDto ToDto(this Subscriptions entity) => SubscriptionsDto.FromEntity(entity);
}

