// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 7a1c1c6dd76aa65cebbe85333005901bf83056e129e752499006eeb6f4adcde4]
// 模型: TaskAssignments (XiaoShuTong.Entities.TaskManagement.TaskAssignments)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using XiaoShuTong;
using XiaoShuTong.Entities.TaskManagement;

namespace XiaoShuTong.Entities.TaskManagement.DTOs;
/// <summary>条件工厂（V4.9）。支持两种使用方式：     <list type="bullet">     <item><c>TaskAssignments.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>     <item><c>TaskAssignments.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>     </list></summary>
public partial record TaskAssignmentsDto : IDomainDto<TaskAssignments>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 自增主键 </summary>
    public long Id { get; init; }
    /// <summary> 外部业务键 </summary>
    public required string UId { get; init; }
    /// <summary> 所属任务 </summary>
    public long TaskId { get; init; }
    /// <summary> 学生 </summary>
    public long UserId { get; init; }
    /// <summary> 状态（Pending/InProgress/Completed/Overdue） </summary>
    public required AssignmentStatus Status { get; init; }
    /// <summary> 完成度 0-100（已完成题数/总题数） </summary>
    public int Progress { get; init; }
    /// <summary> 关联学习会话（执行任务时创建，跨模块） </summary>
    public long? SessionId { get; init; }
    /// <summary> 分配时间 </summary>
    public DateTime AssignedAt { get; init; }
    /// <summary> 首次开始时间 </summary>
    public DateTime? StartedAt { get; init; }
    /// <summary> 全部完成时间 </summary>
    public DateTime? CompletedAt { get; init; }
    /// <summary> 创建时间（框架审计字段） </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 更新时间（框架审计字段） </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static TaskAssignmentsDto FromEntity(TaskAssignments entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new TaskAssignmentsDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UId = entity.UId,
            TaskId = entity.TaskId,
            UserId = entity.UserId,
            Status = entity.Status,
            Progress = entity.Progress,
            SessionId = entity.SessionId,
            AssignedAt = entity.AssignedAt,
            StartedAt = entity.StartedAt,
            CompletedAt = entity.CompletedAt,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<TaskAssignments, TaskAssignmentsDto>> SelectExpression => e => new TaskAssignmentsDto
    {
        Id = e.Id,
        UId = e.UId,
        TaskId = e.TaskId,
        UserId = e.UserId,
        Status = e.Status,
        Progress = e.Progress,
        SessionId = e.SessionId,
        AssignedAt = e.AssignedAt,
        StartedAt = e.StartedAt,
        CompletedAt = e.CompletedAt,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    TaskAssignments IDomainDto<TaskAssignments>.ApplyToEntity(TaskAssignments entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UId), d => d.UId, (e, v) => e.UId = v )
            .Map(nameof(TaskId), d => d.TaskId, (e, v) => e.TaskId = v )
            .Map(nameof(UserId), d => d.UserId, (e, v) => e.UserId = v )
            .Map(nameof(Status), d => d.Status, (e, v) => e.Status = v )
            .Map(nameof(Progress), d => d.Progress, (e, v) => e.Progress = v )
            .Map(nameof(SessionId), d => d.SessionId, (e, v) => e.SessionId = v )
            .Map(nameof(AssignedAt), d => d.AssignedAt, (e, v) => e.AssignedAt = v )
            .Map(nameof(StartedAt), d => d.StartedAt, (e, v) => e.StartedAt = v )
            .Map(nameof(CompletedAt), d => d.CompletedAt, (e, v) => e.CompletedAt = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    TaskAssignments IDomainDto<TaskAssignments>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(TaskAssignmentsDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<TaskAssignments>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<TaskAssignments, TaskAssignmentsDto>(scene, results)
                .MaxLength(nameof(UId), 32, d => d.UId)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class TaskAssignmentsDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static TaskAssignmentsDto ToDto(this TaskAssignments entity) => TaskAssignmentsDto.FromEntity(entity);
}

