// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: ac09d1b2005d7394b1556bc804059517d44d2e34209594302b6d80ec7e258673]
// 模型: Tasks (XiaoShuTong.Entities.TaskManagement.Tasks)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using XiaoShuTong;
using XiaoShuTong.Entities.TaskManagement;

namespace XiaoShuTong.Entities.TaskManagement.DTOs;
/// <summary>条件工厂（V4.9）。支持两种使用方式：     <list type="bullet">     <item><c>Tasks.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>     <item><c>Tasks.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>     </list></summary>
public partial record TasksDto : IDomainDto<Tasks>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 自增主键 </summary>
    public long Id { get; init; }
    /// <summary> 外部业务键（uuid，API/DTO 暴露） </summary>
    public required string UId { get; init; }
    /// <summary> 群主（发布者） </summary>
    public long OwnerId { get; init; }
    /// <summary> 目标群组 </summary>
    public long GroupId { get; init; }
    /// <summary> 关联题库（官方/PGC/自定义，业务键） </summary>
    public string? BankId { get; init; }
    /// <summary> 任务标题（≤128） </summary>
    public required string Title { get; init; }
    /// <summary> 任务说明 </summary>
    public string? Description { get; init; }
    /// <summary> 题目 ID 列表（jsonb，任务题集） </summary>
    public required string[] QuestionIds { get; init; }
    /// <summary> 题目数量 </summary>
    public int QuestionCount { get; init; }
    /// <summary> 场景（Memorize/Assess） </summary>
    public required TaskScenario Scenario { get; init; }
    /// <summary> 会话类型（Progressive/Free/Assembled） </summary>
    public required TaskSessionType SessionType { get; init; }
    /// <summary> 是否允许重做（重做不改变 Completed 状态） </summary>
    public bool AllowRedo { get; init; }
    /// <summary> 任务开始时间 </summary>
    public DateTime StartedAt { get; init; }
    /// <summary> 截止时间（NULL=无截止） </summary>
    public DateTime? DeadlineAt { get; init; }
    /// <summary> 状态（Draft/Active/Closed） </summary>
    public required TaskStatus Status { get; init; }
    /// <summary> 创建时间 </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 更新时间 </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static TasksDto FromEntity(Tasks entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new TasksDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UId = entity.UId,
            OwnerId = entity.OwnerId,
            GroupId = entity.GroupId,
            BankId = entity.BankId,
            Title = entity.Title,
            Description = entity.Description,
            QuestionIds = entity.QuestionIds,
            QuestionCount = entity.QuestionCount,
            Scenario = entity.Scenario,
            SessionType = entity.SessionType,
            AllowRedo = entity.AllowRedo,
            StartedAt = entity.StartedAt,
            DeadlineAt = entity.DeadlineAt,
            Status = entity.Status,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<Tasks, TasksDto>> SelectExpression => e => new TasksDto
    {
        Id = e.Id,
        UId = e.UId,
        OwnerId = e.OwnerId,
        GroupId = e.GroupId,
        BankId = e.BankId,
        Title = e.Title,
        Description = e.Description,
        QuestionIds = e.QuestionIds,
        QuestionCount = e.QuestionCount,
        Scenario = e.Scenario,
        SessionType = e.SessionType,
        AllowRedo = e.AllowRedo,
        StartedAt = e.StartedAt,
        DeadlineAt = e.DeadlineAt,
        Status = e.Status,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    Tasks IDomainDto<Tasks>.ApplyToEntity(Tasks entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UId), d => d.UId, (e, v) => e.UId = v )
            .Map(nameof(OwnerId), d => d.OwnerId, (e, v) => e.OwnerId = v )
            .Map(nameof(GroupId), d => d.GroupId, (e, v) => e.GroupId = v )
            .Map(nameof(BankId), d => d.BankId, (e, v) => e.BankId = v )
            .Map(nameof(Title), d => d.Title, (e, v) => e.Title = v )
            .Map(nameof(Description), d => d.Description, (e, v) => e.Description = v )
            .Map(nameof(QuestionIds), d => d.QuestionIds, (e, v) => e.QuestionIds = v )
            .Map(nameof(QuestionCount), d => d.QuestionCount, (e, v) => e.QuestionCount = v )
            .Map(nameof(Scenario), d => d.Scenario, (e, v) => e.Scenario = v )
            .Map(nameof(SessionType), d => d.SessionType, (e, v) => e.SessionType = v )
            .Map(nameof(AllowRedo), d => d.AllowRedo, (e, v) => e.AllowRedo = v )
            .Map(nameof(StartedAt), d => d.StartedAt, (e, v) => e.StartedAt = v )
            .Map(nameof(DeadlineAt), d => d.DeadlineAt, (e, v) => e.DeadlineAt = v )
            .Map(nameof(Status), d => d.Status, (e, v) => e.Status = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    Tasks IDomainDto<Tasks>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(TasksDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<Tasks>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<Tasks, TasksDto>(scene, results)
                .MaxLength(nameof(UId), 32, d => d.UId)
                .MaxLength(nameof(BankId), 64, d => d.BankId)
                .MaxLength(nameof(Title), 128, d => d.Title)
                .MaxLength(nameof(Description), 512, d => d.Description)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class TasksDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static TasksDto ToDto(this Tasks entity) => TasksDto.FromEntity(entity);
}

