/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthPrivacyRouteImport } from './routes/auth/privacy'
import { Route as ParentDashboardRouteImport } from './routes/parent/dashboard'
import { Route as StudentHomeRouteImport } from './routes/student/home'
import { Route as StudentRankRouteImport } from './routes/student/rank'
import { Route as TeacherDashboardRouteImport } from './routes/teacher/dashboard'
import { Route as StudentBankSelfRouteImport } from './routes/student/bank/self'
import { Route as StudentStatsHeatmapRouteImport } from './routes/student/stats/heatmap'
import { Route as StudentStatsWrongRouteImport } from './routes/student/stats/wrong'
import { Route as StudentStudyResultRouteImport } from './routes/student/study/result'
import { Route as StudentStudyReviewRouteImport } from './routes/student/study/review'
import { Route as StudentStudyTaskRouteImport } from './routes/student/study/task'
import { Route as StudentUserProfileRouteImport } from './routes/student/user/profile'
import { Route as TeacherTasksCreateRouteImport } from './routes/teacher/tasks/create'
import { Route as TeacherTasksDetailRouteImport } from './routes/teacher/tasks/detail'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPrivacyRoute = AuthPrivacyRouteImport.update({
  id: '/auth/privacy',
  path: '/auth/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentDashboardRoute = ParentDashboardRouteImport.update({
  id: '/parent/dashboard',
  path: '/parent/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentHomeRoute = StudentHomeRouteImport.update({
  id: '/student/home',
  path: '/student/home',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRankRoute = StudentRankRouteImport.update({
  id: '/student/rank',
  path: '/student/rank',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/teacher/dashboard',
  path: '/teacher/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentBankSelfRoute = StudentBankSelfRouteImport.update({
  id: '/student/bank/self',
  path: '/student/bank/self',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentStatsHeatmapRoute = StudentStatsHeatmapRouteImport.update({
  id: '/student/stats/heatmap',
  path: '/student/stats/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentStatsWrongRoute = StudentStatsWrongRouteImport.update({
  id: '/student/stats/wrong',
  path: '/student/stats/wrong',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentStudyResultRoute = StudentStudyResultRouteImport.update({
  id: '/student/study/result',
  path: '/student/study/result',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentStudyReviewRoute = StudentStudyReviewRouteImport.update({
  id: '/student/study/review',
  path: '/student/study/review',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentStudyTaskRoute = StudentStudyTaskRouteImport.update({
  id: '/student/study/task',
  path: '/student/study/task',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentUserProfileRoute = StudentUserProfileRouteImport.update({
  id: '/student/user/profile',
  path: '/student/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherTasksCreateRoute = TeacherTasksCreateRouteImport.update({
  id: '/teacher/tasks/create',
  path: '/teacher/tasks/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherTasksDetailRoute = TeacherTasksDetailRouteImport.update({
  id: '/teacher/tasks/detail',
  path: '/teacher/tasks/detail',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/privacy': typeof AuthPrivacyRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/student/home': typeof StudentHomeRoute
  '/student/rank': typeof StudentRankRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/student/bank/self': typeof StudentBankSelfRoute
  '/student/stats/heatmap': typeof StudentStatsHeatmapRoute
  '/student/stats/wrong': typeof StudentStatsWrongRoute
  '/student/study/result': typeof StudentStudyResultRoute
  '/student/study/review': typeof StudentStudyReviewRoute
  '/student/study/task': typeof StudentStudyTaskRoute
  '/student/user/profile': typeof StudentUserProfileRoute
  '/teacher/tasks/create': typeof TeacherTasksCreateRoute
  '/teacher/tasks/detail': typeof TeacherTasksDetailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/privacy': typeof AuthPrivacyRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/student/home': typeof StudentHomeRoute
  '/student/rank': typeof StudentRankRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/student/bank/self': typeof StudentBankSelfRoute
  '/student/stats/heatmap': typeof StudentStatsHeatmapRoute
  '/student/stats/wrong': typeof StudentStatsWrongRoute
  '/student/study/result': typeof StudentStudyResultRoute
  '/student/study/review': typeof StudentStudyReviewRoute
  '/student/study/task': typeof StudentStudyTaskRoute
  '/student/user/profile': typeof StudentUserProfileRoute
  '/teacher/tasks/create': typeof TeacherTasksCreateRoute
  '/teacher/tasks/detail': typeof TeacherTasksDetailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/privacy': typeof AuthPrivacyRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/student/home': typeof StudentHomeRoute
  '/student/rank': typeof StudentRankRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/student/bank/self': typeof StudentBankSelfRoute
  '/student/stats/heatmap': typeof StudentStatsHeatmapRoute
  '/student/stats/wrong': typeof StudentStatsWrongRoute
  '/student/study/result': typeof StudentStudyResultRoute
  '/student/study/review': typeof StudentStudyReviewRoute
  '/student/study/task': typeof StudentStudyTaskRoute
  '/student/user/profile': typeof StudentUserProfileRoute
  '/teacher/tasks/create': typeof TeacherTasksCreateRoute
  '/teacher/tasks/detail': typeof TeacherTasksDetailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/privacy'
    | '/parent/dashboard'
    | '/student/home'
    | '/student/rank'
    | '/teacher/dashboard'
    | '/student/bank/self'
    | '/student/stats/heatmap'
    | '/student/stats/wrong'
    | '/student/study/result'
    | '/student/study/review'
    | '/student/study/task'
    | '/student/user/profile'
    | '/teacher/tasks/create'
    | '/teacher/tasks/detail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/privacy'
    | '/parent/dashboard'
    | '/student/home'
    | '/student/rank'
    | '/teacher/dashboard'
    | '/student/bank/self'
    | '/student/stats/heatmap'
    | '/student/stats/wrong'
    | '/student/study/result'
    | '/student/study/review'
    | '/student/study/task'
    | '/student/user/profile'
    | '/teacher/tasks/create'
    | '/teacher/tasks/detail'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/privacy'
    | '/parent/dashboard'
    | '/student/home'
    | '/student/rank'
    | '/teacher/dashboard'
    | '/student/bank/self'
    | '/student/stats/heatmap'
    | '/student/stats/wrong'
    | '/student/study/result'
    | '/student/study/review'
    | '/student/study/task'
    | '/student/user/profile'
    | '/teacher/tasks/create'
    | '/teacher/tasks/detail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPrivacyRoute: typeof AuthPrivacyRoute
  ParentDashboardRoute: typeof ParentDashboardRoute
  StudentHomeRoute: typeof StudentHomeRoute
  StudentRankRoute: typeof StudentRankRoute
  TeacherDashboardRoute: typeof TeacherDashboardRoute
  StudentBankSelfRoute: typeof StudentBankSelfRoute
  StudentStatsHeatmapRoute: typeof StudentStatsHeatmapRoute
  StudentStatsWrongRoute: typeof StudentStatsWrongRoute
  StudentStudyResultRoute: typeof StudentStudyResultRoute
  StudentStudyReviewRoute: typeof StudentStudyReviewRoute
  StudentStudyTaskRoute: typeof StudentStudyTaskRoute
  StudentUserProfileRoute: typeof StudentUserProfileRoute
  TeacherTasksCreateRoute: typeof TeacherTasksCreateRoute
  TeacherTasksDetailRoute: typeof TeacherTasksDetailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/privacy': {
      id: '/auth/privacy'
      path: '/auth/privacy'
      fullPath: '/auth/privacy'
      preLoaderRoute: typeof AuthPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/dashboard': {
      id: '/parent/dashboard'
      path: '/parent/dashboard'
      fullPath: '/parent/dashboard'
      preLoaderRoute: typeof ParentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/home': {
      id: '/student/home'
      path: '/student/home'
      fullPath: '/student/home'
      preLoaderRoute: typeof StudentHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/rank': {
      id: '/student/rank'
      path: '/student/rank'
      fullPath: '/student/rank'
      preLoaderRoute: typeof StudentRankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/dashboard': {
      id: '/teacher/dashboard'
      path: '/teacher/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof TeacherDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/bank/self': {
      id: '/student/bank/self'
      path: '/student/bank/self'
      fullPath: '/student/bank/self'
      preLoaderRoute: typeof StudentBankSelfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/stats/heatmap': {
      id: '/student/stats/heatmap'
      path: '/student/stats/heatmap'
      fullPath: '/student/stats/heatmap'
      preLoaderRoute: typeof StudentStatsHeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/stats/wrong': {
      id: '/student/stats/wrong'
      path: '/student/stats/wrong'
      fullPath: '/student/stats/wrong'
      preLoaderRoute: typeof StudentStatsWrongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/study/result': {
      id: '/student/study/result'
      path: '/student/study/result'
      fullPath: '/student/study/result'
      preLoaderRoute: typeof StudentStudyResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/study/review': {
      id: '/student/study/review'
      path: '/student/study/review'
      fullPath: '/student/study/review'
      preLoaderRoute: typeof StudentStudyReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/study/task': {
      id: '/student/study/task'
      path: '/student/study/task'
      fullPath: '/student/study/task'
      preLoaderRoute: typeof StudentStudyTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/user/profile': {
      id: '/student/user/profile'
      path: '/student/user/profile'
      fullPath: '/student/user/profile'
      preLoaderRoute: typeof StudentUserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/tasks/create': {
      id: '/teacher/tasks/create'
      path: '/teacher/tasks/create'
      fullPath: '/teacher/tasks/create'
      preLoaderRoute: typeof TeacherTasksCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/tasks/detail': {
      id: '/teacher/tasks/detail'
      path: '/teacher/tasks/detail'
      fullPath: '/teacher/tasks/detail'
      preLoaderRoute: typeof TeacherTasksDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPrivacyRoute: AuthPrivacyRoute,
  ParentDashboardRoute: ParentDashboardRoute,
  StudentHomeRoute: StudentHomeRoute,
  StudentRankRoute: StudentRankRoute,
  TeacherDashboardRoute: TeacherDashboardRoute,
  StudentBankSelfRoute: StudentBankSelfRoute,
  StudentStatsHeatmapRoute: StudentStatsHeatmapRoute,
  StudentStatsWrongRoute: StudentStatsWrongRoute,
  StudentStudyResultRoute: StudentStudyResultRoute,
  StudentStudyReviewRoute: StudentStudyReviewRoute,
  StudentStudyTaskRoute: StudentStudyTaskRoute,
  StudentUserProfileRoute: StudentUserProfileRoute,
  TeacherTasksCreateRoute: TeacherTasksCreateRoute,
  TeacherTasksDetailRoute: TeacherTasksDetailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
