// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: aba57168f98fd2ecf22449d5da0c58dde9d118f3cb72b4584e90d695df7ce6e9]
// 模型: Attempts (XiaoShuTong.Entities.Learning.Attempts)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq.Expressions;
using TKW.Framework;
using TKW.Framework.Domain;
using TKW.Framework.Extensions;

namespace XiaoShuTong.Entities.Learning;

/// <summary>
/// 条件工厂（V4.9）。支持两种使用方式：
/// <list type="bullet">
/// <item><c>Attempts.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>
/// <item><c>Attempts.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>
/// </list>
/// </summary>
partial class Attempts
{
    // --- 静态条件方法（直接返回 Expression） ---
    public static class Conditions
    {
        /// <summary>组合条件：QuestionId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Attempts, bool>> ByQuestionId(string questionId)
        {
            return x => x.QuestionId == questionId;
        }

        /// <summary>模糊搜索：QuestionId（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<Attempts, bool>> LikeQuestionId(string? questionId = null)
        {
            if (string.IsNullOrEmpty(questionId)) return None;
            var val = questionId!;
            return x => x.QuestionId.Contains(val);
        }
        /// <summary>多值模糊搜索：QuestionId（按 QuestionId Or-链）</summary>
        public static Expression<Func<Attempts, bool>> LikeQuestionIdKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<Attempts>(x => x.QuestionId, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：QuestionId（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<Attempts, bool>> EqualQuestionId(string value)
        {
            return x => x.QuestionId == value;
        }
        /// <summary>组合条件：Result（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Attempts, bool>> ByResult(JudgmentResult result)
        {
            return x => x.Result == result;
        }

        /// <summary>组合条件：SessionId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Attempts, bool>> BySessionId(long? sessionId)
        {
            return x => x.SessionId == sessionId;
        }

        /// <summary>组合条件：UId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Attempts, bool>> ByUId(string uId)
        {
            return x => x.UId == uId;
        }

        /// <summary>模糊搜索：UId（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<Attempts, bool>> LikeUId(string? uId = null)
        {
            if (string.IsNullOrEmpty(uId)) return None;
            var val = uId!;
            return x => x.UId.Contains(val);
        }
        /// <summary>多值模糊搜索：UId（按 UId Or-链）</summary>
        public static Expression<Func<Attempts, bool>> LikeUIdKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<Attempts>(x => x.UId, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：UId（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<Attempts, bool>> EqualUId(string value)
        {
            return x => x.UId == value;
        }
        /// <summary>组合条件：UserId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Attempts, bool>> ByUserId(long userId)
        {
            return x => x.UserId == userId;
        }

        /// <summary>组合条件：UseridAnsweredat（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Attempts, bool>> ByUseridAnsweredat(long userId, DateTime? beginAnsweredAt = null, DateTime? endAnsweredAt = null)
        {
            return x => x.UserId == userId &&
            (!beginAnsweredAt.HasValue || x.AnsweredAt >= beginAnsweredAt.Value) &&
            (!endAnsweredAt.HasValue || x.AnsweredAt <= endAnsweredAt.Value);
        }

        /// <summary>时间范围：AnsweredAt（begin/end 可选，返回非可空）</summary>
        public static Expression<Func<Attempts, bool>> ByAnsweredAtRange(DateTime? begin = null, DateTime? end = null)
        {
            return x => (!begin.HasValue || x.AnsweredAt >= begin.Value)
                     && (!end.HasValue || x.AnsweredAt <= end.Value);
        }
        /// <summary>组合条件：UseridQuestionid（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Attempts, bool>> ByUseridQuestionid(long userId, string questionId)
        {
            return x => x.UserId == userId &&
            x.QuestionId == questionId;
        }

        /// <summary>多值模糊搜索：UseridQuestionid（按 QuestionId Or-链）</summary>
        public static Expression<Func<Attempts, bool>> LikeUseridQuestionidKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<Attempts>(x => x.QuestionId, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：UseridQuestionid（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<Attempts, bool>> EqualUseridQuestionid(string value)
        {
            return x => x.QuestionId == value;
        }
        /// <summary>组合条件：UseridResult（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Attempts, bool>> ByUseridResult(long userId, JudgmentResult result)
        {
            return x => x.UserId == userId &&
            x.Result == result;
        }

        /// <summary>恒真表达式（无筛选条件时的 Identity 值）</summary>
        public static Expression<Func<Attempts, bool>> None => x => true;

        /// <summary>组合多个条件（AND 连接）。所有条件同时满足。</summary>
        public static Expression<Func<Attempts, bool>> All(params Expression<Func<Attempts, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.And(result, predicates[i]);
            return result;
        }

        /// <summary>组合多个条件（OR 连接）。任一条件满足即可。</summary>
        public static Expression<Func<Attempts, bool>> Any(params Expression<Func<Attempts, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.Or(result, predicates[i]);
            return result;
        }
    }

    // --- 链式 Builder（Entity.Where.ByXxx().ByYyy()，基类 PredicateBuilderBase<T> 提供 Update/Where/Or/If/隐式转换） ---
    /// <summary>链式条件构造器入口。<c>Attempts.Where.ByMemberId(123).ByStatus(1)</c></summary>
    public static PredicateBuilder Where => new PredicateBuilder();

    public sealed class PredicateBuilder : PredicateBuilderBase<Attempts>
    {

        /// <summary>组合条件：QuestionId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByQuestionId(string questionId)
            => (PredicateBuilder)Update(Conditions.ByQuestionId(questionId));

        /// <summary>模糊搜索：QuestionId（单个关键字）</summary>
        public PredicateBuilder LikeQuestionId(string? questionId = null)
            => (PredicateBuilder)Update(Conditions.LikeQuestionId(questionId));

        /// <summary>多值模糊搜索：QuestionId（按关键词 Or-链）</summary>
        public PredicateBuilder LikeQuestionIdKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeQuestionIdKeywords(keywords));

        /// <summary>跨属性精确匹配：QuestionId（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualQuestionId(string value)
            => (PredicateBuilder)Update(Conditions.EqualQuestionId(value));

        /// <summary>组合条件：Result（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByResult(JudgmentResult result)
            => (PredicateBuilder)Update(Conditions.ByResult(result));

        /// <summary>组合条件：SessionId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder BySessionId(long? sessionId)
            => (PredicateBuilder)Update(Conditions.BySessionId(sessionId));

        /// <summary>组合条件：UId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByUId(string uId)
            => (PredicateBuilder)Update(Conditions.ByUId(uId));

        /// <summary>模糊搜索：UId（单个关键字）</summary>
        public PredicateBuilder LikeUId(string? uId = null)
            => (PredicateBuilder)Update(Conditions.LikeUId(uId));

        /// <summary>多值模糊搜索：UId（按关键词 Or-链）</summary>
        public PredicateBuilder LikeUIdKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeUIdKeywords(keywords));

        /// <summary>跨属性精确匹配：UId（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualUId(string value)
            => (PredicateBuilder)Update(Conditions.EqualUId(value));

        /// <summary>组合条件：UserId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByUserId(long userId)
            => (PredicateBuilder)Update(Conditions.ByUserId(userId));

        /// <summary>组合条件：UseridAnsweredat（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByUseridAnsweredat(long userId, DateTime? beginAnsweredAt = null, DateTime? endAnsweredAt = null)
            => (PredicateBuilder)Update(Conditions.ByUseridAnsweredat(userId, beginAnsweredAt, endAnsweredAt));

        /// <summary>时间范围：AnsweredAt（begin/end 可选）</summary>
        public PredicateBuilder ByAnsweredAtRange(DateTime? begin = null, DateTime? end = null)
            => (PredicateBuilder)Update(Conditions.ByAnsweredAtRange(begin, end));

        /// <summary>组合条件：UseridQuestionid（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByUseridQuestionid(long userId, string questionId)
            => (PredicateBuilder)Update(Conditions.ByUseridQuestionid(userId, questionId));

        /// <summary>多值模糊搜索：UseridQuestionid（按关键词 Or-链）</summary>
        public PredicateBuilder LikeUseridQuestionidKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeUseridQuestionidKeywords(keywords));

        /// <summary>跨属性精确匹配：UseridQuestionid（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualUseridQuestionid(string value)
            => (PredicateBuilder)Update(Conditions.EqualUseridQuestionid(value));

        /// <summary>组合条件：UseridResult（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByUseridResult(long userId, JudgmentResult result)
            => (PredicateBuilder)Update(Conditions.ByUseridResult(userId, result));
        // V4.9: 工厂方法（AOT 兼容，替代 Activator.CreateInstance）
        protected override PredicateBuilderBase<Attempts> CreateBranch() => new PredicateBuilder();
}
}
