// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 0a60530a3d7856da733ea0995b82f938f37b6767afa8b0db6e2ac4268064a93e]
// 模型: Groups (XiaoShuTong.Entities.GroupManagement.Groups)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq.Expressions;
using TKW.Framework;
using TKW.Framework.Domain;
using TKW.Framework.Extensions;

namespace XiaoShuTong.Entities.GroupManagement;

/// <summary>
/// 条件工厂（V4.9）。支持两种使用方式：
/// <list type="bullet">
/// <item><c>Groups.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>
/// <item><c>Groups.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>
/// </list>
/// </summary>
partial class Groups
{
    // --- 静态条件方法（直接返回 Expression） ---
    public static class Conditions
    {
        /// <summary>组合条件：BetaCodeId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Groups, bool>> ByBetaCodeId(long? betaCodeId)
        {
            return x => x.BetaCodeId == betaCodeId;
        }

        /// <summary>组合条件：Name（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Groups, bool>> ByName(string name)
        {
            return x => x.Name == name;
        }

        /// <summary>模糊搜索：Name（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<Groups, bool>> LikeName(string? name = null)
        {
            if (string.IsNullOrEmpty(name)) return None;
            var val = name!;
            return x => x.Name.Contains(val);
        }
        /// <summary>多值模糊搜索：Name（按 Name Or-链）</summary>
        public static Expression<Func<Groups, bool>> LikeNameKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<Groups>(x => x.Name, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：Name（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<Groups, bool>> EqualName(string value)
        {
            return x => x.Name == value;
        }
        /// <summary>组合条件：OwnerId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Groups, bool>> ByOwnerId(long ownerId)
        {
            return x => x.OwnerId == ownerId;
        }

        /// <summary>组合条件：OwneridStatus（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Groups, bool>> ByOwneridStatus(long ownerId, GroupStatus status)
        {
            return x => x.OwnerId == ownerId &&
            x.Status == status;
        }

        /// <summary>组合条件：Status（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Groups, bool>> ByStatus(GroupStatus status)
        {
            return x => x.Status == status;
        }

        /// <summary>组合条件：UId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Groups, bool>> ByUId(string uId)
        {
            return x => x.UId == uId;
        }

        /// <summary>模糊搜索：UId（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<Groups, bool>> LikeUId(string? uId = null)
        {
            if (string.IsNullOrEmpty(uId)) return None;
            var val = uId!;
            return x => x.UId.Contains(val);
        }
        /// <summary>多值模糊搜索：UId（按 UId Or-链）</summary>
        public static Expression<Func<Groups, bool>> LikeUIdKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<Groups>(x => x.UId, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：UId（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<Groups, bool>> EqualUId(string value)
        {
            return x => x.UId == value;
        }
        /// <summary>恒真表达式（无筛选条件时的 Identity 值）</summary>
        public static Expression<Func<Groups, bool>> None => x => true;

        /// <summary>组合多个条件（AND 连接）。所有条件同时满足。</summary>
        public static Expression<Func<Groups, bool>> All(params Expression<Func<Groups, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.And(result, predicates[i]);
            return result;
        }

        /// <summary>组合多个条件（OR 连接）。任一条件满足即可。</summary>
        public static Expression<Func<Groups, bool>> Any(params Expression<Func<Groups, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.Or(result, predicates[i]);
            return result;
        }
    }

    // --- 链式 Builder（Entity.Where.ByXxx().ByYyy()，基类 PredicateBuilderBase<T> 提供 Update/Where/Or/If/隐式转换） ---
    /// <summary>链式条件构造器入口。<c>Groups.Where.ByMemberId(123).ByStatus(1)</c></summary>
    public static PredicateBuilder Where => new PredicateBuilder();

    public sealed class PredicateBuilder : PredicateBuilderBase<Groups>
    {

        /// <summary>组合条件：BetaCodeId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByBetaCodeId(long? betaCodeId)
            => (PredicateBuilder)Update(Conditions.ByBetaCodeId(betaCodeId));

        /// <summary>组合条件：Name（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByName(string name)
            => (PredicateBuilder)Update(Conditions.ByName(name));

        /// <summary>模糊搜索：Name（单个关键字）</summary>
        public PredicateBuilder LikeName(string? name = null)
            => (PredicateBuilder)Update(Conditions.LikeName(name));

        /// <summary>多值模糊搜索：Name（按关键词 Or-链）</summary>
        public PredicateBuilder LikeNameKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeNameKeywords(keywords));

        /// <summary>跨属性精确匹配：Name（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualName(string value)
            => (PredicateBuilder)Update(Conditions.EqualName(value));

        /// <summary>组合条件：OwnerId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByOwnerId(long ownerId)
            => (PredicateBuilder)Update(Conditions.ByOwnerId(ownerId));

        /// <summary>组合条件：OwneridStatus（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByOwneridStatus(long ownerId, GroupStatus status)
            => (PredicateBuilder)Update(Conditions.ByOwneridStatus(ownerId, status));

        /// <summary>组合条件：Status（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByStatus(GroupStatus status)
            => (PredicateBuilder)Update(Conditions.ByStatus(status));

        /// <summary>组合条件：UId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByUId(string uId)
            => (PredicateBuilder)Update(Conditions.ByUId(uId));

        /// <summary>模糊搜索：UId（单个关键字）</summary>
        public PredicateBuilder LikeUId(string? uId = null)
            => (PredicateBuilder)Update(Conditions.LikeUId(uId));

        /// <summary>多值模糊搜索：UId（按关键词 Or-链）</summary>
        public PredicateBuilder LikeUIdKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeUIdKeywords(keywords));

        /// <summary>跨属性精确匹配：UId（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualUId(string value)
            => (PredicateBuilder)Update(Conditions.EqualUId(value));
        // V4.9: 工厂方法（AOT 兼容，替代 Activator.CreateInstance）
        protected override PredicateBuilderBase<Groups> CreateBranch() => new PredicateBuilder();
}
}
