// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 9c4fdd067fd1506bc0d877e9bef75fa2878be2cb21a243891c024a4f18b35610]
// 模型: GroupMembers (XiaoShuTong.Entities.GroupManagement.GroupMembers)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq.Expressions;
using TKW.Framework;
using TKW.Framework.Domain;
using TKW.Framework.Extensions;

namespace XiaoShuTong.Entities.GroupManagement;

/// <summary>
/// 条件工厂（V4.9）。支持两种使用方式：
/// <list type="bullet">
/// <item><c>GroupMembers.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>
/// <item><c>GroupMembers.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>
/// </list>
/// </summary>
partial class GroupMembers
{
    // --- 静态条件方法（直接返回 Expression） ---
    public static class Conditions
    {
        /// <summary>组合条件：GroupId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<GroupMembers, bool>> ByGroupId(long groupId)
        {
            return x => x.GroupId == groupId;
        }

        /// <summary>组合条件：GroupidRole（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<GroupMembers, bool>> ByGroupidRole(long groupId, MemberRole role)
        {
            return x => x.GroupId == groupId &&
            x.Role == role;
        }

        /// <summary>精确匹配：GroupidUseridRole（Unique 索引，必填参数）</summary>
        public static Expression<Func<GroupMembers, bool>> ByGroupidUseridRole(long groupId, long userId, MemberRole role)
            => x => x.GroupId == groupId && x.UserId == userId && x.Role == role;

        /// <summary>组合条件：InviteCodeId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<GroupMembers, bool>> ByInviteCodeId(long? inviteCodeId)
        {
            return x => x.InviteCodeId == inviteCodeId;
        }

        /// <summary>组合条件：Role（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<GroupMembers, bool>> ByRole(MemberRole role)
        {
            return x => x.Role == role;
        }

        /// <summary>组合条件：UId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<GroupMembers, bool>> ByUId(string uId)
        {
            return x => x.UId == uId;
        }

        /// <summary>模糊搜索：UId（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<GroupMembers, bool>> LikeUId(string? uId = null)
        {
            if (string.IsNullOrEmpty(uId)) return None;
            var val = uId!;
            return x => x.UId.Contains(val);
        }
        /// <summary>多值模糊搜索：UId（按 UId Or-链）</summary>
        public static Expression<Func<GroupMembers, bool>> LikeUIdKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<GroupMembers>(x => x.UId, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：UId（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<GroupMembers, bool>> EqualUId(string value)
        {
            return x => x.UId == value;
        }
        /// <summary>组合条件：UserId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<GroupMembers, bool>> ByUserId(long userId)
        {
            return x => x.UserId == userId;
        }

        /// <summary>恒真表达式（无筛选条件时的 Identity 值）</summary>
        public static Expression<Func<GroupMembers, bool>> None => x => true;

        /// <summary>组合多个条件（AND 连接）。所有条件同时满足。</summary>
        public static Expression<Func<GroupMembers, bool>> All(params Expression<Func<GroupMembers, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.And(result, predicates[i]);
            return result;
        }

        /// <summary>组合多个条件（OR 连接）。任一条件满足即可。</summary>
        public static Expression<Func<GroupMembers, bool>> Any(params Expression<Func<GroupMembers, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.Or(result, predicates[i]);
            return result;
        }
    }

    // --- 链式 Builder（Entity.Where.ByXxx().ByYyy()，基类 PredicateBuilderBase<T> 提供 Update/Where/Or/If/隐式转换） ---
    /// <summary>链式条件构造器入口。<c>GroupMembers.Where.ByMemberId(123).ByStatus(1)</c></summary>
    public static PredicateBuilder Where => new PredicateBuilder();

    public sealed class PredicateBuilder : PredicateBuilderBase<GroupMembers>
    {

        /// <summary>组合条件：GroupId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByGroupId(long groupId)
            => (PredicateBuilder)Update(Conditions.ByGroupId(groupId));

        /// <summary>组合条件：GroupidRole（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByGroupidRole(long groupId, MemberRole role)
            => (PredicateBuilder)Update(Conditions.ByGroupidRole(groupId, role));

        /// <summary>精确匹配：GroupidUseridRole（Unique 索引，必填参数）</summary>
        public PredicateBuilder ByGroupidUseridRole(long groupId, long userId, MemberRole role)
            => (PredicateBuilder)Update(Conditions.ByGroupidUseridRole(groupId, userId, role));

        /// <summary>组合条件：InviteCodeId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByInviteCodeId(long? inviteCodeId)
            => (PredicateBuilder)Update(Conditions.ByInviteCodeId(inviteCodeId));

        /// <summary>组合条件：Role（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByRole(MemberRole role)
            => (PredicateBuilder)Update(Conditions.ByRole(role));

        /// <summary>组合条件：UId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByUId(string uId)
            => (PredicateBuilder)Update(Conditions.ByUId(uId));

        /// <summary>模糊搜索：UId（单个关键字）</summary>
        public PredicateBuilder LikeUId(string? uId = null)
            => (PredicateBuilder)Update(Conditions.LikeUId(uId));

        /// <summary>多值模糊搜索：UId（按关键词 Or-链）</summary>
        public PredicateBuilder LikeUIdKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeUIdKeywords(keywords));

        /// <summary>跨属性精确匹配：UId（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualUId(string value)
            => (PredicateBuilder)Update(Conditions.EqualUId(value));

        /// <summary>组合条件：UserId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByUserId(long userId)
            => (PredicateBuilder)Update(Conditions.ByUserId(userId));
        // V4.9: 工厂方法（AOT 兼容，替代 Activator.CreateInstance）
        protected override PredicateBuilderBase<GroupMembers> CreateBranch() => new PredicateBuilder();
}
}
