// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: dd91a9f02772b06ccdade43bdc4a9725e0c09efc9d5435592dc8cf9eaff1e364]
// 模型: OneTimeInviteCodes (XiaoShuTong.Entities.GroupManagement.OneTimeInviteCodes)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq.Expressions;
using TKW.Framework;
using TKW.Framework.Domain;
using TKW.Framework.Extensions;

namespace XiaoShuTong.Entities.GroupManagement;

/// <summary>
/// 条件工厂（V4.9）。支持两种使用方式：
/// <list type="bullet">
/// <item><c>OneTimeInviteCodes.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>
/// <item><c>OneTimeInviteCodes.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>
/// </list>
/// </summary>
partial class OneTimeInviteCodes
{
    // --- 静态条件方法（直接返回 Expression） ---
    public static class Conditions
    {
        /// <summary>组合条件：Code（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<OneTimeInviteCodes, bool>> ByCode(string code)
        {
            return x => x.Code == code;
        }

        /// <summary>模糊搜索：Code（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<OneTimeInviteCodes, bool>> LikeCode(string? code = null)
        {
            if (string.IsNullOrEmpty(code)) return None;
            var val = code!;
            return x => x.Code.Contains(val);
        }
        /// <summary>多值模糊搜索：Code（按 Code Or-链）</summary>
        public static Expression<Func<OneTimeInviteCodes, bool>> LikeCodeKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<OneTimeInviteCodes>(x => x.Code, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：Code（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<OneTimeInviteCodes, bool>> EqualCode(string value)
        {
            return x => x.Code == value;
        }
        /// <summary>组合条件：GroupId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<OneTimeInviteCodes, bool>> ByGroupId(long groupId)
        {
            return x => x.GroupId == groupId;
        }

        /// <summary>组合条件：RosterImportId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<OneTimeInviteCodes, bool>> ByRosterImportId(long? rosterImportId)
        {
            return x => x.RosterImportId == rosterImportId;
        }

        /// <summary>组合条件：Status（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<OneTimeInviteCodes, bool>> ByStatus(OneTimeCodeStatus status)
        {
            return x => x.Status == status;
        }

        /// <summary>组合条件：UId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<OneTimeInviteCodes, bool>> ByUId(string uId)
        {
            return x => x.UId == uId;
        }

        /// <summary>模糊搜索：UId（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<OneTimeInviteCodes, bool>> LikeUId(string? uId = null)
        {
            if (string.IsNullOrEmpty(uId)) return None;
            var val = uId!;
            return x => x.UId.Contains(val);
        }
        /// <summary>多值模糊搜索：UId（按 UId Or-链）</summary>
        public static Expression<Func<OneTimeInviteCodes, bool>> LikeUIdKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<OneTimeInviteCodes>(x => x.UId, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：UId（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<OneTimeInviteCodes, bool>> EqualUId(string value)
        {
            return x => x.UId == value;
        }
        /// <summary>恒真表达式（无筛选条件时的 Identity 值）</summary>
        public static Expression<Func<OneTimeInviteCodes, bool>> None => x => true;

        /// <summary>组合多个条件（AND 连接）。所有条件同时满足。</summary>
        public static Expression<Func<OneTimeInviteCodes, bool>> All(params Expression<Func<OneTimeInviteCodes, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.And(result, predicates[i]);
            return result;
        }

        /// <summary>组合多个条件（OR 连接）。任一条件满足即可。</summary>
        public static Expression<Func<OneTimeInviteCodes, bool>> Any(params Expression<Func<OneTimeInviteCodes, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.Or(result, predicates[i]);
            return result;
        }
    }

    // --- 链式 Builder（Entity.Where.ByXxx().ByYyy()，基类 PredicateBuilderBase<T> 提供 Update/Where/Or/If/隐式转换） ---
    /// <summary>链式条件构造器入口。<c>OneTimeInviteCodes.Where.ByMemberId(123).ByStatus(1)</c></summary>
    public static PredicateBuilder Where => new PredicateBuilder();

    public sealed class PredicateBuilder : PredicateBuilderBase<OneTimeInviteCodes>
    {

        /// <summary>组合条件：Code（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByCode(string code)
            => (PredicateBuilder)Update(Conditions.ByCode(code));

        /// <summary>模糊搜索：Code（单个关键字）</summary>
        public PredicateBuilder LikeCode(string? code = null)
            => (PredicateBuilder)Update(Conditions.LikeCode(code));

        /// <summary>多值模糊搜索：Code（按关键词 Or-链）</summary>
        public PredicateBuilder LikeCodeKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeCodeKeywords(keywords));

        /// <summary>跨属性精确匹配：Code（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualCode(string value)
            => (PredicateBuilder)Update(Conditions.EqualCode(value));

        /// <summary>组合条件：GroupId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByGroupId(long groupId)
            => (PredicateBuilder)Update(Conditions.ByGroupId(groupId));

        /// <summary>组合条件：RosterImportId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByRosterImportId(long? rosterImportId)
            => (PredicateBuilder)Update(Conditions.ByRosterImportId(rosterImportId));

        /// <summary>组合条件：Status（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByStatus(OneTimeCodeStatus status)
            => (PredicateBuilder)Update(Conditions.ByStatus(status));

        /// <summary>组合条件：UId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByUId(string uId)
            => (PredicateBuilder)Update(Conditions.ByUId(uId));

        /// <summary>模糊搜索：UId（单个关键字）</summary>
        public PredicateBuilder LikeUId(string? uId = null)
            => (PredicateBuilder)Update(Conditions.LikeUId(uId));

        /// <summary>多值模糊搜索：UId（按关键词 Or-链）</summary>
        public PredicateBuilder LikeUIdKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeUIdKeywords(keywords));

        /// <summary>跨属性精确匹配：UId（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualUId(string value)
            => (PredicateBuilder)Update(Conditions.EqualUId(value));
        // V4.9: 工厂方法（AOT 兼容，替代 Activator.CreateInstance）
        protected override PredicateBuilderBase<OneTimeInviteCodes> CreateBranch() => new PredicateBuilder();
}
}
