// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: d5b0f1d1e831c4c0938f5b56bc5dcc4977fecdf21733de6bbc4fefc32171c61e]
// 模型: ParentStudentRelations (XiaoShuTong.Entities.Parent.ParentStudentRelations)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq.Expressions;
using TKW.Framework;
using TKW.Framework.Domain;
using TKW.Framework.Extensions;

namespace XiaoShuTong.Entities.Parent;

/// <summary>
/// 条件工厂（V4.9）。支持两种使用方式：
/// <list type="bullet">
/// <item><c>ParentStudentRelations.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>
/// <item><c>ParentStudentRelations.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>
/// </list>
/// </summary>
partial class ParentStudentRelations
{
    // --- 静态条件方法（直接返回 Expression） ---
    public static class Conditions
    {
        /// <summary>组合条件：ParentId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<ParentStudentRelations, bool>> ByParentId(long parentId)
        {
            return x => x.ParentId == parentId;
        }

        /// <summary>精确匹配：ParentrelationsPair（Unique 索引，必填参数）</summary>
        public static Expression<Func<ParentStudentRelations, bool>> ByParentrelationsPair(long parentId, long studentId)
            => x => x.ParentId == parentId && x.StudentId == studentId;

        /// <summary>组合条件：StudentId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<ParentStudentRelations, bool>> ByStudentId(long studentId)
        {
            return x => x.StudentId == studentId;
        }

        /// <summary>组合条件：UId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<ParentStudentRelations, bool>> ByUId(string uId)
        {
            return x => x.UId == uId;
        }

        /// <summary>模糊搜索：UId（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<ParentStudentRelations, bool>> LikeUId(string? uId = null)
        {
            if (string.IsNullOrEmpty(uId)) return None;
            var val = uId!;
            return x => x.UId.Contains(val);
        }
        /// <summary>多值模糊搜索：UId（按 UId Or-链）</summary>
        public static Expression<Func<ParentStudentRelations, bool>> LikeUIdKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<ParentStudentRelations>(x => x.UId, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：UId（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<ParentStudentRelations, bool>> EqualUId(string value)
        {
            return x => x.UId == value;
        }
        /// <summary>恒真表达式（无筛选条件时的 Identity 值）</summary>
        public static Expression<Func<ParentStudentRelations, bool>> None => x => true;

        /// <summary>组合多个条件（AND 连接）。所有条件同时满足。</summary>
        public static Expression<Func<ParentStudentRelations, bool>> All(params Expression<Func<ParentStudentRelations, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.And(result, predicates[i]);
            return result;
        }

        /// <summary>组合多个条件（OR 连接）。任一条件满足即可。</summary>
        public static Expression<Func<ParentStudentRelations, bool>> Any(params Expression<Func<ParentStudentRelations, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.Or(result, predicates[i]);
            return result;
        }
    }

    // --- 链式 Builder（Entity.Where.ByXxx().ByYyy()，基类 PredicateBuilderBase<T> 提供 Update/Where/Or/If/隐式转换） ---
    /// <summary>链式条件构造器入口。<c>ParentStudentRelations.Where.ByMemberId(123).ByStatus(1)</c></summary>
    public static PredicateBuilder Where => new PredicateBuilder();

    public sealed class PredicateBuilder : PredicateBuilderBase<ParentStudentRelations>
    {

        /// <summary>组合条件：ParentId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByParentId(long parentId)
            => (PredicateBuilder)Update(Conditions.ByParentId(parentId));

        /// <summary>精确匹配：ParentrelationsPair（Unique 索引，必填参数）</summary>
        public PredicateBuilder ByParentrelationsPair(long parentId, long studentId)
            => (PredicateBuilder)Update(Conditions.ByParentrelationsPair(parentId, studentId));

        /// <summary>组合条件：StudentId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByStudentId(long studentId)
            => (PredicateBuilder)Update(Conditions.ByStudentId(studentId));

        /// <summary>组合条件：UId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByUId(string uId)
            => (PredicateBuilder)Update(Conditions.ByUId(uId));

        /// <summary>模糊搜索：UId（单个关键字）</summary>
        public PredicateBuilder LikeUId(string? uId = null)
            => (PredicateBuilder)Update(Conditions.LikeUId(uId));

        /// <summary>多值模糊搜索：UId（按关键词 Or-链）</summary>
        public PredicateBuilder LikeUIdKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeUIdKeywords(keywords));

        /// <summary>跨属性精确匹配：UId（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualUId(string value)
            => (PredicateBuilder)Update(Conditions.EqualUId(value));
        // V4.9: 工厂方法（AOT 兼容，替代 Activator.CreateInstance）
        protected override PredicateBuilderBase<ParentStudentRelations> CreateBranch() => new PredicateBuilder();
}
}
