// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 9e2d02094efbc5fa1eafeff92cd6758342360f3aa66139b4fa2a99c93f0f8903]
// 模型: PkAttempts (XiaoShuTong.Entities.Pk.PkAttempts)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq.Expressions;
using TKW.Framework;
using TKW.Framework.Domain;
using TKW.Framework.Extensions;

namespace XiaoShuTong.Entities.Pk;

/// <summary>
/// 条件工厂（V4.9）。支持两种使用方式：
/// <list type="bullet">
/// <item><c>PkAttempts.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>
/// <item><c>PkAttempts.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>
/// </list>
/// </summary>
partial class PkAttempts
{
    // --- 静态条件方法（直接返回 Expression） ---
    public static class Conditions
    {
        /// <summary>精确匹配：Dedup（Unique 索引，必填参数）</summary>
        public static Expression<Func<PkAttempts, bool>> ByDedup(long matchId, long playerId, string questionId)
            => x => x.MatchId == matchId && x.PlayerId == playerId && x.QuestionId == questionId;

        /// <summary>组合条件：MatchId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<PkAttempts, bool>> ByMatchId(long matchId)
        {
            return x => x.MatchId == matchId;
        }

        /// <summary>组合条件：PlayerId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<PkAttempts, bool>> ByPlayerId(long playerId)
        {
            return x => x.PlayerId == playerId;
        }

        /// <summary>组合条件：QuestionId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<PkAttempts, bool>> ByQuestionId(string questionId)
        {
            return x => x.QuestionId == questionId;
        }

        /// <summary>模糊搜索：QuestionId（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<PkAttempts, bool>> LikeQuestionId(string? questionId = null)
        {
            if (string.IsNullOrEmpty(questionId)) return None;
            var val = questionId!;
            return x => x.QuestionId.Contains(val);
        }
        /// <summary>多值模糊搜索：QuestionId（按 QuestionId Or-链）</summary>
        public static Expression<Func<PkAttempts, bool>> LikeQuestionIdKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<PkAttempts>(x => x.QuestionId, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：QuestionId（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<PkAttempts, bool>> EqualQuestionId(string value)
        {
            return x => x.QuestionId == value;
        }
        /// <summary>组合条件：UId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<PkAttempts, bool>> ByUId(string uId)
        {
            return x => x.UId == uId;
        }

        /// <summary>模糊搜索：UId（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<PkAttempts, bool>> LikeUId(string? uId = null)
        {
            if (string.IsNullOrEmpty(uId)) return None;
            var val = uId!;
            return x => x.UId.Contains(val);
        }
        /// <summary>多值模糊搜索：UId（按 UId Or-链）</summary>
        public static Expression<Func<PkAttempts, bool>> LikeUIdKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<PkAttempts>(x => x.UId, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：UId（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<PkAttempts, bool>> EqualUId(string value)
        {
            return x => x.UId == value;
        }
        /// <summary>恒真表达式（无筛选条件时的 Identity 值）</summary>
        public static Expression<Func<PkAttempts, bool>> None => x => true;

        /// <summary>组合多个条件（AND 连接）。所有条件同时满足。</summary>
        public static Expression<Func<PkAttempts, bool>> All(params Expression<Func<PkAttempts, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.And(result, predicates[i]);
            return result;
        }

        /// <summary>组合多个条件（OR 连接）。任一条件满足即可。</summary>
        public static Expression<Func<PkAttempts, bool>> Any(params Expression<Func<PkAttempts, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.Or(result, predicates[i]);
            return result;
        }
    }

    // --- 链式 Builder（Entity.Where.ByXxx().ByYyy()，基类 PredicateBuilderBase<T> 提供 Update/Where/Or/If/隐式转换） ---
    /// <summary>链式条件构造器入口。<c>PkAttempts.Where.ByMemberId(123).ByStatus(1)</c></summary>
    public static PredicateBuilder Where => new PredicateBuilder();

    public sealed class PredicateBuilder : PredicateBuilderBase<PkAttempts>
    {

        /// <summary>精确匹配：Dedup（Unique 索引，必填参数）</summary>
        public PredicateBuilder ByDedup(long matchId, long playerId, string questionId)
            => (PredicateBuilder)Update(Conditions.ByDedup(matchId, playerId, questionId));

        /// <summary>组合条件：MatchId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByMatchId(long matchId)
            => (PredicateBuilder)Update(Conditions.ByMatchId(matchId));

        /// <summary>组合条件：PlayerId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByPlayerId(long playerId)
            => (PredicateBuilder)Update(Conditions.ByPlayerId(playerId));

        /// <summary>组合条件：QuestionId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByQuestionId(string questionId)
            => (PredicateBuilder)Update(Conditions.ByQuestionId(questionId));

        /// <summary>模糊搜索：QuestionId（单个关键字）</summary>
        public PredicateBuilder LikeQuestionId(string? questionId = null)
            => (PredicateBuilder)Update(Conditions.LikeQuestionId(questionId));

        /// <summary>多值模糊搜索：QuestionId（按关键词 Or-链）</summary>
        public PredicateBuilder LikeQuestionIdKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeQuestionIdKeywords(keywords));

        /// <summary>跨属性精确匹配：QuestionId（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualQuestionId(string value)
            => (PredicateBuilder)Update(Conditions.EqualQuestionId(value));

        /// <summary>组合条件：UId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByUId(string uId)
            => (PredicateBuilder)Update(Conditions.ByUId(uId));

        /// <summary>模糊搜索：UId（单个关键字）</summary>
        public PredicateBuilder LikeUId(string? uId = null)
            => (PredicateBuilder)Update(Conditions.LikeUId(uId));

        /// <summary>多值模糊搜索：UId（按关键词 Or-链）</summary>
        public PredicateBuilder LikeUIdKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeUIdKeywords(keywords));

        /// <summary>跨属性精确匹配：UId（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualUId(string value)
            => (PredicateBuilder)Update(Conditions.EqualUId(value));
        // V4.9: 工厂方法（AOT 兼容，替代 Activator.CreateInstance）
        protected override PredicateBuilderBase<PkAttempts> CreateBranch() => new PredicateBuilder();
}
}
