// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: f367b312e22ae7a7f647e80c0b0ae0062644dcef227ee8ef902677e627ae7e26]
// 模型: PkMatches (XiaoShuTong.Entities.Pk.PkMatches)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq.Expressions;
using TKW.Framework;
using TKW.Framework.Domain;
using TKW.Framework.Extensions;

namespace XiaoShuTong.Entities.Pk;

/// <summary>
/// 条件工厂（V4.9）。支持两种使用方式：
/// <list type="bullet">
/// <item><c>PkMatches.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>
/// <item><c>PkMatches.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>
/// </list>
/// </summary>
partial class PkMatches
{
    // --- 静态条件方法（直接返回 Expression） ---
    public static class Conditions
    {
        /// <summary>组合条件：InviteCode（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<PkMatches, bool>> ByInviteCode(string inviteCode)
        {
            return x => x.InviteCode == inviteCode;
        }

        /// <summary>模糊搜索：InviteCode（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<PkMatches, bool>> LikeInviteCode(string? inviteCode = null)
        {
            if (string.IsNullOrEmpty(inviteCode)) return None;
            var val = inviteCode!;
            return x => x.InviteCode != null && x.InviteCode.Contains(val);
        }
        /// <summary>多值模糊搜索：InviteCode（按 InviteCode Or-链）</summary>
        public static Expression<Func<PkMatches, bool>> LikeInviteCodeKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<PkMatches>(x => x.InviteCode, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：InviteCode（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<PkMatches, bool>> EqualInviteCode(string value)
        {
            return x => x.InviteCode == value;
        }
        /// <summary>组合条件：Status（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<PkMatches, bool>> ByStatus(PkMatchStatus status)
        {
            return x => x.Status == status;
        }

        /// <summary>组合条件：StatusCreatedat（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<PkMatches, bool>> ByStatusCreatedat(PkMatchStatus status, DateTime? beginCreateTime = null, DateTime? endCreateTime = null)
        {
            return x => x.Status == status &&
            (!beginCreateTime.HasValue || x.CreateTime >= beginCreateTime.Value) &&
            (!endCreateTime.HasValue || x.CreateTime <= endCreateTime.Value);
        }

        /// <summary>时间范围：CreateTime（begin/end 可选，返回非可空）</summary>
        public static Expression<Func<PkMatches, bool>> ByCreateTimeRange(DateTime? begin = null, DateTime? end = null)
        {
            return x => (!begin.HasValue || x.CreateTime >= begin.Value)
                     && (!end.HasValue || x.CreateTime <= end.Value);
        }
        /// <summary>组合条件：UId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<PkMatches, bool>> ByUId(string uId)
        {
            return x => x.UId == uId;
        }

        /// <summary>模糊搜索：UId（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<PkMatches, bool>> LikeUId(string? uId = null)
        {
            if (string.IsNullOrEmpty(uId)) return None;
            var val = uId!;
            return x => x.UId.Contains(val);
        }
        /// <summary>多值模糊搜索：UId（按 UId Or-链）</summary>
        public static Expression<Func<PkMatches, bool>> LikeUIdKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<PkMatches>(x => x.UId, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：UId（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<PkMatches, bool>> EqualUId(string value)
        {
            return x => x.UId == value;
        }
        /// <summary>组合条件：WinnerId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<PkMatches, bool>> ByWinnerId(long? winnerId)
        {
            return x => x.WinnerId == winnerId;
        }

        /// <summary>恒真表达式（无筛选条件时的 Identity 值）</summary>
        public static Expression<Func<PkMatches, bool>> None => x => true;

        /// <summary>组合多个条件（AND 连接）。所有条件同时满足。</summary>
        public static Expression<Func<PkMatches, bool>> All(params Expression<Func<PkMatches, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.And(result, predicates[i]);
            return result;
        }

        /// <summary>组合多个条件（OR 连接）。任一条件满足即可。</summary>
        public static Expression<Func<PkMatches, bool>> Any(params Expression<Func<PkMatches, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.Or(result, predicates[i]);
            return result;
        }
    }

    // --- 链式 Builder（Entity.Where.ByXxx().ByYyy()，基类 PredicateBuilderBase<T> 提供 Update/Where/Or/If/隐式转换） ---
    /// <summary>链式条件构造器入口。<c>PkMatches.Where.ByMemberId(123).ByStatus(1)</c></summary>
    public static PredicateBuilder Where => new PredicateBuilder();

    public sealed class PredicateBuilder : PredicateBuilderBase<PkMatches>
    {

        /// <summary>组合条件：InviteCode（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByInviteCode(string inviteCode)
            => (PredicateBuilder)Update(Conditions.ByInviteCode(inviteCode));

        /// <summary>模糊搜索：InviteCode（单个关键字）</summary>
        public PredicateBuilder LikeInviteCode(string? inviteCode = null)
            => (PredicateBuilder)Update(Conditions.LikeInviteCode(inviteCode));

        /// <summary>多值模糊搜索：InviteCode（按关键词 Or-链）</summary>
        public PredicateBuilder LikeInviteCodeKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeInviteCodeKeywords(keywords));

        /// <summary>跨属性精确匹配：InviteCode（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualInviteCode(string value)
            => (PredicateBuilder)Update(Conditions.EqualInviteCode(value));

        /// <summary>组合条件：Status（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByStatus(PkMatchStatus status)
            => (PredicateBuilder)Update(Conditions.ByStatus(status));

        /// <summary>组合条件：StatusCreatedat（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByStatusCreatedat(PkMatchStatus status, DateTime? beginCreateTime = null, DateTime? endCreateTime = null)
            => (PredicateBuilder)Update(Conditions.ByStatusCreatedat(status, beginCreateTime, endCreateTime));

        /// <summary>时间范围：CreateTime（begin/end 可选）</summary>
        public PredicateBuilder ByCreateTimeRange(DateTime? begin = null, DateTime? end = null)
            => (PredicateBuilder)Update(Conditions.ByCreateTimeRange(begin, end));

        /// <summary>组合条件：UId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByUId(string uId)
            => (PredicateBuilder)Update(Conditions.ByUId(uId));

        /// <summary>模糊搜索：UId（单个关键字）</summary>
        public PredicateBuilder LikeUId(string? uId = null)
            => (PredicateBuilder)Update(Conditions.LikeUId(uId));

        /// <summary>多值模糊搜索：UId（按关键词 Or-链）</summary>
        public PredicateBuilder LikeUIdKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeUIdKeywords(keywords));

        /// <summary>跨属性精确匹配：UId（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualUId(string value)
            => (PredicateBuilder)Update(Conditions.EqualUId(value));

        /// <summary>组合条件：WinnerId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByWinnerId(long? winnerId)
            => (PredicateBuilder)Update(Conditions.ByWinnerId(winnerId));
        // V4.9: 工厂方法（AOT 兼容，替代 Activator.CreateInstance）
        protected override PredicateBuilderBase<PkMatches> CreateBranch() => new PredicateBuilder();
}
}
