// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 8a40dc8b7a14adc6ce5283b642067b37c68275710810e97937fa48fa26859e7a]
// 模型: Questions (XiaoShuTong.Entities.Bank.Questions)
// 生成时间: 2026-09-08 05:56:57
// </auto-generated>
#nullable enable
using System;
using System.Linq.Expressions;
using TKW.Framework;
using TKW.Framework.Domain;
using TKW.Framework.Extensions;

namespace XiaoShuTong.Entities.Bank;

/// <summary>
/// 条件工厂（V4.9）。支持两种使用方式：
/// <list type="bullet">
/// <item><c>Questions.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>
/// <item><c>Questions.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>
/// </list>
/// </summary>
partial class Questions
{
    // --- 静态条件方法（直接返回 Expression） ---
    public static class Conditions
    {
        /// <summary>组合条件：BankId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Questions, bool>> ByBankId(string bankId)
        {
            return x => x.BankId == bankId;
        }

        /// <summary>模糊搜索：BankId（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<Questions, bool>> LikeBankId(string? bankId = null)
        {
            if (string.IsNullOrEmpty(bankId)) return None;
            var val = bankId!;
            return x => x.BankId.Contains(val);
        }
        /// <summary>多值模糊搜索：BankId（按 BankId Or-链）</summary>
        public static Expression<Func<Questions, bool>> LikeBankIdKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<Questions>(x => x.BankId, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：BankId（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<Questions, bool>> EqualBankId(string value)
        {
            return x => x.BankId == value;
        }
        /// <summary>组合条件：BankidChapter（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Questions, bool>> ByBankidChapter(string bankId, string chapterId)
        {
            return x => x.BankId == bankId &&
            x.ChapterId == chapterId;
        }

        /// <summary>模糊搜索：ChapterId（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<Questions, bool>> LikeChapterId(string? chapterId = null)
        {
            if (string.IsNullOrEmpty(chapterId)) return None;
            var val = chapterId!;
            return x => x.ChapterId != null && x.ChapterId.Contains(val);
        }
        /// <summary>多值模糊搜索：BankidChapter（按 BankId Or-链）</summary>
        public static Expression<Func<Questions, bool>> LikeBankidChapterKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<Questions>(x => x.BankId, keywords) ?? None;
        }
        /// <summary>跨属性模糊搜索：BankidChapter（单个关键字在多个字符串属性中 OR 匹配）</summary>
        public static Expression<Func<Questions, bool>> LikeBankidChapter(string? keyword = null)
        {
            if (string.IsNullOrEmpty(keyword)) return None;
            var kw = keyword!;
            return x => x.BankId.Contains(kw) ||
                x.ChapterId != null && x.ChapterId.Contains(kw);
        }
        /// <summary>跨属性精确匹配：BankidChapter（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<Questions, bool>> EqualBankidChapter(string value)
        {
            return x => x.BankId == value ||
                x.ChapterId == value;
        }
        /// <summary>组合条件：ChapterId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Questions, bool>> ByChapterId(string chapterId)
        {
            return x => x.ChapterId == chapterId;
        }

        /// <summary>多值模糊搜索：ChapterId（按 ChapterId Or-链）</summary>
        public static Expression<Func<Questions, bool>> LikeChapterIdKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<Questions>(x => x.ChapterId, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：ChapterId（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<Questions, bool>> EqualChapterId(string value)
        {
            return x => x.ChapterId == value;
        }
        /// <summary>组合条件：QType（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Questions, bool>> ByQType(QuestionType qType)
        {
            return x => x.QType == qType;
        }

        /// <summary>组合条件：QuestionId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Questions, bool>> ByQuestionId(string questionId)
        {
            return x => x.QuestionId == questionId;
        }

        /// <summary>模糊搜索：QuestionId（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<Questions, bool>> LikeQuestionId(string? questionId = null)
        {
            if (string.IsNullOrEmpty(questionId)) return None;
            var val = questionId!;
            return x => x.QuestionId.Contains(val);
        }
        /// <summary>多值模糊搜索：QuestionId（按 QuestionId Or-链）</summary>
        public static Expression<Func<Questions, bool>> LikeQuestionIdKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<Questions>(x => x.QuestionId, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：QuestionId（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<Questions, bool>> EqualQuestionId(string value)
        {
            return x => x.QuestionId == value;
        }
        /// <summary>组合条件：Status（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Questions, bool>> ByStatus(QuestionStatus status)
        {
            return x => x.Status == status;
        }

        /// <summary>组合条件：UId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Questions, bool>> ByUId(string uId)
        {
            return x => x.UId == uId;
        }

        /// <summary>模糊搜索：UId（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<Questions, bool>> LikeUId(string? uId = null)
        {
            if (string.IsNullOrEmpty(uId)) return None;
            var val = uId!;
            return x => x.UId.Contains(val);
        }
        /// <summary>多值模糊搜索：UId（按 UId Or-链）</summary>
        public static Expression<Func<Questions, bool>> LikeUIdKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<Questions>(x => x.UId, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：UId（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<Questions, bool>> EqualUId(string value)
        {
            return x => x.UId == value;
        }
        /// <summary>恒真表达式（无筛选条件时的 Identity 值）</summary>
        public static Expression<Func<Questions, bool>> None => x => true;

        /// <summary>组合多个条件（AND 连接）。所有条件同时满足。</summary>
        public static Expression<Func<Questions, bool>> All(params Expression<Func<Questions, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.And(result, predicates[i]);
            return result;
        }

        /// <summary>组合多个条件（OR 连接）。任一条件满足即可。</summary>
        public static Expression<Func<Questions, bool>> Any(params Expression<Func<Questions, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.Or(result, predicates[i]);
            return result;
        }
    }

    // --- 链式 Builder（Entity.Where.ByXxx().ByYyy()，基类 PredicateBuilderBase<T> 提供 Update/Where/Or/If/隐式转换） ---
    /// <summary>链式条件构造器入口。<c>Questions.Where.ByMemberId(123).ByStatus(1)</c></summary>
    public static PredicateBuilder Where => new PredicateBuilder();

    public sealed class PredicateBuilder : PredicateBuilderBase<Questions>
    {

        /// <summary>组合条件：BankId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByBankId(string bankId)
            => (PredicateBuilder)Update(Conditions.ByBankId(bankId));

        /// <summary>模糊搜索：BankId（单个关键字）</summary>
        public PredicateBuilder LikeBankId(string? bankId = null)
            => (PredicateBuilder)Update(Conditions.LikeBankId(bankId));

        /// <summary>多值模糊搜索：BankId（按关键词 Or-链）</summary>
        public PredicateBuilder LikeBankIdKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeBankIdKeywords(keywords));

        /// <summary>跨属性精确匹配：BankId（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualBankId(string value)
            => (PredicateBuilder)Update(Conditions.EqualBankId(value));

        /// <summary>组合条件：BankidChapter（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByBankidChapter(string bankId, string chapterId)
            => (PredicateBuilder)Update(Conditions.ByBankidChapter(bankId, chapterId));

        /// <summary>模糊搜索：ChapterId（单个关键字）</summary>
        public PredicateBuilder LikeChapterId(string? chapterId = null)
            => (PredicateBuilder)Update(Conditions.LikeChapterId(chapterId));

        /// <summary>多值模糊搜索：BankidChapter（按关键词 Or-链）</summary>
        public PredicateBuilder LikeBankidChapterKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeBankidChapterKeywords(keywords));

        /// <summary>跨属性模糊搜索：BankidChapter（单个关键字在多个字符串属性中 OR 匹配）</summary>
        public PredicateBuilder LikeBankidChapter(string? keyword = null)
            => (PredicateBuilder)Update(Conditions.LikeBankidChapter(keyword));

        /// <summary>跨属性精确匹配：BankidChapter（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualBankidChapter(string value)
            => (PredicateBuilder)Update(Conditions.EqualBankidChapter(value));

        /// <summary>组合条件：ChapterId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByChapterId(string chapterId)
            => (PredicateBuilder)Update(Conditions.ByChapterId(chapterId));

        /// <summary>多值模糊搜索：ChapterId（按关键词 Or-链）</summary>
        public PredicateBuilder LikeChapterIdKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeChapterIdKeywords(keywords));

        /// <summary>跨属性精确匹配：ChapterId（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualChapterId(string value)
            => (PredicateBuilder)Update(Conditions.EqualChapterId(value));

        /// <summary>组合条件：QType（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByQType(QuestionType qType)
            => (PredicateBuilder)Update(Conditions.ByQType(qType));

        /// <summary>组合条件：QuestionId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByQuestionId(string questionId)
            => (PredicateBuilder)Update(Conditions.ByQuestionId(questionId));

        /// <summary>模糊搜索：QuestionId（单个关键字）</summary>
        public PredicateBuilder LikeQuestionId(string? questionId = null)
            => (PredicateBuilder)Update(Conditions.LikeQuestionId(questionId));

        /// <summary>多值模糊搜索：QuestionId（按关键词 Or-链）</summary>
        public PredicateBuilder LikeQuestionIdKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeQuestionIdKeywords(keywords));

        /// <summary>跨属性精确匹配：QuestionId（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualQuestionId(string value)
            => (PredicateBuilder)Update(Conditions.EqualQuestionId(value));

        /// <summary>组合条件：Status（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByStatus(QuestionStatus status)
            => (PredicateBuilder)Update(Conditions.ByStatus(status));

        /// <summary>组合条件：UId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByUId(string uId)
            => (PredicateBuilder)Update(Conditions.ByUId(uId));

        /// <summary>模糊搜索：UId（单个关键字）</summary>
        public PredicateBuilder LikeUId(string? uId = null)
            => (PredicateBuilder)Update(Conditions.LikeUId(uId));

        /// <summary>多值模糊搜索：UId（按关键词 Or-链）</summary>
        public PredicateBuilder LikeUIdKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeUIdKeywords(keywords));

        /// <summary>跨属性精确匹配：UId（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualUId(string value)
            => (PredicateBuilder)Update(Conditions.EqualUId(value));
        // V4.9: 工厂方法（AOT 兼容，替代 Activator.CreateInstance）
        protected override PredicateBuilderBase<Questions> CreateBranch() => new PredicateBuilder();
}
}
