// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 03c6e32357b0407837af78f8572d5cfb108540ad1c2ce6dfe9125921981a7d38]
// 模型: StudySessions (XiaoShuTong.Entities.Learning.StudySessions)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq.Expressions;
using TKW.Framework;
using TKW.Framework.Domain;
using TKW.Framework.Extensions;

namespace XiaoShuTong.Entities.Learning;

/// <summary>
/// 条件工厂（V4.9）。支持两种使用方式：
/// <list type="bullet">
/// <item><c>StudySessions.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>
/// <item><c>StudySessions.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>
/// </list>
/// </summary>
partial class StudySessions
{
    // --- 静态条件方法（直接返回 Expression） ---
    public static class Conditions
    {
        /// <summary>组合条件：TaskId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<StudySessions, bool>> ByTaskId(long? taskId)
        {
            return x => x.TaskId == taskId;
        }

        /// <summary>组合条件：UId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<StudySessions, bool>> ByUId(string uId)
        {
            return x => x.UId == uId;
        }

        /// <summary>模糊搜索：UId（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<StudySessions, bool>> LikeUId(string? uId = null)
        {
            if (string.IsNullOrEmpty(uId)) return None;
            var val = uId!;
            return x => x.UId.Contains(val);
        }
        /// <summary>多值模糊搜索：UId（按 UId Or-链）</summary>
        public static Expression<Func<StudySessions, bool>> LikeUIdKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<StudySessions>(x => x.UId, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：UId（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<StudySessions, bool>> EqualUId(string value)
        {
            return x => x.UId == value;
        }
        /// <summary>组合条件：UserId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<StudySessions, bool>> ByUserId(long userId)
        {
            return x => x.UserId == userId;
        }

        /// <summary>组合条件：UseridStartedat（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<StudySessions, bool>> ByUseridStartedat(long userId, DateTime? beginStartedAt = null, DateTime? endStartedAt = null)
        {
            return x => x.UserId == userId &&
            (!beginStartedAt.HasValue || x.StartedAt >= beginStartedAt.Value) &&
            (!endStartedAt.HasValue || x.StartedAt <= endStartedAt.Value);
        }

        /// <summary>时间范围：StartedAt（begin/end 可选，返回非可空）</summary>
        public static Expression<Func<StudySessions, bool>> ByStartedAtRange(DateTime? begin = null, DateTime? end = null)
        {
            return x => (!begin.HasValue || x.StartedAt >= begin.Value)
                     && (!end.HasValue || x.StartedAt <= end.Value);
        }
        /// <summary>恒真表达式（无筛选条件时的 Identity 值）</summary>
        public static Expression<Func<StudySessions, bool>> None => x => true;

        /// <summary>组合多个条件（AND 连接）。所有条件同时满足。</summary>
        public static Expression<Func<StudySessions, bool>> All(params Expression<Func<StudySessions, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.And(result, predicates[i]);
            return result;
        }

        /// <summary>组合多个条件（OR 连接）。任一条件满足即可。</summary>
        public static Expression<Func<StudySessions, bool>> Any(params Expression<Func<StudySessions, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.Or(result, predicates[i]);
            return result;
        }
    }

    // --- 链式 Builder（Entity.Where.ByXxx().ByYyy()，基类 PredicateBuilderBase<T> 提供 Update/Where/Or/If/隐式转换） ---
    /// <summary>链式条件构造器入口。<c>StudySessions.Where.ByMemberId(123).ByStatus(1)</c></summary>
    public static PredicateBuilder Where => new PredicateBuilder();

    public sealed class PredicateBuilder : PredicateBuilderBase<StudySessions>
    {

        /// <summary>组合条件：TaskId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByTaskId(long? taskId)
            => (PredicateBuilder)Update(Conditions.ByTaskId(taskId));

        /// <summary>组合条件：UId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByUId(string uId)
            => (PredicateBuilder)Update(Conditions.ByUId(uId));

        /// <summary>模糊搜索：UId（单个关键字）</summary>
        public PredicateBuilder LikeUId(string? uId = null)
            => (PredicateBuilder)Update(Conditions.LikeUId(uId));

        /// <summary>多值模糊搜索：UId（按关键词 Or-链）</summary>
        public PredicateBuilder LikeUIdKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeUIdKeywords(keywords));

        /// <summary>跨属性精确匹配：UId（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualUId(string value)
            => (PredicateBuilder)Update(Conditions.EqualUId(value));

        /// <summary>组合条件：UserId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByUserId(long userId)
            => (PredicateBuilder)Update(Conditions.ByUserId(userId));

        /// <summary>组合条件：UseridStartedat（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByUseridStartedat(long userId, DateTime? beginStartedAt = null, DateTime? endStartedAt = null)
            => (PredicateBuilder)Update(Conditions.ByUseridStartedat(userId, beginStartedAt, endStartedAt));

        /// <summary>时间范围：StartedAt（begin/end 可选）</summary>
        public PredicateBuilder ByStartedAtRange(DateTime? begin = null, DateTime? end = null)
            => (PredicateBuilder)Update(Conditions.ByStartedAtRange(begin, end));
        // V4.9: 工厂方法（AOT 兼容，替代 Activator.CreateInstance）
        protected override PredicateBuilderBase<StudySessions> CreateBranch() => new PredicateBuilder();
}
}
