// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: ebf19b3e0cf9bbb838d87d13eafc5c112aa650a10523485d45beed7a95b1eab7]
// 模型: TaskAssignments (XiaoShuTong.Entities.TaskManagement.TaskAssignments)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq.Expressions;
using TKW.Framework;
using TKW.Framework.Domain;
using TKW.Framework.Extensions;

namespace XiaoShuTong.Entities.TaskManagement;

/// <summary>
/// 条件工厂（V4.9）。支持两种使用方式：
/// <list type="bullet">
/// <item><c>TaskAssignments.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>
/// <item><c>TaskAssignments.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>
/// </list>
/// </summary>
partial class TaskAssignments
{
    // --- 静态条件方法（直接返回 Expression） ---
    public static class Conditions
    {
        /// <summary>组合条件：Status（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<TaskAssignments, bool>> ByStatus(AssignmentStatus status)
        {
            return x => x.Status == status;
        }

        /// <summary>组合条件：TaskId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<TaskAssignments, bool>> ByTaskId(long taskId)
        {
            return x => x.TaskId == taskId;
        }

        /// <summary>组合条件：TaskidStatus（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<TaskAssignments, bool>> ByTaskidStatus(long taskId, AssignmentStatus status)
        {
            return x => x.TaskId == taskId &&
            x.Status == status;
        }

        /// <summary>精确匹配：TaskidUserid（Unique 索引，必填参数）</summary>
        public static Expression<Func<TaskAssignments, bool>> ByTaskidUserid(long taskId, long userId)
            => x => x.TaskId == taskId && x.UserId == userId;

        /// <summary>组合条件：UId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<TaskAssignments, bool>> ByUId(string uId)
        {
            return x => x.UId == uId;
        }

        /// <summary>模糊搜索：UId（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<TaskAssignments, bool>> LikeUId(string? uId = null)
        {
            if (string.IsNullOrEmpty(uId)) return None;
            var val = uId!;
            return x => x.UId.Contains(val);
        }
        /// <summary>多值模糊搜索：UId（按 UId Or-链）</summary>
        public static Expression<Func<TaskAssignments, bool>> LikeUIdKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<TaskAssignments>(x => x.UId, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：UId（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<TaskAssignments, bool>> EqualUId(string value)
        {
            return x => x.UId == value;
        }
        /// <summary>组合条件：UserId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<TaskAssignments, bool>> ByUserId(long userId)
        {
            return x => x.UserId == userId;
        }

        /// <summary>组合条件：UseridStatus（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<TaskAssignments, bool>> ByUseridStatus(long userId, AssignmentStatus status)
        {
            return x => x.UserId == userId &&
            x.Status == status;
        }

        /// <summary>恒真表达式（无筛选条件时的 Identity 值）</summary>
        public static Expression<Func<TaskAssignments, bool>> None => x => true;

        /// <summary>组合多个条件（AND 连接）。所有条件同时满足。</summary>
        public static Expression<Func<TaskAssignments, bool>> All(params Expression<Func<TaskAssignments, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.And(result, predicates[i]);
            return result;
        }

        /// <summary>组合多个条件（OR 连接）。任一条件满足即可。</summary>
        public static Expression<Func<TaskAssignments, bool>> Any(params Expression<Func<TaskAssignments, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.Or(result, predicates[i]);
            return result;
        }
    }

    // --- 链式 Builder（Entity.Where.ByXxx().ByYyy()，基类 PredicateBuilderBase<T> 提供 Update/Where/Or/If/隐式转换） ---
    /// <summary>链式条件构造器入口。<c>TaskAssignments.Where.ByMemberId(123).ByStatus(1)</c></summary>
    public static PredicateBuilder Where => new PredicateBuilder();

    public sealed class PredicateBuilder : PredicateBuilderBase<TaskAssignments>
    {

        /// <summary>组合条件：Status（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByStatus(AssignmentStatus status)
            => (PredicateBuilder)Update(Conditions.ByStatus(status));

        /// <summary>组合条件：TaskId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByTaskId(long taskId)
            => (PredicateBuilder)Update(Conditions.ByTaskId(taskId));

        /// <summary>组合条件：TaskidStatus（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByTaskidStatus(long taskId, AssignmentStatus status)
            => (PredicateBuilder)Update(Conditions.ByTaskidStatus(taskId, status));

        /// <summary>精确匹配：TaskidUserid（Unique 索引，必填参数）</summary>
        public PredicateBuilder ByTaskidUserid(long taskId, long userId)
            => (PredicateBuilder)Update(Conditions.ByTaskidUserid(taskId, userId));

        /// <summary>组合条件：UId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByUId(string uId)
            => (PredicateBuilder)Update(Conditions.ByUId(uId));

        /// <summary>模糊搜索：UId（单个关键字）</summary>
        public PredicateBuilder LikeUId(string? uId = null)
            => (PredicateBuilder)Update(Conditions.LikeUId(uId));

        /// <summary>多值模糊搜索：UId（按关键词 Or-链）</summary>
        public PredicateBuilder LikeUIdKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeUIdKeywords(keywords));

        /// <summary>跨属性精确匹配：UId（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualUId(string value)
            => (PredicateBuilder)Update(Conditions.EqualUId(value));

        /// <summary>组合条件：UserId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByUserId(long userId)
            => (PredicateBuilder)Update(Conditions.ByUserId(userId));

        /// <summary>组合条件：UseridStatus（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByUseridStatus(long userId, AssignmentStatus status)
            => (PredicateBuilder)Update(Conditions.ByUseridStatus(userId, status));
        // V4.9: 工厂方法（AOT 兼容，替代 Activator.CreateInstance）
        protected override PredicateBuilderBase<TaskAssignments> CreateBranch() => new PredicateBuilder();
}
}
