// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: f04717d453cd2d8474beb5d09b0ad6a5de923242b4b5d5bec4dcda49380b877b]
// 模型: Tasks (XiaoShuTong.Entities.TaskManagement.Tasks)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq.Expressions;
using TKW.Framework;
using TKW.Framework.Domain;
using TKW.Framework.Extensions;

namespace XiaoShuTong.Entities.TaskManagement;

/// <summary>
/// 条件工厂（V4.9）。支持两种使用方式：
/// <list type="bullet">
/// <item><c>Tasks.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>
/// <item><c>Tasks.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>
/// </list>
/// </summary>
partial class Tasks
{
    // --- 静态条件方法（直接返回 Expression） ---
    public static class Conditions
    {
        /// <summary>组合条件：Deadlineat（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Tasks, bool>> ByDeadlineat(DateTime? beginDeadlineAt = null, DateTime? endDeadlineAt = null)
        {
            return x => (!beginDeadlineAt.HasValue || x.DeadlineAt >= beginDeadlineAt.Value) &&
            (!endDeadlineAt.HasValue || x.DeadlineAt <= endDeadlineAt.Value);
        }

        /// <summary>时间范围：DeadlineAt（begin/end 可选，返回非可空）</summary>
        public static Expression<Func<Tasks, bool>> ByDeadlineAtRange(DateTime? begin = null, DateTime? end = null)
        {
            return x => (!begin.HasValue || x.DeadlineAt >= begin.Value)
                     && (!end.HasValue || x.DeadlineAt <= end.Value);
        }
        /// <summary>组合条件：GroupId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Tasks, bool>> ByGroupId(long groupId)
        {
            return x => x.GroupId == groupId;
        }

        /// <summary>组合条件：GroupidStatus（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Tasks, bool>> ByGroupidStatus(long groupId, TaskStatus status)
        {
            return x => x.GroupId == groupId &&
            x.Status == status;
        }

        /// <summary>组合条件：OwnerId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Tasks, bool>> ByOwnerId(long ownerId)
        {
            return x => x.OwnerId == ownerId;
        }

        /// <summary>组合条件：OwneridStatus（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Tasks, bool>> ByOwneridStatus(long ownerId, TaskStatus status)
        {
            return x => x.OwnerId == ownerId &&
            x.Status == status;
        }

        /// <summary>组合条件：Status（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Tasks, bool>> ByStatus(TaskStatus status)
        {
            return x => x.Status == status;
        }

        /// <summary>组合条件：Title（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Tasks, bool>> ByTitle(string title)
        {
            return x => x.Title == title;
        }

        /// <summary>模糊搜索：Title（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<Tasks, bool>> LikeTitle(string? title = null)
        {
            if (string.IsNullOrEmpty(title)) return None;
            var val = title!;
            return x => x.Title.Contains(val);
        }
        /// <summary>多值模糊搜索：Title（按 Title Or-链）</summary>
        public static Expression<Func<Tasks, bool>> LikeTitleKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<Tasks>(x => x.Title, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：Title（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<Tasks, bool>> EqualTitle(string value)
        {
            return x => x.Title == value;
        }
        /// <summary>组合条件：UId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<Tasks, bool>> ByUId(string uId)
        {
            return x => x.UId == uId;
        }

        /// <summary>模糊搜索：UId（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<Tasks, bool>> LikeUId(string? uId = null)
        {
            if (string.IsNullOrEmpty(uId)) return None;
            var val = uId!;
            return x => x.UId.Contains(val);
        }
        /// <summary>多值模糊搜索：UId（按 UId Or-链）</summary>
        public static Expression<Func<Tasks, bool>> LikeUIdKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<Tasks>(x => x.UId, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：UId（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<Tasks, bool>> EqualUId(string value)
        {
            return x => x.UId == value;
        }
        /// <summary>恒真表达式（无筛选条件时的 Identity 值）</summary>
        public static Expression<Func<Tasks, bool>> None => x => true;

        /// <summary>组合多个条件（AND 连接）。所有条件同时满足。</summary>
        public static Expression<Func<Tasks, bool>> All(params Expression<Func<Tasks, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.And(result, predicates[i]);
            return result;
        }

        /// <summary>组合多个条件（OR 连接）。任一条件满足即可。</summary>
        public static Expression<Func<Tasks, bool>> Any(params Expression<Func<Tasks, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.Or(result, predicates[i]);
            return result;
        }
    }

    // --- 链式 Builder（Entity.Where.ByXxx().ByYyy()，基类 PredicateBuilderBase<T> 提供 Update/Where/Or/If/隐式转换） ---
    /// <summary>链式条件构造器入口。<c>Tasks.Where.ByMemberId(123).ByStatus(1)</c></summary>
    public static PredicateBuilder Where => new PredicateBuilder();

    public sealed class PredicateBuilder : PredicateBuilderBase<Tasks>
    {

        /// <summary>组合条件：Deadlineat（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByDeadlineat(DateTime? beginDeadlineAt = null, DateTime? endDeadlineAt = null)
            => (PredicateBuilder)Update(Conditions.ByDeadlineat(beginDeadlineAt, endDeadlineAt));

        /// <summary>时间范围：DeadlineAt（begin/end 可选）</summary>
        public PredicateBuilder ByDeadlineAtRange(DateTime? begin = null, DateTime? end = null)
            => (PredicateBuilder)Update(Conditions.ByDeadlineAtRange(begin, end));

        /// <summary>组合条件：GroupId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByGroupId(long groupId)
            => (PredicateBuilder)Update(Conditions.ByGroupId(groupId));

        /// <summary>组合条件：GroupidStatus（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByGroupidStatus(long groupId, TaskStatus status)
            => (PredicateBuilder)Update(Conditions.ByGroupidStatus(groupId, status));

        /// <summary>组合条件：OwnerId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByOwnerId(long ownerId)
            => (PredicateBuilder)Update(Conditions.ByOwnerId(ownerId));

        /// <summary>组合条件：OwneridStatus（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByOwneridStatus(long ownerId, TaskStatus status)
            => (PredicateBuilder)Update(Conditions.ByOwneridStatus(ownerId, status));

        /// <summary>组合条件：Status（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByStatus(TaskStatus status)
            => (PredicateBuilder)Update(Conditions.ByStatus(status));

        /// <summary>组合条件：Title（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByTitle(string title)
            => (PredicateBuilder)Update(Conditions.ByTitle(title));

        /// <summary>模糊搜索：Title（单个关键字）</summary>
        public PredicateBuilder LikeTitle(string? title = null)
            => (PredicateBuilder)Update(Conditions.LikeTitle(title));

        /// <summary>多值模糊搜索：Title（按关键词 Or-链）</summary>
        public PredicateBuilder LikeTitleKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeTitleKeywords(keywords));

        /// <summary>跨属性精确匹配：Title（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualTitle(string value)
            => (PredicateBuilder)Update(Conditions.EqualTitle(value));

        /// <summary>组合条件：UId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByUId(string uId)
            => (PredicateBuilder)Update(Conditions.ByUId(uId));

        /// <summary>模糊搜索：UId（单个关键字）</summary>
        public PredicateBuilder LikeUId(string? uId = null)
            => (PredicateBuilder)Update(Conditions.LikeUId(uId));

        /// <summary>多值模糊搜索：UId（按关键词 Or-链）</summary>
        public PredicateBuilder LikeUIdKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeUIdKeywords(keywords));

        /// <summary>跨属性精确匹配：UId（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualUId(string value)
            => (PredicateBuilder)Update(Conditions.EqualUId(value));
        // V4.9: 工厂方法（AOT 兼容，替代 Activator.CreateInstance）
        protected override PredicateBuilderBase<Tasks> CreateBranch() => new PredicateBuilder();
}
}
