// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 17aab803043ab20337bcd5d071cca30a7b743c96402f15092c2f5e3b0ddac70b]
// 模型: WrongQuestions (XiaoShuTong.Entities.Learning.WrongQuestions)
// 生成时间: 2026-09-08 05:19:32
// </auto-generated>
#nullable enable
using System;
using System.Linq.Expressions;
using TKW.Framework;
using TKW.Framework.Domain;
using TKW.Framework.Extensions;

namespace XiaoShuTong.Entities.Learning;

/// <summary>
/// 条件工厂（V4.9）。支持两种使用方式：
/// <list type="bullet">
/// <item><c>WrongQuestions.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>
/// <item><c>WrongQuestions.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>
/// </list>
/// </summary>
partial class WrongQuestions
{
    // --- 静态条件方法（直接返回 Expression） ---
    public static class Conditions
    {
        /// <summary>组合条件：QuestionId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<WrongQuestions, bool>> ByQuestionId(string questionId)
        {
            return x => x.QuestionId == questionId;
        }

        /// <summary>模糊搜索：QuestionId（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<WrongQuestions, bool>> LikeQuestionId(string? questionId = null)
        {
            if (string.IsNullOrEmpty(questionId)) return None;
            var val = questionId!;
            return x => x.QuestionId.Contains(val);
        }
        /// <summary>多值模糊搜索：QuestionId（按 QuestionId Or-链）</summary>
        public static Expression<Func<WrongQuestions, bool>> LikeQuestionIdKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<WrongQuestions>(x => x.QuestionId, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：QuestionId（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<WrongQuestions, bool>> EqualQuestionId(string value)
        {
            return x => x.QuestionId == value;
        }
        /// <summary>组合条件：Subject（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<WrongQuestions, bool>> BySubject(string subject)
        {
            return x => x.Subject == subject;
        }

        /// <summary>模糊搜索：Subject（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<WrongQuestions, bool>> LikeSubject(string? subject = null)
        {
            if (string.IsNullOrEmpty(subject)) return None;
            var val = subject!;
            return x => x.Subject.Contains(val);
        }
        /// <summary>多值模糊搜索：Subject（按 Subject Or-链）</summary>
        public static Expression<Func<WrongQuestions, bool>> LikeSubjectKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<WrongQuestions>(x => x.Subject, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：Subject（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<WrongQuestions, bool>> EqualSubject(string value)
        {
            return x => x.Subject == value;
        }
        /// <summary>组合条件：UId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<WrongQuestions, bool>> ByUId(string uId)
        {
            return x => x.UId == uId;
        }

        /// <summary>模糊搜索：UId（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<WrongQuestions, bool>> LikeUId(string? uId = null)
        {
            if (string.IsNullOrEmpty(uId)) return None;
            var val = uId!;
            return x => x.UId.Contains(val);
        }
        /// <summary>多值模糊搜索：UId（按 UId Or-链）</summary>
        public static Expression<Func<WrongQuestions, bool>> LikeUIdKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<WrongQuestions>(x => x.UId, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：UId（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<WrongQuestions, bool>> EqualUId(string value)
        {
            return x => x.UId == value;
        }
        /// <summary>组合条件：UserId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<WrongQuestions, bool>> ByUserId(long userId)
        {
            return x => x.UserId == userId;
        }

        /// <summary>组合条件：UseridMasteredLastwrongat（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<WrongQuestions, bool>> ByUseridMasteredLastwrongat(long userId, bool mastered, DateTime? beginLastWrongAt = null, DateTime? endLastWrongAt = null)
        {
            return x => x.UserId == userId &&
            x.Mastered == mastered &&
            (!beginLastWrongAt.HasValue || x.LastWrongAt >= beginLastWrongAt.Value) &&
            (!endLastWrongAt.HasValue || x.LastWrongAt <= endLastWrongAt.Value);
        }

        /// <summary>时间范围：LastWrongAt（begin/end 可选，返回非可空）</summary>
        public static Expression<Func<WrongQuestions, bool>> ByLastWrongAtRange(DateTime? begin = null, DateTime? end = null)
        {
            return x => (!begin.HasValue || x.LastWrongAt >= begin.Value)
                     && (!end.HasValue || x.LastWrongAt <= end.Value);
        }
        /// <summary>精确匹配：UseridQuestionid（Unique 索引，必填参数）</summary>
        public static Expression<Func<WrongQuestions, bool>> ByUseridQuestionid(long userId, string questionId)
            => x => x.UserId == userId && x.QuestionId == questionId;

        /// <summary>组合条件：UseridSubject（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<WrongQuestions, bool>> ByUseridSubject(long userId, string subject)
        {
            return x => x.UserId == userId &&
            x.Subject == subject;
        }

        /// <summary>多值模糊搜索：UseridSubject（按 Subject Or-链）</summary>
        public static Expression<Func<WrongQuestions, bool>> LikeUseridSubjectKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<WrongQuestions>(x => x.Subject, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：UseridSubject（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<WrongQuestions, bool>> EqualUseridSubject(string value)
        {
            return x => x.Subject == value;
        }
        /// <summary>恒真表达式（无筛选条件时的 Identity 值）</summary>
        public static Expression<Func<WrongQuestions, bool>> None => x => true;

        /// <summary>组合多个条件（AND 连接）。所有条件同时满足。</summary>
        public static Expression<Func<WrongQuestions, bool>> All(params Expression<Func<WrongQuestions, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.And(result, predicates[i]);
            return result;
        }

        /// <summary>组合多个条件（OR 连接）。任一条件满足即可。</summary>
        public static Expression<Func<WrongQuestions, bool>> Any(params Expression<Func<WrongQuestions, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.Or(result, predicates[i]);
            return result;
        }
    }

    // --- 链式 Builder（Entity.Where.ByXxx().ByYyy()，基类 PredicateBuilderBase<T> 提供 Update/Where/Or/If/隐式转换） ---
    /// <summary>链式条件构造器入口。<c>WrongQuestions.Where.ByMemberId(123).ByStatus(1)</c></summary>
    public static PredicateBuilder Where => new PredicateBuilder();

    public sealed class PredicateBuilder : PredicateBuilderBase<WrongQuestions>
    {

        /// <summary>组合条件：QuestionId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByQuestionId(string questionId)
            => (PredicateBuilder)Update(Conditions.ByQuestionId(questionId));

        /// <summary>模糊搜索：QuestionId（单个关键字）</summary>
        public PredicateBuilder LikeQuestionId(string? questionId = null)
            => (PredicateBuilder)Update(Conditions.LikeQuestionId(questionId));

        /// <summary>多值模糊搜索：QuestionId（按关键词 Or-链）</summary>
        public PredicateBuilder LikeQuestionIdKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeQuestionIdKeywords(keywords));

        /// <summary>跨属性精确匹配：QuestionId（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualQuestionId(string value)
            => (PredicateBuilder)Update(Conditions.EqualQuestionId(value));

        /// <summary>组合条件：Subject（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder BySubject(string subject)
            => (PredicateBuilder)Update(Conditions.BySubject(subject));

        /// <summary>模糊搜索：Subject（单个关键字）</summary>
        public PredicateBuilder LikeSubject(string? subject = null)
            => (PredicateBuilder)Update(Conditions.LikeSubject(subject));

        /// <summary>多值模糊搜索：Subject（按关键词 Or-链）</summary>
        public PredicateBuilder LikeSubjectKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeSubjectKeywords(keywords));

        /// <summary>跨属性精确匹配：Subject（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualSubject(string value)
            => (PredicateBuilder)Update(Conditions.EqualSubject(value));

        /// <summary>组合条件：UId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByUId(string uId)
            => (PredicateBuilder)Update(Conditions.ByUId(uId));

        /// <summary>模糊搜索：UId（单个关键字）</summary>
        public PredicateBuilder LikeUId(string? uId = null)
            => (PredicateBuilder)Update(Conditions.LikeUId(uId));

        /// <summary>多值模糊搜索：UId（按关键词 Or-链）</summary>
        public PredicateBuilder LikeUIdKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeUIdKeywords(keywords));

        /// <summary>跨属性精确匹配：UId（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualUId(string value)
            => (PredicateBuilder)Update(Conditions.EqualUId(value));

        /// <summary>组合条件：UserId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByUserId(long userId)
            => (PredicateBuilder)Update(Conditions.ByUserId(userId));

        /// <summary>组合条件：UseridMasteredLastwrongat（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByUseridMasteredLastwrongat(long userId, bool mastered, DateTime? beginLastWrongAt = null, DateTime? endLastWrongAt = null)
            => (PredicateBuilder)Update(Conditions.ByUseridMasteredLastwrongat(userId, mastered, beginLastWrongAt, endLastWrongAt));

        /// <summary>时间范围：LastWrongAt（begin/end 可选）</summary>
        public PredicateBuilder ByLastWrongAtRange(DateTime? begin = null, DateTime? end = null)
            => (PredicateBuilder)Update(Conditions.ByLastWrongAtRange(begin, end));

        /// <summary>精确匹配：UseridQuestionid（Unique 索引，必填参数）</summary>
        public PredicateBuilder ByUseridQuestionid(long userId, string questionId)
            => (PredicateBuilder)Update(Conditions.ByUseridQuestionid(userId, questionId));

        /// <summary>组合条件：UseridSubject（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByUseridSubject(long userId, string subject)
            => (PredicateBuilder)Update(Conditions.ByUseridSubject(userId, subject));

        /// <summary>多值模糊搜索：UseridSubject（按关键词 Or-链）</summary>
        public PredicateBuilder LikeUseridSubjectKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeUseridSubjectKeywords(keywords));

        /// <summary>跨属性精确匹配：UseridSubject（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualUseridSubject(string value)
            => (PredicateBuilder)Update(Conditions.EqualUseridSubject(value));
        // V4.9: 工厂方法（AOT 兼容，替代 Activator.CreateInstance）
        protected override PredicateBuilderBase<WrongQuestions> CreateBranch() => new PredicateBuilder();
}
}
